// packages/react/src/visual/display/3d-scatter/ThreeScatterPlot.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface ThreeScatterPlotProps {
  title?: string;
  mode?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/display/3d-scatter — visual.display.3d-scatter */
export const ThreeScatterPlot = forwardRef<HTMLElement, ThreeScatterPlotProps>(function ThreeScatterPlot(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-display-3d-scatter', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-display-3d-scatter" data-three-mode={props.mode} data-three-title={props.title} aria-label={props.title ?? '3D host'}>{children}</section>
  );
});

// packages/angular/src/visual/display/3d-scatter/three-scatter-plot.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface ThreeScatterPlotProps {
  title?: string;
  mode?: string;
  className?: string;
}

/** @rosettadash/angular/visual/display/3d-scatter — visual.display.3d-scatter */
@Component({
  selector: 'rd-display-3d-scatter',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-display-3d-scatter'" [ngClass]="rootClass()" [attr.data-three-mode]="mode()" [attr.data-three-title]="title()" [attr.aria-label]="title() ?? '3D host'"><ng-content /></section>
  `,
})
export class ThreeScatterPlot {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly mode = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-display-3d-scatter', this.className()].filter(Boolean).join(' '),
  );
}
