// packages/react/src/layout/accordion-link-list/AccordionLinkList.tsx
import { Accordion, type AccordionProps } from '../accordion/Accordion';
import { LinkList, type LinkListProps } from '../../visual/link-list/LinkList';

/** Public props for the accordion + link-list recipe. */
export interface AccordionLinkListProps
  extends Omit<AccordionProps, 'children'>,
    Pick<LinkListProps, 'items' | 'dense'> {}

/**
 * Recipe: collapsible nav / TOC composed from Accordion + LinkList.
 */
export function AccordionLinkList({
  title,
  open,
  defaultOpen = false,
  className,
  style,
  onOpenChange,
  onToggle,
  items = [],
  dense = false,
}: AccordionLinkListProps) {
  const recipeClass = ['rd-accordion-link-list', className]
    .filter(Boolean)
    .join(' ');

  return (
    <Accordion
      title={title}
      open={open}
      defaultOpen={defaultOpen}
      className={recipeClass}
      style={style}
      onOpenChange={onOpenChange}
      onToggle={onToggle}
    >
      <LinkList items={items} dense={dense} />
    </Accordion>
  );
}

// packages/svelte/src/layout/accordion-link-list/AccordionLinkList.svelte
<script lang="ts">
	import Accordion from '../accordion/Accordion.svelte';
	import LinkList from '../../visual/link-list/LinkList.svelte';
	import type { LinkListItem } from '../../visual/link-list/types';

	interface Props {
		title: string;
		open?: boolean;
		defaultOpen?: boolean;
		className?: string;
		items?: LinkListItem[];
		dense?: boolean;
	}

	let {
		title,
		defaultOpen = false,
		open = $bindable(defaultOpen),
		className,
		items = [],
		dense = false,
	}: Props = $props();

	const recipeClass = $derived(
		['rd-accordion-link-list', className].filter(Boolean).join(' '),
	);
</script>

<Accordion {title} bind:open {defaultOpen} className={recipeClass}>
	<LinkList {items} {dense} />
</Accordion>
