// packages/react/src/visual/input/number/NumberInput.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface NumberInputProps {
  label?: string;
  placeholder?: string;
  min?: number;
  max?: number;
  step?: number;
  value?: number;
  onChange?: (value: number) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/input/number — visual.input.number */
export const NumberInput = forwardRef<HTMLElement, NumberInputProps>(function NumberInput(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-input-number', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-input-number">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <input
        type="number"
        className="rd-input"
        placeholder={props.placeholder}
        min={props.min}
        max={props.max}
        step={props.step}
        value={props.value}
        onChange={(e) => props.onChange?.(Number(e.target.value))}
      />
      {children}
    </section>
  );
});

// packages/angular/src/visual/input/number/number-input.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface NumberInputProps {
  label?: string;
  placeholder?: string;
  min?: number;
  max?: number;
  step?: number;
  value?: number;
  onChange?: (value: number) => void;
  className?: string;
}

/** @rosettadash/angular/visual/input/number — visual.input.number */
@Component({
  selector: 'rd-input-number',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-input-number'" [ngClass]="rootClass()">
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      <input type="number" class="rd-input" [placeholder]="placeholder() ?? ''" [min]="min()" [max]="max()" [step]="step()" [value]="value()" />
      <ng-content />
    </section>
  `,
})
export class NumberInput {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly placeholder = input<string | undefined>(undefined);
  readonly min = input<number | undefined>(undefined);
  readonly max = input<number | undefined>(undefined);
  readonly step = input<number | undefined>(undefined);
  readonly value = input<number | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-input-number', this.className()].filter(Boolean).join(' '),
  );
}
