// packages/angular/src/infra/postgresql/postgresql-infra.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface PostgresqlInfraProps {
  label?: string;
  envKey?: string;
  tableOrCollection?: string;
  className?: string;
}

/** @rosettadash/angular/infra/postgresql — infra.postgresql */
@Component({
  selector: 'rd-postgresql',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-postgresql'" [ngClass]="rootClass()">
      <span class="rd-infra__badge">INFRA</span>
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      @if (envKey()) { <code>{{ envKey() }}</code> }
      @if (tableOrCollection()) { <span class="rd-infra__meta">{{ tableOrCollection() }}</span> }
      <ng-content />
    </section>
  `,
})
export class PostgresqlInfra {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly envKey = input<string | undefined>(undefined);
  readonly tableOrCollection = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-postgresql', this.className()].filter(Boolean).join(' '),
  );
}

// packages/react/src/infra/postgresql/PostgresqlInfra.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface PostgresqlInfraProps {
  label?: string;
  envKey?: string;
  tableOrCollection?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/infra/postgresql — infra.postgresql */
export const PostgresqlInfra = forwardRef<HTMLElement, PostgresqlInfraProps>(function PostgresqlInfra(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-postgresql', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-postgresql">
      <span className="rd-infra__badge">INFRA</span>
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      {props.envKey ? <code>{props.envKey}</code> : null}
      {props.tableOrCollection ? <span className="rd-infra__meta">{props.tableOrCollection}</span> : null}
      {children}
    </section>
  );
});
