// packages/react/src/visual/wasm/module/WasmModule.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface WasmModuleProps {
  moduleLabel?: string;
  exportName?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/wasm/module — visual.wasm.module */
export const WasmModule = forwardRef<HTMLElement, WasmModuleProps>(function WasmModule(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-wasm-module', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-wasm-module">
      <span className="rd-wasm__label">{props.moduleLabel ?? 'WASM Module'}</span>
      <code>{props.exportName ?? 'run()'}()</code>
      {children}
    </section>
  );
});

// packages/svelte/src/visual/wasm/module/WasmModule.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { WasmModuleProps } from './types';

	type Props = WasmModuleProps & { children?: Snippet };

	let {
		className,
		moduleLabel,
		exportName,
		children,
	}: Props = $props();
	const exportFnLabel = $derived(exportName ?? 'run()');
	const rootClass = $derived(['rd-wasm-module', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-wasm-module">
	<span class="rd-wasm__label">{moduleLabel ?? 'WASM Module'}</span>
	<code>{exportFnLabel}()</code>
	{@render children?.()}
</section>
