// packages/react/src/layout/tabs/TabsLayout.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface TabsLayoutTab {
  id: string;
  label: string;
}

export interface TabsLayoutProps {
  title?: string;
  tabs?: TabsLayoutTab[];
  activeTabId?: string;
  onTabChange?: (tabId: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/layout/tabs — layout.tabs */
export const TabsLayout = forwardRef<HTMLElement, TabsLayoutProps>(function TabsLayout(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-tabs', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-tabs">
      {props.title ? <span className="rd-tabs__title">{props.title}</span> : null}
      <div className="rd-tabs__tabs" role="tablist">
        {(props.tabs ?? []).map((tab) => (
          <button key={tab.id} type="button" role="tab" className={['rd-tabs__tab', props.activeTabId === tab.id ? 'rd-tabs__tab--active' : ''].filter(Boolean).join(' ')} onClick={() => props.onTabChange?.(tab.id)}>{tab.label}</button>
        ))}
      </div>
      <div className="rd-tabs__panel">{children}</div>
    </section>
  );
});

// packages/angular/src/layout/tabs/tabs-layout.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface TabsLayoutTab {
  id: string;
  label: string;
}

export interface TabsLayoutProps {
  title?: string;
  tabs?: TabsLayoutTab[];
  activeTabId?: string;
  onTabChange?: (tabId: string) => void;
  className?: string;
}

/** @rosettadash/angular/layout/tabs — layout.tabs */
@Component({
  selector: 'rd-tabs',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-tabs'" [ngClass]="rootClass()">
      @if (title()) { <span class="rd-tabs__title">{{ title() }}</span> }
      <div class="rd-tabs__tabs" role="tablist">
        @for (tab of tabs() ?? []; track tab.id) {
          <button type="button" role="tab" [class]="tabClass(tab.id)">{{ tab.label }}</button>
        }
      </div>
      <div class="rd-tabs__panel"><ng-content /></div>
    </section>
  `,
})
export class TabsLayout {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly tabs = input<TabsLayoutTab[] | undefined>(undefined);
  readonly activeTabId = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-tabs', this.className()].filter(Boolean).join(' '),
  );
  tabClass(id: string): string {
    return ['rd-tabs__tab', this.activeTabId() === id ? 'rd-tabs__tab--active' : ''].filter(Boolean).join(' ');
  }
}
