// packages/react/src/visual/media/video-source/VideoSource.tsx
import { createElement, type CSSProperties } from 'react';
import {
  DB_VIDEO_SOURCE_TAG,
  registerRdVideoSource,
} from '@rosettadash/web-components/visual/media/video-source';
import { useCustomElementHost } from '../../../lib/custom-element-host';

export interface VideoSourceProps {
  label?: string;
  accept?: string;
  sourceWidth?: number;
  sourceHeight?: number;
  className?: string;
  style?: CSSProperties;
  onVideoFile?: (detail: {
    file: File;
    metadata: Record<string, string | number | boolean | null | undefined>;
  }) => void;
  onMetadata?: (
    detail: Record<string, string | number | boolean | null | undefined>,
  ) => void;
}

/** React wrapper around `<rd-video-source>`. */
export function VideoSource({
  label,
  accept,
  sourceWidth,
  sourceHeight,
  className,
  style,
  onVideoFile,
  onMetadata,
}: VideoSourceProps) {
  const host = useCustomElementHost(
    {
      register: registerRdVideoSource,
      attrs: {
        sourceWidth: 'source-width',
        sourceHeight: 'source-height',
      },
      events: {
        'video-file': 'onVideoFile',
        metadata: 'onMetadata',
      },
    },
    { label, accept, sourceWidth, sourceHeight },
    {
      onVideoFile: onVideoFile as ((detail: unknown) => void) | undefined,
      onMetadata: onMetadata as ((detail: unknown) => void) | undefined,
    },
  );

  return createElement(DB_VIDEO_SOURCE_TAG, {
    ref: host,
    className,
    style,
  });
}

// packages/svelte/src/visual/media/video-source/VideoSource.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import {
		DB_VIDEO_SOURCE_TAG,
		registerRdVideoSource,
	} from '@rosettadash/web-components/visual/media/video-source';
	import {
		attachHostEvents,
		setHostAttribute,
	} from '../../../lib/custom-element-host';
	import type { VideoFileDetail, VideoSourceProps } from './types';

	let {
		label,
		accept,
		sourceWidth,
		sourceHeight,
		className,
		onVideoFile,
		onMetadata,
	}: VideoSourceProps = $props();

	let host: HTMLElement;
	let detachEvents = () => {};

	onMount(() => {
		registerRdVideoSource();
		detachEvents = attachHostEvents(host, {
			'video-file': (detail) => onVideoFile?.(detail as VideoFileDetail),
			metadata: (detail) =>
				onMetadata?.(
					detail as Record<string, string | number | boolean | null | undefined>,
				),
		});
		return () => detachEvents();
	});

	$effect(() => {
		if (!host) {
			return;
		}
		setHostAttribute(host, 'label', label);
		setHostAttribute(host, 'accept', accept);
		setHostAttribute(host, 'source-width', sourceWidth);
		setHostAttribute(host, 'source-height', sourceHeight);
	});
</script>

<svelte:element this={DB_VIDEO_SOURCE_TAG} bind:this={host} class={className} />
