// packages/exporters-web-components/src/lib/component-templates.ts
import type { IRComponent } from '@dashbuilder/core';
import { WebComponentsExportError } from './types';
import { customElementTag, joinLines } from './utils';

const SUPPORTED_TYPES = new Set([
  'visual.input.text',
  'visual.input.select',
  'visual.input.date-range',
  'domain.time-preset',
  'visual.table',
  'visual.detail',
  'visual.skeleton',
  'visual.kpi',
  'visual.chart.line',
  'visual.chart.bar',
  'visual.chart.pie',
  'visual.display.3d-bar-chart',
  'visual.display.3d-scatter',
  'visual.display.3d-scene',
  'visual.display.3d-gltf-model',
  'visual.display.3d-geo-globe',
  'logic.timer',
  'visual.news.language-select',
  'visual.news.region-select',
  'visual.news.type-select',
  'visual.news.search-box',
  'visual.news.results-table',
  'visual.news.article-detail',
]);

export function generateComponentFile(component: IRComponent, exportName: string): string {
  if (!SUPPORTED_TYPES.has(component.type)) {
    throw new WebComponentsExportError(
      `Unsupported Web Components export component type: ${component.type}`,
    );
  }

  switch (component.type) {
    case 'visual.input.text':
    case 'visual.news.search-box':
      return generateTextInput(exportName);
    case 'visual.input.select':
    case 'visual.news.language-select':
    case 'visual.news.region-select':
    case 'visual.news.type-select':
      return generateSelectInput(exportName);
    case 'visual.input.date-range':
      return generateDateRangeFilter(exportName);
    case 'domain.time-preset':
      return generateTimePreset(exportName);
    case 'visual.table':
    case 'visual.news.results-table':
      return generateDataTable(exportName);
    case 'visual.detail':
    case 'visual.news.article-detail':
      return generateDetailPanel(exportName);
    case 'visual.skeleton':
      return generateSkeleton(exportName);
    case 'visual.kpi':
      return generateKpiCard(exportName);
    case 'visual.chart.line':
      return generateLineChart(exportName);
    case 'visual.chart.bar':
      return generateBarChart(exportName);
    case 'visual.chart.pie':
      return generatePieChart(exportName);
    case 'logic.timer':
      return generateTimer(exportName);
    default:
      return generatePlaceholder(exportName, component.label, component.type);
  }
}

function shellStyles(): string {
  return [
    `:host { display: block; font-family: system-ui, sans-serif; color: var(--db-text, #1f2937); }`,
    `.field, .input, .select, .table, .kpi-card, .chart-card, .detail-panel, .timer, .skeleton {`,
    `  border: 1px solid var(--db-border, #d9dee7); border-radius: 0.5rem; }`,
    `.input, .select { width: 100%; padding: 0.5rem 0.75rem; box-sizing: border-box; }`,
    `.table { width: 100%; border-collapse: collapse; }`,
    `.table th, .table td { padding: 0.5rem 0.75rem; text-align: left; }`,
    `.kpi-card, .chart-card, .detail-panel, .timer, .skeleton { padding: 1rem; }`,
    `.table-row { cursor: pointer; }`,
    `.table-row--selected { background: color-mix(in srgb, var(--db-accent, #2563eb) 12%, transparent); }`,
  ].join('\n');
}

function generateClassShell(
  exportName: string,
  bodyHtml: string,
  extraMembers = '',
  extraMethods = '',
): string {
  const tag = customElementTag(exportName);
  return joinLines([
    `import type { DateRange, Row } from '../types';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`${shellStyles()}\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${tag}';`,
    `  private renderRoot: ShadowRoot;`,
    ``,
    `  constructor() {`,
    `    super();`,
    `    this.renderRoot = this.attachShadow({ mode: 'open' });`,
    `  }`,
    ``,
    `  connectedCallback(): void {`,
    `    this.renderRoot.innerHTML = \`<style>\${STYLES}</style>${bodyHtml}\`;`,
    `    this.bindDom();`,
    `  }`,
    ``,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    ``,
    `  protected bindDom(): void {}`,
    `  protected render(): void {}`,
    extraMembers,
    extraMethods,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

function generateTextInput(exportName: string): string {
  return joinLines([
    `import type { Row } from '../types';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`${shellStyles()}\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${customElementTag(exportName)}';`,
    `  private input: HTMLInputElement | null = null;`,
    `  placeholder = '';`,
    `  required = false;`,
    `  value = '';`,
    ``,
    `  connectedCallback(): void {`,
    `    this.render();`,
    `  }`,
    ``,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    ``,
    `  private render(): void {`,
    `    if (!this.shadowRoot) {`,
    `      this.attachShadow({ mode: 'open' });`,
    `    }`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><label class="field"><input class="input" type="text" placeholder="\${this.placeholder}" ?required="\${this.required}" value="\${this.value}" /></label>\`;`,
    `    this.input = this.shadowRoot!.querySelector('input');`,
    `    this.input?.addEventListener('input', () => {`,
    `      this.value = this.input?.value ?? '';`,
    `      this.dispatchEvent(new CustomEvent('value-change', { detail: this.value, bubbles: true }));`,
    `    });`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

function generateSelectInput(exportName: string): string {
  return joinLines([
    `import type { Row } from '../types';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`${shellStyles()}\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${customElementTag(exportName)}';`,
    `  placeholder = 'Select…';`,
    `  options: Row[] = [];`,
    `  value = '';`,
    ``,
    `  connectedCallback(): void {`,
    `    this.render();`,
    `  }`,
    ``,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    ``,
    `  private render(): void {`,
    `    if (!this.shadowRoot) {`,
    `      this.attachShadow({ mode: 'open' });`,
    `    }`,
    `    const optionMarkup = this.options`,
    `      .map((option, index) => {`,
    `        const value = String(option.id ?? option.label ?? index);`,
    `        const label = String(option.label ?? option.id ?? index);`,
    `        return \`<option value="\${value}">\${label}</option>\`;`,
    `      })`,
    `      .join('');`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><label class="field"><select class="select"><option value="">\${this.placeholder}</option>\${optionMarkup}</select></label>\`;`,
    `    const select = this.shadowRoot!.querySelector('select');`,
    `    if (select) {`,
    `      select.value = this.value;`,
    `      select.addEventListener('change', () => {`,
    `        this.value = select.value;`,
    `        this.dispatchEvent(new CustomEvent('value-change', { detail: this.value, bubbles: true }));`,
    `      });`,
    `    }`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

function generateDateRangeFilter(exportName: string): string {
  return joinLines([
    `import type { DateRange } from '../types';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`${shellStyles()} .date-range { display: grid; gap: 0.5rem; padding: 0.75rem; }\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${customElementTag(exportName)}';`,
    `  range: DateRange | undefined;`,
    ``,
    `  connectedCallback(): void {`,
    `    this.render();`,
    `  }`,
    ``,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `  }`,
    ``,
    `  private emitRange(start: string, end: string): void {`,
    `    this.range = { start, end };`,
    `    this.dispatchEvent(new CustomEvent('range-change', { detail: this.range, bubbles: true }));`,
    `  }`,
    ``,
    `  private render(): void {`,
    `    if (!this.shadowRoot) {`,
    `      this.attachShadow({ mode: 'open' });`,
    `    }`,
    `    const start = this.range?.start ?? '';`,
    `    const end = this.range?.end ?? '';`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><div class="date-range"><label>Start<input class="input" type="date" value="\${start}" /></label><label>End<input class="input" type="date" value="\${end}" /></label></div>\`;`,
    `    const inputs = this.shadowRoot!.querySelectorAll('input');`,
    `    inputs.forEach((input) => {`,
    `      input.addEventListener('change', () => {`,
    `        const values = [...this.shadowRoot!.querySelectorAll('input')].map((el) => (el as HTMLInputElement).value);`,
    `        this.emitRange(values[0] ?? '', values[1] ?? '');`,
    `      });`,
    `    });`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

function generateTimePreset(exportName: string): string {
  return generatePlaceholder(exportName, 'Time preset', 'domain.time-preset');
}

function generateDataTable(exportName: string): string {
  return joinLines([
    `import type { Row } from '../types';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`${shellStyles()}\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${customElementTag(exportName)}';`,
    `  data: Row[] = [];`,
    `  selectedRow: Row | undefined;`,
    ``,
    `  connectedCallback(): void {`,
    `    this.render();`,
    `  }`,
    ``,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    ``,
    `  private render(): void {`,
    `    if (!this.shadowRoot) {`,
    `      this.attachShadow({ mode: 'open' });`,
    `    }`,
    `    const columns = this.data.length > 0 ? Object.keys(this.data[0]) : ['label', 'value'];`,
    `    const head = columns.map((column) => \`<th>\${column}</th>\`).join('');`,
    `    const rows = this.data`,
    `      .map((row, index) => {`,
    `        const cells = columns.map((column) => \`<td>\${String(row[column] ?? '')}</td>\`).join('');`,
    `        const selected = this.selectedRow === row ? ' table-row--selected' : '';`,
    `        return \`<tr class="table-row\${selected}" data-index="\${index}">\${cells}</tr>\`;`,
    `      })`,
    `      .join('');`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><table class="table"><thead><tr>\${head}</tr></thead><tbody>\${rows}</tbody></table>\`;`,
    `    this.shadowRoot!.querySelectorAll('.table-row').forEach((rowEl) => {`,
    `      rowEl.addEventListener('click', () => {`,
    `        const index = Number((rowEl as HTMLElement).dataset.index ?? '-1');`,
    `        const next = this.data[index];`,
    `        this.selectedRow = next;`,
    `        this.dispatchEvent(new CustomEvent('row-select', { detail: next, bubbles: true }));`,
    `        this.render();`,
    `      });`,
    `    });`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

function generateDetailPanel(exportName: string): string {
  return joinLines([
    `import type { Row } from '../types';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`${shellStyles()} .detail-panel__empty { color: var(--db-muted, #6b7280); }\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${customElementTag(exportName)}';`,
    `  selectedRow: Row | undefined;`,
    ``,
    `  connectedCallback(): void {`,
    `    this.render();`,
    `  }`,
    ``,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    ``,
    `  private render(): void {`,
    `    if (!this.shadowRoot) {`,
    `      this.attachShadow({ mode: 'open' });`,
    `    }`,
    `    if (!this.selectedRow) {`,
    `      this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><section class="detail-panel"><p class="detail-panel__empty">Select a row to view details.</p></section>\`;`,
    `      return;`,
    `    }`,
    `    const fields = Object.entries(this.selectedRow)`,
    `      .map(([key, value]) => \`<div><dt>\${key}</dt><dd>\${String(value ?? '')}</dd></div>\`)`,
    `      .join('');`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><section class="detail-panel"><dl>\${fields}</dl></section>\`;`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

function generateSkeleton(exportName: string): string {
  return generatePlaceholder(exportName, 'Loading skeleton', 'visual.skeleton');
}

function generateKpiCard(exportName: string): string {
  return joinLines([
    `import type { Row } from '../types';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`${shellStyles()} .kpi-card__value { font-size: 1.5rem; font-weight: 700; margin: 0.25rem 0 0; }\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${customElementTag(exportName)}';`,
    `  title = 'KPI';`,
    `  data: Row[] = [];`,
    ``,
    `  connectedCallback(): void {`,
    `    this.render();`,
    `  }`,
    ``,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    ``,
    `  private render(): void {`,
    `    if (!this.shadowRoot) {`,
    `      this.attachShadow({ mode: 'open' });`,
    `    }`,
    `    const value = this.data.length > 0 ? String(Object.values(this.data[0])[0] ?? '—') : '—';`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><section class="kpi-card"><h3>\${this.title}</h3><p class="kpi-card__value">\${value}</p></section>\`;`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

function generateLineChart(exportName: string): string {
  return joinLines([
    `import type { Row } from '../types';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`${shellStyles()} .chart-card svg { width: 100%; height: 8rem; }\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${customElementTag(exportName)}';`,
    `  title = 'Line chart';`,
    `  data: Row[] = [];`,
    ``,
    `  connectedCallback(): void {`,
    `    this.render();`,
    `  }`,
    ``,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    ``,
    `  private render(): void {`,
    `    if (!this.shadowRoot) {`,
    `      this.attachShadow({ mode: 'open' });`,
    `    }`,
    `    const values = this.data.map((row, index) => Number(row.value ?? index + 1));`,
    `    const points = values.length`,
    `      ? values.map((value, index) => \`\${(index / Math.max(values.length - 1, 1)) * 100},\${100 - value}\`).join(' ')`,
    `      : '0,100 100,0';`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><section class="chart-card"><h3>\${this.title}</h3><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline fill="none" stroke="var(--db-accent, #2563eb)" stroke-width="2" points="\${points}" /></svg></section>\`;`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

function generateBarChart(exportName: string): string {
  return generateLineChart(exportName);
}

function generatePieChart(exportName: string): string {
  return joinLines([
    `import type { Row } from '../types';`,
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`${shellStyles()} .pie-chart { width: 8rem; height: 8rem; border-radius: 999px; border: 1px solid var(--db-border, #d9dee7); margin: 0 auto; }\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${customElementTag(exportName)}';`,
    `  title = 'Pie chart';`,
    `  donut = false;`,
    `  data: Row[] = [];`,
    ``,
    `  connectedCallback(): void {`,
    `    this.render();`,
    `  }`,
    ``,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    ``,
    `  private render(): void {`,
    `    if (!this.shadowRoot) {`,
    `      this.attachShadow({ mode: 'open' });`,
    `    }`,
    `    const donutClass = this.donut ? ' pie-chart--donut' : '';`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><section class="chart-card"><h3>\${this.title}</h3><div class="pie-chart\${donutClass}"></div></section>\`;`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

function generateTimer(exportName: string): string {
  return generatePlaceholder(exportName, 'Timer', 'logic.timer');
}

function generatePlaceholder(exportName: string, label: string, type: string): string {
  return joinLines([
    `import { defineDashElement } from '../define-element';`,
    ``,
    `const STYLES = \`:host { display: block; padding: 1rem; border: 1px dashed var(--db-border, #d9dee7); border-radius: 0.5rem; color: var(--db-muted, #6b7280); font: 0.875rem system-ui, sans-serif; }\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${customElementTag(exportName)}';`,
    ``,
    `  connectedCallback(): void {`,
    `    if (!this.shadowRoot) {`,
    `      this.attachShadow({ mode: 'open' });`,
    `    }`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><p>${label} <code>${type}</code></p>\`;`,
    `  }`,
    ``,
    `  setProperty(_name: string, _value: unknown): void {}`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineDashElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

export function generateDefineElementHelper(): string {
  return joinLines([
    `export function defineDashElement(`,
    `  tagName: string,`,
    `  ctor: CustomElementConstructor,`,
    `): void {`,
    `  if (!customElements.get(tagName)) {`,
    `    customElements.define(tagName, ctor);`,
    `  }`,
    `}`,
    ``,
  ]);
}

export function generateRegisterAllFile(componentNames: string[]): string {
  return joinLines([
    ...componentNames.map((name) => `import { register${name} } from './components/${name}';`),
    `import { registerDbDashboard } from './dashboard';`,
    ``,
    `export function registerDashBuilderElements(): void {`,
    ...componentNames.map((name) => `  register${name}();`),
    `  registerDbDashboard();`,
    `}`,
    ``,
  ]);
}

// packages/exporters-angular/src/lib/component-templates.ts
import type { IRComponent } from '@dashbuilder/core';
import { AngularExportError } from './types';
import {
  generateThreeBarChart,
  generateThreeScatterPlot,
  generateThreeScenePointCloud,
  generateThreeGltfModel,
  generateThreeGeoGlobe,
} from './three-visual-templates';
import { joinLines, selectorFromClass } from './utils';

const SUPPORTED_TYPES = new Set([
  'visual.input.text',
  'visual.input.select',
  'visual.input.date-range',
  'domain.time-preset',
  'visual.table',
  'visual.detail',
  'visual.skeleton',
  'visual.kpi',
  'visual.chart.line',
  'visual.chart.bar',
  'visual.chart.pie',
  'visual.display.3d-bar-chart',
  'visual.display.3d-scatter',
  'visual.display.3d-scene',
  'visual.display.3d-gltf-model',
  'visual.display.3d-geo-globe',
  'logic.timer',
  'visual.news.language-select',
  'visual.news.region-select',
  'visual.news.type-select',
  'visual.news.search-box',
  'visual.news.results-table',
  'visual.news.article-detail',
]);

export function generateComponentFile(component: IRComponent, className: string): string {
  if (!SUPPORTED_TYPES.has(component.type)) {
    throw new AngularExportError(`Unsupported Angular export component type: ${component.type}`);
  }

  switch (component.type) {
    case 'visual.input.text':
      return generateTextInput(className);
    case 'visual.input.select':
      return generateSelectInput(className);
    case 'visual.input.date-range':
      return generateDateRangeFilter(className);
    case 'domain.time-preset':
      return generateTimePreset(className);
    case 'visual.table':
      return generateDataTable(className);
    case 'visual.detail':
      return generateDetailPanel(className);
    case 'visual.skeleton':
      return generateSkeleton(className);
    case 'visual.kpi':
      return generateKpiCard(className);
    case 'visual.chart.line':
      return generateLineChart(className);
    case 'visual.chart.bar':
      return generateBarChart(className);
    case 'visual.chart.pie':
      return generatePieChart(className);
    case 'visual.display.3d-bar-chart':
      return generateThreeBarChart(className);
    case 'visual.display.3d-scatter':
      return generateThreeScatterPlot(className);
    case 'visual.display.3d-scene':
      return generateThreeScenePointCloud(className);
    case 'visual.display.3d-gltf-model':
      return generateThreeGltfModel(className);
    case 'visual.display.3d-geo-globe':
      return generateThreeGeoGlobe(className);
    case 'logic.timer':
      return generateTimer(className);
    case 'visual.news.language-select':
    case 'visual.news.region-select':
    case 'visual.news.type-select':
      return generateSelectInput(className);
    case 'visual.news.search-box':
      return generateTextInput(className);
    case 'visual.news.results-table':
      return generateDataTable(className);
    case 'visual.news.article-detail':
      return generateDetailPanel(className);
    default:
      throw new AngularExportError(`Missing Angular template for ${component.type}`);
  }
}

function generateTextInput(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input, output } from '@angular/core';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <label class="field" [attr.for]="id()">`,
    `      <input`,
    `        class="input"`,
    `        type="text"`,
    `        [id]="id()"`,
    `        [placeholder]="placeholder()"`,
    `        [required]="required()"`,
    `        [value]="value() ?? ''"`,
    `        (input)="valueChange.emit($any($event.target).value)"`,
    `      />`,
    `    </label>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  placeholder = input('');`,
    `  required = input(false);`,
    `  value = input<string>();`,
    `  valueChange = output<string>();`,
    `}`,
    ``,
  ]);
}

function generateSelectInput(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input, output } from '@angular/core';`,
    `import type { Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <label class="field" [attr.for]="id()">`,
    `      <select`,
    `        class="select"`,
    `        [id]="id()"`,
    `        [value]="value() ?? ''"`,
    `        (change)="valueChange.emit($any($event.target).value)"`,
    `      >`,
    `        <option value="">{{ placeholder() }}</option>`,
    `        @for (option of options(); track option.id ?? $index) {`,
    `          <option [value]="option.id ?? option.label ?? $index">`,
    `            {{ option.label ?? option.id ?? $index }}`,
    `          </option>`,
    `        }`,
    `      </select>`,
    `    </label>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  placeholder = input('Select…');`,
    `  options = input<Row[]>([]);`,
    `  value = input<string>();`,
    `  valueChange = output<string>();`,
    `}`,
    ``,
  ]);
}

function generateDateRangeFilter(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input, output } from '@angular/core';`,
    `import type { DateRange } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <div class="date-range" [id]="id()">`,
    `      <label class="field">`,
    `        <span>Start</span>`,
    `        <input`,
    `          class="input"`,
    `          type="date"`,
    `          [value]="current().start"`,
    `          (input)="onStartChange($any($event.target).value)"`,
    `        />`,
    `      </label>`,
    `      <label class="field">`,
    `        <span>End</span>`,
    `        <input`,
    `          class="input"`,
    `          type="date"`,
    `          [value]="current().end"`,
    `          (input)="onEndChange($any($event.target).value)"`,
    `        />`,
    `      </label>`,
    `    </div>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  preset = input('last-7-days');`,
    `  value = input<DateRange>();`,
    `  valueChange = output<DateRange>();`,
    ``,
    `  current(): DateRange {`,
    `    return this.value() ?? defaultRangeForPreset(this.preset());`,
    `  }`,
    ``,
    `  onStartChange(start: string): void {`,
    `    this.valueChange.emit({ ...this.current(), start });`,
    `  }`,
    ``,
    `  onEndChange(end: string): void {`,
    `    this.valueChange.emit({ ...this.current(), end });`,
    `  }`,
    `}`,
    ``,
    `function defaultRangeForPreset(preset: string): DateRange {`,
    `  const end = new Date();`,
    `  const start = new Date(end);`,
    `  if (preset === 'last-30-days') {`,
    `    start.setDate(end.getDate() - 30);`,
    `  } else if (preset === 'qtd') {`,
    `    start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `  } else {`,
    `    start.setDate(end.getDate() - 7);`,
    `  }`,
    `  return { start: formatDate(start), end: formatDate(end) };`,
    `}`,
    ``,
    `function formatDate(date: Date): string {`,
    `  return date.toISOString().slice(0, 10);`,
    `}`,
    ``,
  ]);
}

function generateTimePreset(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input, output, signal } from '@angular/core';`,
    `import type { DateRange } from '../types';`,
    ``,
    `const PRESET_OPTIONS = [`,
    `  { id: 'last-7-days', label: 'Last 7 days' },`,
    `  { id: 'last-30-days', label: 'Last 30 days' },`,
    `  { id: 'qtd', label: 'Quarter to date' },`,
    `] as const;`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <div class="time-preset" [id]="id()">`,
    `      <span class="time-preset__label">{{ label() }}</span>`,
    `      <div class="time-preset__buttons">`,
    `        @for (preset of presets; track preset.id) {`,
    `          <button`,
    `            type="button"`,
    `            class="time-preset__button"`,
    `            [class.time-preset__button--active]="isActive(preset.id)"`,
    `            (click)="selectPreset(preset.id)"`,
    `          >`,
    `            {{ preset.label }}`,
    `          </button>`,
    `        }`,
    `      </div>`,
    `    </div>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  label = input('Period');`,
    `  defaultPreset = input('last-7-days');`,
    `  value = input<DateRange>();`,
    `  valueChange = output<DateRange>();`,
    ``,
    `  protected readonly presets = PRESET_OPTIONS;`,
    `  protected readonly activePreset = signal<string | null>(null);`,
    ``,
    `  protected isActive(preset: string): boolean {`,
    `    return (this.activePreset() ?? this.defaultPreset()) === preset;`,
    `  }`,
    ``,
    `  selectPreset(preset: string): void {`,
    `    this.activePreset.set(preset);`,
    `    this.valueChange.emit(defaultRangeForPreset(preset));`,
    `  }`,
    `}`,
    ``,
    `function defaultRangeForPreset(preset: string): DateRange {`,
    `  const end = new Date();`,
    `  const start = new Date(end);`,
    `  if (preset === 'last-30-days') {`,
    `    start.setDate(end.getDate() - 30);`,
    `  } else if (preset === 'qtd') {`,
    `    start.setMonth(Math.floor(end.getMonth() / 3) * 3, 1);`,
    `  } else {`,
    `    start.setDate(end.getDate() - 7);`,
    `  }`,
    `  return { start: formatDate(start), end: formatDate(end) };`,
    `}`,
    ``,
    `function formatDate(date: Date): string {`,
    `  return date.toISOString().slice(0, 10);`,
    `}`,
    ``,
  ]);
}

function generateDataTable(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="table-card" [id]="id()" [attr.data-sortable]="sortable()" [attr.data-filterable]="filterable()">`,
    `      <table class="table">`,
    `        <thead>`,
    `          <tr>`,
    `            @for (column of columns(); track column) {`,
    `              <th>{{ column }}</th>`,
    `            }`,
    `          </tr>`,
    `        </thead>`,
    `        <tbody>`,
    `          @for (row of rows(); track row.id ?? $index) {`,
    `            <tr`,
    `              class="table-row"`,
    `              [class.table-row--selected]="selectedRow()?.id === row.id"`,
    `              (click)="handleRowSelect(row)"`,
    `            >`,
    `              @for (column of columns(); track column) {`,
    `                <td>{{ row[column] ?? '' }}</td>`,
    `              }`,
    `            </tr>`,
    `          }`,
    `        </tbody>`,
    `      </table>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  data = input<Row[]>([]);`,
    `  filter = input<DateRange>();`,
    `  pageSize = input(25);`,
    `  sortable = input(true);`,
    `  filterable = input(true);`,
    `  selectedRow = input<Row>();`,
    `  onSelectRow = input<(row: Row) => void>();`,
    ``,
    `  rows = computed(() => filterRows(this.data(), this.filter()).slice(0, this.pageSize()));`,
    `  columns = computed(() => {`,
    `    const first = this.rows()[0];`,
    `    return first ? Object.keys(first) : ['id', 'label', 'value'];`,
    `  });`,
    ``,
    `  protected handleRowSelect(row: Row): void {`,
    `    this.onSelectRow()?.(row);`,
    `  }`,
    `}`,
    ``,
    `function filterRows(data: Row[], filter?: DateRange): Row[] {`,
    `  if (!filter) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row['date'] ?? row['createdAt'] ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= filter.start && value <= filter.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateDetailPanel(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="detail-panel" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      @if (fields().length === 0) {`,
    `        <p class="detail-panel__empty">{{ emptyMessage() }}</p>`,
    `      } @else {`,
    `        <dl class="detail-panel__fields">`,
    `          @for (field of fields(); track field.key) {`,
    `            <div class="detail-panel__field">`,
    `              <dt>{{ field.key }}</dt>`,
    `              <dd>{{ field.value }}</dd>`,
    `            </div>`,
    `          }`,
    `        </dl>`,
    `      }`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Details');`,
    `  emptyMessage = input('Select a row to view details');`,
    `  row = input<Row>();`,
    ``,
    `  fields = computed(() => {`,
    `    const current = this.row();`,
    `    if (!current) {`,
    `      return [] as Array<{ key: string; value: string }>;`,
    `    }`,
    `    return Object.entries(current).map(([key, value]) => ({`,
    `      key,`,
    `      value: String(value ?? ''),`,
    `    }));`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateSkeleton(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    @if (loading()) {`,
    `      <div class="skeleton skeleton--{{ variant() }}" [id]="id()" aria-busy="true">`,
    `        @if (variant() === 'chart') {`,
    `          <div class="skeleton__chart-block"></div>`,
    `          <div class="skeleton__legend">`,
    `            @for (line of lineIndexes(); track line) {`,
    `              <span class="skeleton__line skeleton__line--short"></span>`,
    `            }`,
    `          </div>`,
    `        } @else if (variant() === 'kpi') {`,
    `          <span class="skeleton__line skeleton__line--title"></span>`,
    `          <span class="skeleton__line skeleton__line--value"></span>`,
    `        } @else {`,
    `          @for (line of lineIndexes(); track line) {`,
    `            <span class="skeleton__line"></span>`,
    `          }`,
    `        }`,
    `      </div>`,
    `    }`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  loading = input(true);`,
    `  variant = input<'table' | 'chart' | 'kpi' | 'card'>('table');`,
    `  lines = input(4);`,
    ``,
    `  lineIndexes = computed(() => {`,
    `    const count = Math.max(1, Math.min(this.lines(), 8));`,
    `    return Array.from({ length: count }, (_, index) => index);`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateKpiCard(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, input } from '@angular/core';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <article class="kpi-card" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <p class="kpi-value">{{ formatValue(value(), format()) }}</p>`,
    `    </article>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Metric');`,
    `  format = input<'number' | 'currency' | 'percent'>('number');`,
    `  value = input(0);`,
    `}`,
    ``,
    `function formatValue(value: number, format: 'number' | 'currency' | 'percent'): string {`,
    `  if (format === 'currency') {`,
    `    return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'USD' }).format(value);`,
    `  }`,
    `  if (format === 'percent') {`,
    `    return new Intl.NumberFormat(undefined, { style: 'percent', maximumFractionDigits: 1 }).format(value / 100);`,
    `  }`,
    `  return new Intl.NumberFormat().format(value);`,
    `}`,
    ``,
  ]);
}

function generateLineChart(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <svg class="line-chart" viewBox="0 0 320 120" role="img" [attr.aria-label]="title()">`,
    `        <polyline fill="none" stroke="currentColor" stroke-width="2" [attr.points]="points()" />`,
    `      </svg>`,
    `      <p class="chart-meta">{{ filtered().length }} points · x={{ xField() }} · y={{ yField() }}</p>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Chart');`,
    `  xField = input('date');`,
    `  yField = input('value');`,
    `  data = input<Row[]>([]);`,
    `  range = input<DateRange>();`,
    ``,
    `  filtered = computed(() => filterByRange(this.data(), this.range()));`,
    `  points = computed(() => {`,
    `    const rows = this.filtered();`,
    `    const max = Math.max(...rows.map((row) => Number(row[this.yField()] ?? 0)), 1);`,
    `    return rows`,
    `      .map((row, index) => {`,
    `        const x = (index / Math.max(rows.length - 1, 1)) * 300 + 10;`,
    `        const y = 110 - (Number(row[this.yField()] ?? 0) / max) * 90;`,
    `        return \`\${x},\${y}\`;`,
    `      })`,
    `      .join(' ');`,
    `  });`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row['date'] ?? row['createdAt'] ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateBarChart(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div class="bar-chart">`,
    `        @for (row of filtered(); track row.id ?? $index) {`,
    `          <div`,
    `            class="bar"`,
    `            [style.height.%]="barHeight(row)"`,
    `            [title]="String(row.label ?? row.id ?? $index)"`,
    `          ></div>`,
    `        }`,
    `      </div>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Chart');`,
    `  data = input<Row[]>([]);`,
    `  range = input<DateRange>();`,
    ``,
    `  filtered = computed(() => filterByRange(this.data(), this.range()));`,
    ``,
    `  barHeight(row: Row): number {`,
    `    const max = Math.max(...this.filtered().map((entry) => Number(entry['value'] ?? 0)), 1);`,
    `    return (Number(row['value'] ?? 0) / max) * 100;`,
    `  }`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row['date'] ?? row['createdAt'] ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generatePieChart(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, computed, input } from '@angular/core';`,
    `import type { DateRange, Row } from '../types';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="chart-card" [id]="id()">`,
    `      <h3>{{ title() }}</h3>`,
    `      <div`,
    `        class="pie-chart"`,
    `        [class.pie-chart--donut]="donut()"`,
    `        [style.background]="gradient()"`,
    `      ></div>`,
    `      <ul class="pie-chart__legend">`,
    `        @for (row of filtered(); track row.id ?? $index) {`,
    `          <li>`,
    `            <span [style.background]="color($index)"></span>`,
    `            {{ String(row[labelField()] ?? row.id ?? $index) }}`,
    `          </li>`,
    `        }`,
    `      </ul>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  title = input('Chart');`,
    `  labelField = input('label');`,
    `  valueField = input('value');`,
    `  donut = input(false);`,
    `  data = input<Row[]>([]);`,
    `  range = input<DateRange>();`,
    ``,
    `  filtered = computed(() => filterByRange(this.data(), this.range()));`,
    ``,
    `  gradient = computed(() => {`,
    `    const colors = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];`,
    `    const total = this.filtered().reduce((sum, row) => sum + Number(row[this.valueField()] ?? 0), 0) || 1;`,
    `    let cumulative = 0;`,
    `    const stops = this.filtered().map((row, index) => {`,
    `      const value = Number(row[this.valueField()] ?? 0);`,
    `      const percent = (value / total) * 100;`,
    `      const start = cumulative;`,
    `      cumulative += percent;`,
    `      return \`\${colors[index % colors.length]} \${start}% \${cumulative}%\`;`,
    `    });`,
    `    return \`conic-gradient(\${stops.join(', ') || '#d1d5db 0 100%'})\`;`,
    `  });`,
    ``,
    `  color(index: number): string {`,
    `    const colors = ['#3b82f6', '#10b981', '#f59e0b', '#ef4444', '#8b5cf6'];`,
    `    return colors[index % colors.length] ?? colors[0];`,
    `  }`,
    `}`,
    ``,
    `function filterByRange(data: Row[], range?: DateRange): Row[] {`,
    `  if (!range) {`,
    `    return data;`,
    `  }`,
    `  return data.filter((row) => {`,
    `    const value = String(row['date'] ?? row['createdAt'] ?? '');`,
    `    if (!value) {`,
    `      return true;`,
    `    }`,
    `    return value >= range.start && value <= range.end;`,
    `  });`,
    `}`,
    ``,
  ]);
}

function generateTimer(className: string): string {
  const selector = selectorFromClass(className);
  return joinLines([
    `import { Component, effect, input, output, signal } from '@angular/core';`,
    ``,
    `@Component({`,
    `  selector: '${selector}',`,
    `  standalone: true,`,
    `  template: \``,
    `    <section class="timer" [id]="id()">`,
    `      <div class="timer__header">`,
    `        <span class="timer__label">{{ label() }}</span>`,
    `        <span class="timer__mode">{{ mode() }}</span>`,
    `      </div>`,
    `      <p class="timer__value">`,
    `        @if (mode() === 'countdown') {`,
    `          {{ remaining() }}s remaining`,
    `        } @else {`,
    `          {{ elapsed() }} ticks`,
    `        }`,
    `      </p>`,
    `    </section>`,
    `  \`,`,
    `})`,
    `export class ${className} {`,
    `  id = input<string>();`,
    `  label = input('Timer');`,
    `  mode = input<'interval' | 'countdown'>('interval');`,
    `  intervalMs = input(5000);`,
    `  durationMs = input(30000);`,
    `  autoStart = input(true);`,
    `  value = input(0);`,
    `  valueChange = output<number>();`,
    ``,
    `  elapsed = signal(0);`,
    `  remaining = signal(1);`,
    ``,
    `  constructor() {`,
    `    effect((onCleanup) => {`,
    `      this.elapsed.set(this.value());`,
    `      this.remaining.set(Math.max(1, Math.ceil(this.durationMs() / 1000)));`,
    `      if (!this.autoStart()) {`,
    `        return;`,
    `      }`,
    `      const stepMs = this.mode() === 'countdown' ? 1000 : this.intervalMs();`,
    `      const id = window.setInterval(() => {`,
    `        const next = this.elapsed() + 1;`,
    `        this.elapsed.set(next);`,
    `        this.valueChange.emit(next);`,
    `        if (this.mode() === 'countdown') {`,
    `          this.remaining.update((current) => Math.max(0, current - 1));`,
    `        }`,
    `      }, stepMs);`,
    `      onCleanup(() => window.clearInterval(id));`,
    `    });`,
    `  }`,
    `}`,
    ``,
  ]);
}
