// packages/react/src/infra/server/nest/NestServerInfra.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface NestServerInfraProps {
  label?: string;
  globalPrefix?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/infra/server/nest — infra.server.nest */
export const NestServerInfra = forwardRef<HTMLElement, NestServerInfraProps>(function NestServerInfra(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-server-nest', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-server-nest">
      <span className="rd-infra__badge">INFRA</span>
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      {props.globalPrefix ? <code>globalPrefix: {props.globalPrefix}</code> : null}
      {children}
    </section>
  );
});

// packages/angular/src/infra/server/nest/nest-server-infra.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface NestServerInfraProps {
  label?: string;
  globalPrefix?: string;
  className?: string;
}

/** @rosettadash/angular/infra/server/nest — infra.server.nest */
@Component({
  selector: 'rd-server-nest',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-server-nest'" [ngClass]="rootClass()">
      <span class="rd-infra__badge">INFRA</span>
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      @if (globalPrefix()) { <code>globalPrefix: {{ globalPrefix() }}</code> }
      <ng-content />
    </section>
  `,
})
export class NestServerInfra {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly globalPrefix = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-server-nest', this.className()].filter(Boolean).join(' '),
  );
}
