// packages/react/src/visual/link-list/LinkList.tsx
import type { CSSProperties } from 'react';

/** Single link item for visual/link-list. */
export interface LinkListItem {
  label: string;
  href: string;
}

/** Public props contract for visual/link-list (parity with web-components). */
export interface LinkListProps {
  items?: LinkListItem[];
  className?: string;
  dense?: boolean;
  style?: CSSProperties;
}

export function LinkList({
  items = [],
  className,
  dense = false,
  style,
}: LinkListProps) {
  const rootClass = [
    'rd-link-list',
    dense ? 'rd-link-list--dense' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <ul className={rootClass} style={style} data-testid="rd-link-list">
      {items.map((item) => (
        <li
          className="rd-link-list__item"
          key={`${item.href}:${item.label}`}
        >
          <a className="rd-link-list__link" href={item.href}>
            {item.label}
          </a>
        </li>
      ))}
    </ul>
  );
}

// packages/svelte/src/visual/link-list/LinkList.svelte
<script lang="ts">
	import type { LinkListItem } from './types';

	interface Props {
		items?: LinkListItem[];
		className?: string;
		dense?: boolean;
	}

	let { items = [], className, dense = false }: Props = $props();

	const rootClass = $derived(
		['rd-link-list', dense ? 'rd-link-list--dense' : '', className]
			.filter(Boolean)
			.join(' '),
	);
</script>

<ul class={rootClass} data-testid="rd-link-list">
	{#each items as item (item.href + ':' + item.label)}
		<li class="rd-link-list__item">
			<a class="rd-link-list__link" href={item.href}>{item.label}</a>
		</li>
	{/each}
</ul>
