// packages/react/src/visual/kpi/KpiCard.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface KpiCardProps {
  title?: string;
  value?: string | number;
  delta?: string;
  format?: 'number' | 'currency' | 'percent';
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/kpi — visual.kpi */
export const KpiCard = forwardRef<HTMLElement, KpiCardProps>(function KpiCard(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-kpi', className].filter(Boolean).join(' ');

  return (
    <article ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-kpi">
      <span className="rd-kpi__title">{props.title ?? 'Metric'}</span>
      <span className="rd-kpi__value">{props.value ?? '—'}</span>
      {props.delta ? <span className="rd-kpi__delta">{props.delta}</span> : null}
      {children}
    </article>
  );
});

// packages/svelte/src/visual/kpi/KpiCard.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { KpiCardProps } from './types';

	type Props = KpiCardProps & { children?: Snippet };

	let {
		className,
		title,
		value,
		delta,
		format,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-kpi', className].filter(Boolean).join(' '));
</script>

<article class={rootClass} data-testid="rd-kpi">
	<span class="rd-kpi__title">{title ?? 'Metric'}</span>
	<span class="rd-kpi__value">{value ?? '—'}</span>
	{#if delta}<span class="rd-kpi__delta">{delta}</span>{/if}
	{@render children?.()}
</article>
