// packages/svelte/src/visual/display/3d-gltf-model/ThreeGltfModel.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { ThreeGltfModelProps } from './types';

	type Props = ThreeGltfModelProps & { children?: Snippet };

	let {
		className,
		title,
		mode,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-display-3d-gltf-model', className].filter(Boolean).join(' '));
</script>

<section
	class={rootClass}
	data-testid="rd-display-3d-gltf-model"
	data-three-mode={mode}
	data-three-title={title}
	aria-label={title ?? '3D host'}
>{@render children?.()}</section>

// packages/react/src/visual/display/3d-gltf-model/ThreeGltfModel.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface ThreeGltfModelProps {
  title?: string;
  mode?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/display/3d-gltf-model — visual.display.3d-gltf-model */
export const ThreeGltfModel = forwardRef<HTMLElement, ThreeGltfModelProps>(function ThreeGltfModel(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-display-3d-gltf-model', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-display-3d-gltf-model" data-three-mode={props.mode} data-three-title={props.title} aria-label={props.title ?? '3D host'}>{children}</section>
  );
});
