// packages/exporters-angular/src/lib/generate-angular-ui.ts
import type { ExportIR } from '@dashbuilder/core';
import { buildDashboardContext } from './binding-resolver';
import { generateComponentFile } from './component-templates';
import type { AngularExportOptions, GeneratedFile } from './types';
import { AngularExportError } from './types';
import { componentExportName, joinLines, pascalFromId, serviceClassName } from './utils';

export function generateAngularUiFiles(
  ir: ExportIR,
  options: AngularExportOptions = {},
): GeneratedFile[] {
  if (ir.targets.ui !== 'angular') {
    throw new AngularExportError(`Angular exporter cannot generate UI target "${ir.targets.ui}"`);
  }

  const root = options.rootDir ?? 'src';
  const usedNames = new Set<string>();
  const exportNames = new Map<string, string>();

  for (const component of ir.components) {
    exportNames.set(component.id, componentExportName(component, usedNames));
  }

  for (const source of ir.dataSources) {
    exportNames.set(source.id, pascalFromId(source.id));
  }

  const files: GeneratedFile[] = [];

  for (const component of ir.components) {
    const exportName = exportNames.get(component.id);
    if (!exportName) {
      continue;
    }

    files.push({
      path: `${root}/components/${exportName}.ts`,
      content: generateComponentFile(component, exportName),
      encoding: 'utf-8',
      description: `Angular component for ${component.label}`,
    });
  }

  files.push({
    path: `${root}/types.ts`,
    content: generateTypesFile(),
    encoding: 'utf-8',
    description: 'Shared dashboard types',
  });

  files.push({
    path: `${root}/styles/tokens.scss`,
    content: generateTokensScss(ir),
    encoding: 'utf-8',
    description: 'Neutral style tokens for exported dashboard',
  });

  for (const source of ir.dataSources.filter((entry) => entry.type === 'infra.postgresql')) {
    const serviceName = serviceClassName(source.id, exportNames);
    const route = ir.routes.find((entry) => entry.method === 'GET')?.path ?? '/api/records';
    files.push({
      path: `${root}/services/${serviceName}.ts`,
      content: generateDataService(serviceName, route),
      encoding: 'utf-8',
      description: `Data service for ${source.label}`,
    });
  }

  files.push({
    path: `${root}/dashboard.component.ts`,
    content: generateDashboardFile(ir, exportNames),
    encoding: 'utf-8',
    description: 'Composed dashboard wired from ExportIR bindings',
  });

  files.push({
    path: 'README.export.md',
    content: generateReadme(ir),
    encoding: 'utf-8',
    description: 'Setup notes for exported Angular UI fragment',
  });

  return files;
}

function generateTypesFile(): string {
  return joinLines([
    `export interface DateRange {`,
    `  start: string;`,
    `  end: string;`,
    `}`,
    ``,
    `export type Row = Record<string, string | number | boolean | null | undefined>;`,
    ``,
  ]);
}

function generateTokensScss(ir: ExportIR): string {
  return joinLines([
    `:root {`,
    `  --db-surface: #ffffff;`,
    `  --db-border: #d9dee7;`,
    `  --db-text: #1f2937;`,
    `  --db-accent: #2563eb;`,
    `  --db-muted: #6b7280;`,
    `}`,
    ``,
    `.dashboard {`,
    `  display: grid;`,
    `  gap: 1rem;`,
    `  padding: 1.5rem;`,
    `  color: var(--db-text);`,
    `  background: var(--db-surface);`,
    `}`,
    ``,
    `.field, .input, .select, .table, .kpi-card, .chart-card {`,
    `  border: 1px solid var(--db-border);`,
    `  border-radius: 0.5rem;`,
    `}`,
    ``,
    `.table { width: 100%; border-collapse: collapse; }`,
    `.table th, .table td { padding: 0.5rem 0.75rem; text-align: left; }`,
    `.kpi-card, .chart-card, .table-card { padding: 1rem; }`,
    `.bar-chart { display: flex; align-items: flex-end; gap: 0.25rem; height: 8rem; }`,
    `.bar { flex: 1; background: var(--db-accent); min-height: 0.25rem; }`,
    `/* preset: ${ir.styles.preset} · generated for ${ir.meta.compositeName} */`,
    ``,
  ]);
}

function generateDataService(serviceName: string, route: string): string {
  return joinLines([
    `import { Injectable, signal } from '@angular/core';`,
    `import type { Row } from '../types';`,
    ``,
    `@Injectable({ providedIn: 'root' })`,
    `export class ${serviceName} {`,
    `  readonly data = signal<Row[] | undefined>(undefined);`,
    `  readonly loading = signal(true);`,
    `  readonly error = signal<Error | undefined>(undefined);`,
    ``,
    `  constructor() {`,
    `    void this.load();`,
    `  }`,
    ``,
    `  private async load(): Promise<void> {`,
    `    try {`,
    `      const response = await fetch('${route}');`,
    `      if (!response.ok) {`,
    `        throw new Error(\`Request failed: \${response.status}\`);`,
    `      }`,
    `      const rows = (await response.json()) as Row[];`,
    `      this.data.set(rows);`,
    `    } catch (nextError) {`,
    `      this.error.set(nextError as Error);`,
    `    } finally {`,
    `      this.loading.set(false);`,
    `    }`,
    `  }`,
    `}`,
    ``,
  ]);
}

function generateDashboardFile(ir: ExportIR, exportNames: Map<string, string>): string {
  const context = buildDashboardContext(ir, exportNames);
  const componentImportLines = context.componentImports.map(
    (name) => `import { ${name} } from './components/${name}';`,
  );
  const serviceImportLines = context.serviceImports.map(
    (name) => `import { ${name} } from './services/${name}';`,
  );

  const templateLines = context.components.map((component) => {
    const attrs = component.bindings.map((binding) => `        ${binding}`).join('\n');
    return [`      <${component.selector}`, attrs, `      />`].join('\n');
  });

  return joinLines([
    `import { Component, inject, signal } from '@angular/core';`,
    `import type { DateRange } from './types';`,
    ...componentImportLines,
    ...serviceImportLines,
    ``,
    `@Component({`,
    `  selector: 'app-dashboard',`,
    `  standalone: true,`,
    `  imports: [${context.componentImports.join(', ')}],`,
    `  template: \``,
    `    <main class="dashboard">`,
    `      <header>`,
    `        <h1>${ir.meta.compositeName}</h1>`,
    `      </header>`,
    ...templateLines,
    `    </main>`,
    `  \`,`,
    `  styleUrls: ['./styles/tokens.scss'],`,
    `})`,
    `export class DashboardComponent {`,
    ...context.serviceFields,
    ...context.stateDeclarations,
    `}`,
    ``,
  ]);
}

function generateReadme(ir: ExportIR): string {
  const envLines =
    ir.envVars.length === 0
      ? ['No environment variables required for the UI fragment.']
      : ir.envVars.map((env) => `- \`${env.key}\`${env.required ? ' (required)' : ''}`);

  return joinLines([
    `# ${ir.meta.compositeName} — Angular UI Export`,
    ``,
    `Generated at ${ir.meta.generatedAt} from composite \`${ir.meta.compositeId}\` v${ir.meta.version}.`,
    ``,
    `## Files`,
    ``,
    `- \`src/dashboard.component.ts\` — composed page wired from builder bindings`,
    `- \`src/components/*.ts\` — standalone P0 visual components`,
    `- \`src/services/*.ts\` — data services targeting exported API routes`,
    `- \`src/styles/tokens.scss\` — neutral dashboard styling`,
    ``,
    `## Environment`,
    ``,
    ...envLines,
    ``,
    `## Next steps`,
    ``,
    `1. Copy the generated \`src/\` folder into your Angular app.`,
    `2. Register \`DashboardComponent\` on a route.`,
    `3. Ensure server routes referenced by data services are available.`,
    ``,
  ]);
}

// packages/exporters-react/src/lib/generate-react-ui.ts
import type { ExportIR } from '@dashbuilder/core';
import { buildDashboardContext } from './binding-resolver';
import { generateComponentFile } from './component-templates';
import type { GeneratedFile, ReactExportOptions } from './types';
import { ReactExportError } from './types';
import { componentExportName, joinLines, pascalFromId } from './utils';

export function generateReactUiFiles(
  ir: ExportIR,
  options: ReactExportOptions = {},
): GeneratedFile[] {
  if (ir.targets.ui !== 'react') {
    throw new ReactExportError(`React exporter cannot generate UI target "${ir.targets.ui}"`);
  }

  const root = options.rootDir ?? 'src';
  const usedNames = new Set<string>();
  const exportNames = new Map<string, string>();

  for (const component of ir.components) {
    exportNames.set(component.id, componentExportName(component, usedNames));
  }

  for (const source of ir.dataSources) {
    exportNames.set(source.id, pascalFromId(source.id));
  }

  const files: GeneratedFile[] = [];
  const componentImports: string[] = [];

  for (const component of ir.components) {
    const exportName = exportNames.get(component.id);
    if (!exportName) {
      continue;
    }
    componentImports.push(exportName);
    files.push({
      path: `${root}/components/${exportName}.tsx`,
      content: generateComponentFile(component, exportName),
      encoding: 'utf-8',
      description: `React component for ${component.label}`,
    });
  }

  files.push({
    path: `${root}/types.ts`,
    content: generateTypesFile(),
    encoding: 'utf-8',
    description: 'Shared dashboard types',
  });

  files.push({
    path: `${root}/styles/tokens.css`,
    content: generateTokensCss(ir),
    encoding: 'utf-8',
    description: 'Neutral style tokens for exported dashboard',
  });

  for (const source of ir.dataSources.filter((entry) => entry.type === 'infra.postgresql')) {
    const hookName = `use${exportNames.get(source.id) ?? pascalFromId(source.id)}Data`;
    const route = ir.routes.find((entry) => entry.method === 'GET')?.path ?? '/api/records';
    files.push({
      path: `${root}/hooks/${hookName}.ts`,
      content: generateDataHook(hookName, route),
      encoding: 'utf-8',
      description: `Data hook for ${source.label}`,
    });
  }

  files.push({
    path: `${root}/Dashboard.tsx`,
    content: generateDashboardFile(ir, exportNames, componentImports),
    encoding: 'utf-8',
    description: 'Composed dashboard page wired from ExportIR bindings',
  });

  files.push({
    path: 'README.export.md',
    content: generateReadme(ir),
    encoding: 'utf-8',
    description: 'Setup notes for exported React UI fragment',
  });

  return files;
}

function generateTypesFile(): string {
  return joinLines([
    `export interface DateRange {`,
    `  start: string;`,
    `  end: string;`,
    `}`,
    ``,
    `export type Row = Record<string, string | number | boolean | null | undefined>;`,
    ``,
  ]);
}

function generateTokensCss(ir: ExportIR): string {
  return joinLines([
    `:root {`,
    `  --db-surface: #ffffff;`,
    `  --db-border: #d9dee7;`,
    `  --db-text: #1f2937;`,
    `  --db-accent: #2563eb;`,
    `  --db-muted: #6b7280;`,
    `}`,
    ``,
    `.dashboard {`,
    `  display: grid;`,
    `  gap: 1rem;`,
    `  padding: 1.5rem;`,
    `  color: var(--db-text);`,
    `  background: var(--db-surface);`,
    `}`,
    ``,
    `.field, .input, .select, .table, .kpi-card, .chart-card {`,
    `  border: 1px solid var(--db-border);`,
    `  border-radius: 0.5rem;`,
    `}`,
    ``,
    `.table { width: 100%; border-collapse: collapse; }`,
    `.table th, .table td { padding: 0.5rem 0.75rem; text-align: left; }`,
    `.kpi-card, .chart-card, .table-card { padding: 1rem; }`,
    `.bar-chart { display: flex; align-items: flex-end; gap: 0.25rem; height: 8rem; }`,
    `.bar { flex: 1; background: var(--db-accent); min-height: 0.25rem; }`,
    `/* preset: ${ir.styles.preset} · generated for ${ir.meta.compositeName} */`,
    ``,
  ]);
}

function generateDataHook(hookName: string, route: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import { useEffect, useState } from 'react';`,
    `import type { Row } from '../types';`,
    ``,
    `export function ${hookName}() {`,
    `  const [data, setData] = useState<Row[] | undefined>();`,
    `  const [loading, setLoading] = useState(true);`,
    `  const [error, setError] = useState<Error | undefined>();`,
    ``,
    `  useEffect(() => {`,
    `    let cancelled = false;`,
    ``,
    `    fetch('${route}')`,
    `      .then(async (response) => {`,
    `        if (!response.ok) {`,
    `          throw new Error(\`Request failed: \${response.status}\`);`,
    `        }`,
    `        return response.json() as Promise<Row[]>;`,
    `      })`,
    `      .then((rows) => {`,
    `        if (!cancelled) {`,
    `          setData(rows);`,
    `        }`,
    `      })`,
    `      .catch((nextError: Error) => {`,
    `        if (!cancelled) {`,
    `          setError(nextError);`,
    `        }`,
    `      })`,
    `      .finally(() => {`,
    `        if (!cancelled) {`,
    `          setLoading(false);`,
    `        }`,
    `      });`,
    ``,
    `    return () => {`,
    `      cancelled = true;`,
    `    };`,
    `  }, []);`,
    ``,
    `  return { data, loading, error };`,
    `}`,
    ``,
  ]);
}

function generateDashboardFile(
  ir: ExportIR,
  exportNames: Map<string, string>,
  componentImports: string[],
): string {
  const context = buildDashboardContext(ir, exportNames);
  const hookImportLines = context.hookImports.map(
    (hook) => `import { ${hook} } from './hooks/${hook}';`,
  );
  const componentImportLines = componentImports.map(
    (name) => `import { ${name} } from './components/${name}';`,
  );

  const renderLines = context.components.map((component) => {
    const propLines = Object.entries(component.props).map(([key, value]) => `        ${key}={${value}}`);
    return [`      <${component.exportName}`, ...propLines, `      />`].join('\n');
  });

  return joinLines([
    `'use client';`,
    ``,
    `import { useState } from 'react';`,
    `import './styles/tokens.css';`,
    `import type { DateRange } from './types';`,
    ...componentImportLines,
    ...hookImportLines,
    ``,
    `export default function Dashboard() {`,
    ...context.stateDeclarations,
    ...context.hookCalls,
    ``,
    `  return (`,
    `    <main className="dashboard">`,
    `      <header>`,
    `        <h1>${ir.meta.compositeName}</h1>`,
    `      </header>`,
    ...renderLines,
    `    </main>`,
    `  );`,
    `}`,
    ``,
  ]);
}

function generateReadme(ir: ExportIR): string {
  const envLines =
    ir.envVars.length === 0
      ? ['No environment variables required for the UI fragment.']
      : ir.envVars.map((env) => `- \`${env.key}\`${env.required ? ' (required)' : ''}`);

  return joinLines([
    `# ${ir.meta.compositeName} — React UI Export`,
    ``,
    `Generated at ${ir.meta.generatedAt} from composite \`${ir.meta.compositeId}\` v${ir.meta.version}.`,
    ``,
    `## Files`,
    ``,
    `- \`src/Dashboard.tsx\` — composed page wired from builder bindings`,
    `- \`src/components/*.tsx\` — P0 visual components`,
    `- \`src/hooks/*.ts\` — data hooks targeting exported API routes`,
    `- \`src/styles/tokens.css\` — neutral dashboard styling`,
    ``,
    `## Environment`,
    ``,
    ...envLines,
    ``,
    `## Next steps`,
    ``,
    `1. Copy the generated \`src/\` folder into your React or Next.js app.`,
    `2. Mount \`Dashboard\` on a route.`,
    `3. Ensure server routes referenced by data hooks are available.`,
    ``,
  ]);
}
