// apps/proof-react/src/screens/DestinationsScreen.tsx
import { TimePreset } from '@rosettadash/react/domain/time-preset';
import { RoleGate } from '@rosettadash/react/domain/role-gate';
import { FilterGrid } from '@rosettadash/react/layout/filter-grid';
import { FlexLayout } from '@rosettadash/react/layout/flex';
import { DateRangeFilter } from '@rosettadash/react/visual/input/date-range';
import { SelectInput } from '@rosettadash/react/visual/input/select';
import { TextInput } from '@rosettadash/react/visual/input/text';
import { DetailPanel, DetailHistoricList, DetailStats } from '@rosettadash/react/visual/detail';
import { FilterSummary } from '@rosettadash/react/visual/filter/filter-summary';
import { DataTable, type DataTableRow } from '@rosettadash/react/visual/table';
import { MOCK_DESTINATIONS, formatVisitorCount, getDestinationById } from '@destination-atlas';
import type { AtlasContext } from '../state/useDestinationAtlasState';
import {
  filterHistoricByPreset,
  formatRegionLabel,
  formatVisitPeriod,
  historicWindowLabel,
  localizedDestinationName,
  periodColumnLabel,
} from '../lib/atlas-utils';

const REGION_OPTIONS = [
  { value: 'asia-pacific', label: 'Asia Pacific' },
  { value: 'europe', label: 'Europe' },
  { value: 'americas', label: 'Americas' },
  { value: 'africa', label: 'Africa' },
];

type Props = Pick<
  AtlasContext,
  | 'locale'
  | 'userRole'
  | 'selectedId'
  | 'setSelectedId'
  | 'destSearch'
  | 'setDestSearch'
  | 'destRegion'
  | 'setDestRegion'
  | 'timePreset'
  | 'setTimePreset'
  | 'visitPeriodStart'
  | 'visitPeriodEnd'
  | 'setVisitPeriod'
  | 'focusDestinationOnMap'
>;

export const DESTINATIONS_SOURCE = `<DestinationsScreen …>
  <FilterGrid>
    <FilterGrid.Stack>
      <TextInput label="Search" value={destSearch} />
      <SelectInput label="Region" value={destRegion} />
    </FilterGrid.Stack>
    <FilterGrid.Period>
      <DateRangeFilter granularity="month" startDate={visitPeriodStart} endDate={visitPeriodEnd} />
    </FilterGrid.Period>
    <FilterGrid.Full>
      <TimePreset activePresetId={timePreset} onPresetChange={setTimePreset} />
    </FilterGrid.Full>
  </FilterGrid>
  <FilterSummary count={filtered.length} chips={…} hint={…} />
  <FlexLayout itemFlex={[1.4, 1]} stretchItems>
    <DataTable rows={rows} selectedRowId={selectedId} />
    <DetailPanel>
      <DetailStats items={…} compact />
      <DetailHistoricList title={…} items={…} compact />
    </DetailPanel>
  </FlexLayout>
</DestinationsScreen>`;

export function DestinationsScreen({
  locale,
  userRole,
  selectedId,
  setSelectedId,
  destSearch,
  setDestSearch,
  destRegion,
  setDestRegion,
  timePreset,
  setTimePreset,
  visitPeriodStart,
  visitPeriodEnd,
  setVisitPeriod,
  focusDestinationOnMap,
}: Props) {
  const filtered = MOCK_DESTINATIONS.filter((dest) => {
    const name = localizedDestinationName(dest, locale).toLowerCase();
    const matchesSearch = !destSearch || name.includes(destSearch.toLowerCase());
    const matchesRegion = !destRegion || dest.region === destRegion;
    return matchesSearch && matchesRegion;
  });

  const periodLabel = periodColumnLabel(timePreset);
  const rows: DataTableRow[] = filtered.map((dest) => ({
    id: dest.id,
    name: localizedDestinationName(dest, locale),
    status: dest.region,
    amount: dest.visitorsCurrent,
    date: periodLabel,
  }));

  const selected = getDestinationById(selectedId);
  const selectedHistoric = selected ? filterHistoricByPreset(selected, timePreset) : [];
  const filtersActive =
    Boolean(destSearch) ||
    Boolean(destRegion) ||
    timePreset !== '5y' ||
    visitPeriodStart !== '2019-01' ||
    visitPeriodEnd !== '2024-12';

  const filterChips = [
    ...(destSearch ? [{ label: 'Search', value: destSearch }] : []),
    ...(destRegion ? [{ label: 'Region', value: formatRegionLabel(destRegion) }] : []),
    { label: 'Visit period', value: formatVisitPeriod(visitPeriodStart, visitPeriodEnd) },
    { label: 'Historic window', value: historicWindowLabel(timePreset) },
  ];

  const filterHint = filtersActive
    ? `Showing ${filtered.length} match${filtered.length === 1 ? '' : 'es'}. Historic window controls which years appear in the table Period column and detail panel (${periodLabel}).`
    : `Historic window is set to ${historicWindowLabel(timePreset)} — detail panels show visitor totals for ${periodLabel}.`;

  return (
    <section className="da-panel">
      <h2>Destinations</h2>
      <p>Browse and filter mock destination records.</p>
      <div className="da-stack">
        <RoleGate
          label="Destination filters"
          currentRole={userRole}
          allowedRoles={['editor', 'admin']}
          statusText="Editor filters active"
          hiddenStatusText="Filters are available to Editor and Admin roles. Viewer sees the full list."
        >
          <FilterGrid>
            <FilterGrid.Stack>
              <TextInput
                label="Search"
                placeholder="Destination name…"
                value={destSearch}
                onChange={setDestSearch}
              />
              <SelectInput
                label="Region"
                placeholder="All regions"
                options={REGION_OPTIONS}
                value={destRegion}
                onChange={setDestRegion}
              />
            </FilterGrid.Stack>
            <FilterGrid.Period>
              <DateRangeFilter
                label="Visit period"
                granularity="month"
                startDate={visitPeriodStart}
                endDate={visitPeriodEnd}
                onChange={setVisitPeriod}
              />
            </FilterGrid.Period>
            <FilterGrid.Full>
              <TimePreset
                label="Historic window"
                presets={[
                  { id: '1y', label: '1Y' },
                  { id: '5y', label: '5Y' },
                  { id: 'all', label: 'All' },
                ]}
                activePresetId={timePreset}
                onPresetChange={setTimePreset}
              />
            </FilterGrid.Full>
          </FilterGrid>
        </RoleGate>

        <FilterSummary
          count={filtered.length}
          countNoun="destination"
          chips={filterChips}
          hint={filterHint}
        />

        <FlexLayout direction="row" gap={16} title="Browse destinations" itemFlex={[1.4, 1]} stretchItems>
          <DataTable
            title="Destinations"
            rows={rows}
            selectedRowId={selectedId}
            onRowSelect={userRole === 'viewer' ? undefined : setSelectedId}
            columns={[
              { key: 'name', header: 'Destination' },
              {
                key: 'status',
                header: 'Region',
                format: (value) => formatRegionLabel(String(value ?? '')),
              },
              {
                key: 'amount',
                header: '2024 visitors',
                align: 'right',
                width: '7.5rem',
                format: (value) => formatVisitorCount(Number(value ?? 0)),
              },
              { key: 'date', header: 'Period', align: 'right', width: '9rem' },
            ]}
          />
          <DetailPanel title="Destination detail">
            {userRole === 'viewer' ? (
              <p className="da-detail-body">
                Switch to Editor or Admin to select rows and view destination details.
              </p>
            ) : selected ? (
              <div>
                <p className="rd-detail-card__title">
                  {localizedDestinationName(selected, locale)}
                </p>
                <p className="rd-detail-card__meta">{formatRegionLabel(selected.region)}</p>
                <DetailStats
                  compact
                  items={[
                    {
                      label: 'Current visitors',
                      value: `${formatVisitorCount(selected.visitorsCurrent)} (2024)`,
                    },
                    {
                      label: 'Coordinates',
                      value: `${selected.lat.toFixed(4)}, ${selected.lng.toFixed(4)}`,
                    },
                  ]}
                />
                <DetailHistoricList
                  compact
                  title={`Historic visitors (${historicWindowLabel(timePreset)})`}
                  items={selectedHistoric.map((row) => ({
                    label: String(row.year),
                    value: formatVisitorCount(row.visitors),
                  }))}
                />
                <p className="da-detail-actions">
                  <button
                    type="button"
                    className="rd-button"
                    onClick={() => focusDestinationOnMap(selected.id)}
                  >
                    View on map
                  </button>
                </p>
              </div>
            ) : (
              <p className="da-detail-body">Select a destination row to view details.</p>
            )}
          </DetailPanel>
        </FlexLayout>
      </div>
    </section>
  );
}

// apps/proof-vue/src/screens/DestinationsScreen.vue
<script lang="ts">
export const DESTINATIONS_SOURCE = `<DestinationsScreen …>
  <FilterGrid>…</FilterGrid>
  <DataTable rows={rows} />
  <DetailPanel>…</DetailPanel>
</DestinationsScreen>`;
</script>

<script setup lang="ts">
import { computed } from 'vue';
import { TimePreset } from '@rosettadash/vue/domain/time-preset';
import { FlexLayout } from '@rosettadash/vue/layout/flex';
import { DateRangeFilter } from '@rosettadash/vue/visual/input/date-range';
import { DetailPanel } from '@rosettadash/vue/visual/detail';
import { DataTable } from '@rosettadash/vue/visual/table';
import type { DataTableRow } from '@rosettadash/vue/visual/table/data-table';
import { MOCK_DESTINATIONS, formatVisitorCount, getDestinationById } from '@destination-atlas';
import BoundSelectInput from '../components/BoundSelectInput.vue';
import BoundTextInput from '../components/BoundTextInput.vue';
import FilterSummary from '../components/FilterSummary.vue';
import RoleGatePanel from '../components/RoleGatePanel.vue';
import type { AtlasUserRole } from '../lib/roles';
import {
  filterHistoricByPreset,
  formatRegionLabel,
  formatVisitPeriod,
  historicWindowLabel,
  localizedDestinationName,
  periodColumnLabel,
} from '../lib/atlas-utils';

const props = defineProps<{
  locale: string;
  userRole: AtlasUserRole;
  selectedId: string;
  destSearch: string;
  destRegion: string;
  timePreset: string;
  visitPeriodStart: string;
  visitPeriodEnd: string;
}>();

const emit = defineEmits<{
  'update:selectedId': [string];
  'update:destSearch': [string];
  'update:destRegion': [string];
  'update:timePreset': [string];
  'update:visitPeriod': [{ startDate: string; endDate: string }];
  focusDestinationOnMap: [string];
}>();

const REGION_OPTIONS = [
  { value: 'asia-pacific', label: 'Asia Pacific' },
  { value: 'europe', label: 'Europe' },
  { value: 'americas', label: 'Americas' },
  { value: 'africa', label: 'Africa' },
];

const filtered = computed(() =>
  MOCK_DESTINATIONS.filter((dest) => {
    const name = localizedDestinationName(dest, props.locale).toLowerCase();
    const matchesSearch = !props.destSearch || name.includes(props.destSearch.toLowerCase());
    const matchesRegion = !props.destRegion || dest.region === props.destRegion;
    return matchesSearch && matchesRegion;
  }),
);

const periodLabel = computed(() => periodColumnLabel(props.timePreset));

const rows = computed<DataTableRow[]>(() =>
  filtered.value.map((dest) => ({
    id: dest.id,
    name: localizedDestinationName(dest, props.locale),
    status: dest.region,
    amount: dest.visitorsCurrent,
    date: periodLabel.value,
  })),
);

const selected = computed(() => getDestinationById(props.selectedId));
const selectedHistoric = computed(() =>
  selected.value ? filterHistoricByPreset(selected.value, props.timePreset) : [],
);

const filterChips = computed(() => [
  ...(props.destSearch ? [{ label: 'Search', value: props.destSearch }] : []),
  ...(props.destRegion ? [{ label: 'Region', value: formatRegionLabel(props.destRegion) }] : []),
  { label: 'Visit period', value: formatVisitPeriod(props.visitPeriodStart, props.visitPeriodEnd) },
  { label: 'Historic window', value: historicWindowLabel(props.timePreset) },
]);
</script>

<template>
  <section class="da-panel">
    <h2>Destinations</h2>
    <p>Browse and filter mock destination records.</p>
    <div class="da-stack">
      <RoleGatePanel
        gate-label="Destination filters"
        :current-role="userRole"
        :allowed-roles="['editor', 'admin']"
        status-text="Editor filters active"
        hidden-status-text="Filters are available to Editor and Admin roles. Viewer sees the full list."
      >
        <div class="da-stack da-stack--2">
          <div class="rd-filter-grid">
            <BoundTextInput
              field-label="Search"
              placeholder="Destination name…"
              :value="destSearch"
              @update:value="emit('update:destSearch', $event)"
            />
            <BoundSelectInput
              field-label="Region"
              placeholder="All regions"
              :options="REGION_OPTIONS"
              :value="destRegion"
              @update:value="emit('update:destRegion', $event)"
            />
            <DateRangeFilter
              label="Visit period"
              granularity="month"
              :start-date="visitPeriodStart"
              :end-date="visitPeriodEnd"
              @change="emit('update:visitPeriod', $event)"
            />
            <TimePreset
              label="Historic window"
              :presets="[
                { id: '1y', label: '1Y' },
                { id: '5y', label: '5Y' },
                { id: 'all', label: 'All' },
              ]"
              :active-preset-id="timePreset"
              @preset-change="emit('update:timePreset', $event)"
            />
          </div>
        </div>
      </RoleGatePanel>

      <FilterSummary
        :count="filtered.length"
        count-noun="destination"
        :chips="filterChips"
        :hint="`Historic window: ${historicWindowLabel(timePreset)} (${periodLabel}).`"
      />

      <FlexLayout direction="row" :gap="16" title="Browse destinations">
        <DataTable title="Destinations" :rows="rows" />
        <DetailPanel title="Destination detail">
          <p v-if="userRole === 'viewer'" class="da-detail-body">
            Switch to Editor or Admin to select rows and view destination details.
          </p>
          <div v-else-if="selected">
            <p class="rd-detail-card__title">{{ localizedDestinationName(selected, locale) }}</p>
            <p class="rd-detail-card__meta">{{ formatRegionLabel(selected.region) }}</p>
            <dl class="rd-detail-stats rd-detail-stats--compact">
              <div>
                <dt>Current visitors</dt>
                <dd>{{ formatVisitorCount(selected.visitorsCurrent) }} (2024)</dd>
              </div>
              <div>
                <dt>Coordinates</dt>
                <dd>{{ selected.lat.toFixed(4) }}, {{ selected.lng.toFixed(4) }}</dd>
              </div>
            </dl>
            <section class="rd-detail-historic rd-detail-historic--compact">
              <h4>Historic visitors ({{ historicWindowLabel(timePreset) }})</h4>
              <ul>
                <li v-for="row in selectedHistoric" :key="row.year">
                  <span>{{ row.year }}</span>
                  <strong>{{ formatVisitorCount(row.visitors) }}</strong>
                </li>
              </ul>
            </section>
            <p class="da-detail-actions">
              <button type="button" class="rd-button" @click="emit('focusDestinationOnMap', selected.id)">
                View on map
              </button>
            </p>
          </div>
          <p v-else class="da-detail-body">Select a destination row to view details.</p>
        </DetailPanel>
      </FlexLayout>
    </div>
  </section>
</template>
