// packages/svelte/src/visual/news/language-select/NewsLanguageSelect.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { NewsLanguageSelectProps } from './types';

	type Props = NewsLanguageSelectProps & { children?: Snippet };

	let {
		className,
		label,
		placeholder,
		options,
		value,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-news-language-select', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-news-language-select">
	{#if label}<span class="rd-field__label">{label}</span>{/if}
	<select class="rd-select" value={value ?? ''}>
		<option value="">{placeholder ?? 'Select…'}</option>
		{#each options ?? [] as o (o.value)}<option value={o.value}>{o.label}</option>{/each}
	</select>
	{@render children?.()}
</section>

// packages/react/src/visual/news/language-select/NewsLanguageSelect.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface NewsLanguageSelectProps {
  label?: string;
  placeholder?: string;
  options?: { value: string; label: string }[];
  value?: string;
  onChange?: (value: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/news/language-select — visual.news.language-select */
export const NewsLanguageSelect = forwardRef<HTMLElement, NewsLanguageSelectProps>(function NewsLanguageSelect(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-news-language-select', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-news-language-select">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <select className="rd-select" value={props.value} onChange={(e) => props.onChange?.(e.target.value)}>
        <option value="">{props.placeholder ?? 'Select…'}</option>
        {(props.options ?? []).map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
      </select>
      {children}
    </section>
  );
});
