// apps/proof-vue/src/screens/MapsScreen.vue
<script lang="ts">
export const MAPS_SOURCE = `<MapsScreen mapsPanel={mapsPanel}>
  <MapScreen part="toolbar" />
  <MapsPanelNav panel={mapsPanel} />
  <MapScreen v-if="map" /> | <GlobeScreen v-else />
</MapsScreen>`;
</script>

<script setup lang="ts">
import { ref } from 'vue';
import type { GeoMapProvider } from '@destination-atlas';
import MapsPanelNav from '../components/MapsPanelNav.vue';
import BoundSelectInput from '../components/BoundSelectInput.vue';
import MapScreen from './MapScreen.vue';
import GlobeScreen from './GlobeScreen.vue';
import type { GeoExplorerListPlacement } from '../components/GeoExplorerLayout.vue';

defineProps<{
  locale: string;
  selectedId: string;
  mapProvider: GeoMapProvider;
  mapLocationQuery: string;
  mapViewOverride: { lat: number; lng: number; zoom: number; label: string } | null;
  mapsPanel: 'map' | 'globe';
}>();

const emit = defineEmits<{
  'update:selectedId': [string];
  'update:mapProvider': [GeoMapProvider];
  'update:mapLocationQuery': [string];
  'update:mapsPanel': ['map' | 'globe'];
  focusDestinationOnMap: [string];
  goToMapView: [{ lat: number; lng: number; zoom: number; label: string }];
  openSettings: [];
}>();

const listPlacement = ref<GeoExplorerListPlacement>('right');
</script>

<template>
  <section class="da-panel da-maps-panel" :class="`da-maps-panel--${mapsPanel}`">
    <div class="da-maps-panel__body">
      <div class="da-maps-toolbar">
        <MapScreen
          part="toolbar"
          embedded
          :locale="locale"
          :selected-id="selectedId"
          :map-provider="mapProvider"
          :map-location-query="mapLocationQuery"
          :map-view-override="mapViewOverride"
          @update:selected-id="emit('update:selectedId', $event)"
          @update:map-provider="emit('update:mapProvider', $event)"
          @update:map-location-query="emit('update:mapLocationQuery', $event)"
          @focus-destination-on-map="emit('focusDestinationOnMap', $event)"
          @go-to-map-view="emit('goToMapView', $event)"
          @open-settings="emit('openSettings')"
        />
        <BoundSelectInput
          field-label="Destination list placement"
          :options="[
            { value: 'right', label: 'List on right' },
            { value: 'left', label: 'List on left' },
          ]"
          :value="listPlacement"
          @update:value="listPlacement = $event as GeoExplorerListPlacement"
        />
      </div>

      <MapsPanelNav :panel="mapsPanel" @select-panel="emit('update:mapsPanel', $event)" />

      <div class="da-maps-explorer">
        <MapScreen
          v-if="mapsPanel === 'map'"
          part="explorer"
          embedded
          :list-placement="listPlacement"
          :locale="locale"
          :selected-id="selectedId"
          :map-provider="mapProvider"
          :map-location-query="mapLocationQuery"
          :map-view-override="mapViewOverride"
          @update:selected-id="emit('update:selectedId', $event)"
          @update:map-provider="emit('update:mapProvider', $event)"
          @update:map-location-query="emit('update:mapLocationQuery', $event)"
          @focus-destination-on-map="emit('focusDestinationOnMap', $event)"
          @go-to-map-view="emit('goToMapView', $event)"
          @open-settings="emit('openSettings')"
        />
        <GlobeScreen
          v-else
          part="explorer"
          embedded
          :list-placement="listPlacement"
          :locale="locale"
          :selected-id="selectedId"
          @update:selected-id="emit('update:selectedId', $event)"
          @focus-destination-on-map="emit('focusDestinationOnMap', $event)"
        />
      </div>

      <GlobeScreen
        v-if="mapsPanel === 'globe'"
        part="footer"
        embedded
        :locale="locale"
        :selected-id="selectedId"
        @update:selected-id="emit('update:selectedId', $event)"
        @focus-destination-on-map="emit('focusDestinationOnMap', $event)"
      />
    </div>
  </section>
</template>

// apps/proof-svelte/src/screens/MapsScreen.svelte
<script module lang="ts">
  export const MAPS_SOURCE = `<MapsScreen mapsPanel={mapsPanel}>
  <MapScreen part="toolbar" />
  <MapsPanelNav panel={mapsPanel} />
  <MapScreen v-if="map" /> | <GlobeScreen v-else />
</MapsScreen>`;
</script>

<script lang="ts">
  import type { GeoMapProvider } from '@destination-atlas';
  import MapsPanelNav from '../components/MapsPanelNav.svelte';
  import BoundSelectInput from '../components/BoundSelectInput.svelte';
  import MapScreen from './MapScreen.svelte';
  import GlobeScreen from './GlobeScreen.svelte';
  import type { GeoExplorerListPlacement } from '../components/GeoExplorerLayout.svelte';

  let {
    locale,
    selectedId,
    mapProvider,
    mapLocationQuery,
    mapViewOverride,
    mapsPanel,
    onSelectedIdChange,
    onMapProviderChange,
    onMapLocationQueryChange,
    onMapsPanelChange,
    onFocusDestinationOnMap,
    onGoToMapView,
    onOpenSettings,
  }: {
    locale: string;
    selectedId: string;
    mapProvider: GeoMapProvider;
    mapLocationQuery: string;
    mapViewOverride: { lat: number; lng: number; zoom: number; label: string } | null;
    mapsPanel: 'map' | 'globe';
    onSelectedIdChange?: (id: string) => void;
    onMapProviderChange?: (provider: GeoMapProvider) => void;
    onMapLocationQueryChange?: (query: string) => void;
    onMapsPanelChange?: (panel: 'map' | 'globe') => void;
    onFocusDestinationOnMap?: (id: string) => void;
    onGoToMapView?: (view: { lat: number; lng: number; zoom: number; label: string }) => void;
    onOpenSettings?: () => void;
  } = $props();

  let listPlacement = $state<GeoExplorerListPlacement>('right');
</script>

<section class="da-panel da-maps-panel da-maps-panel--{mapsPanel}">
  <div class="da-maps-panel__body">
    <div class="da-maps-toolbar">
      <MapScreen
        part="toolbar"
        embedded
        {locale}
        {selectedId}
        {mapProvider}
        {mapLocationQuery}
        {mapViewOverride}
        onSelectedIdChange={onSelectedIdChange}
        onMapProviderChange={onMapProviderChange}
        onMapLocationQueryChange={onMapLocationQueryChange}
        {onFocusDestinationOnMap}
        {onGoToMapView}
        {onOpenSettings}
      />
      <BoundSelectInput
        fieldLabel="Destination list placement"
        options={[
          { value: 'right', label: 'List on right' },
          { value: 'left', label: 'List on left' },
        ]}
        value={listPlacement}
        onValueChange={(value) => (listPlacement = value as GeoExplorerListPlacement)}
      />
    </div>

    <MapsPanelNav panel={mapsPanel} onSelectPanel={onMapsPanelChange} />

    <div class="da-maps-explorer">
      {#if mapsPanel === 'map'}
        <MapScreen
          part="explorer"
          embedded
          {listPlacement}
          {locale}
          {selectedId}
          {mapProvider}
          {mapLocationQuery}
          {mapViewOverride}
          onSelectedIdChange={onSelectedIdChange}
          onMapProviderChange={onMapProviderChange}
          onMapLocationQueryChange={onMapLocationQueryChange}
          {onFocusDestinationOnMap}
          {onGoToMapView}
          {onOpenSettings}
        />
      {:else}
        <GlobeScreen
          part="explorer"
          embedded
          {listPlacement}
          {locale}
          {selectedId}
          onSelectedIdChange={onSelectedIdChange}
          {onFocusDestinationOnMap}
        />
      {/if}
    </div>

    {#if mapsPanel === 'globe'}
      <GlobeScreen
        part="footer"
        embedded
        {locale}
        {selectedId}
        onSelectedIdChange={onSelectedIdChange}
        {onFocusDestinationOnMap}
      />
    {/if}
  </div>
</section>
