// apps/proof-vue/src/screens/OverviewScreen.vue
<script lang="ts">
export const OVERVIEW_SOURCE = `<OverviewScreen locale={locale} userRole={userRole}>
  <GridLayout columns={3} gap={12} title="Destination KPIs">
    {MOCK_DESTINATIONS.map((dest) => (
      <KpiCard title={...} value={...} delta={...} />
    ))}
  </GridLayout>
  <LineChart points={aggregateVisitorTrend()} xAxisLabel="Year" yAxisLabel="Total visitors" />
  <BarChart bars={destinationBarSeries(locale)} yAxisLabel="Visitors" />
  <RoleGate currentRole={userRole} allowedRoles={['admin']} label="Operations metrics">
    <MetricChip chipLabel="Avg. stay" chipValue="4.2 nights" />
    <StatusBadge statusText="Data freshness: current" tone="success" />
  </RoleGate>
</OverviewScreen>`;
</script>

<script setup lang="ts">
import { BarChart } from '@rosettadash/vue/visual/chart/bar';
import { LineChart } from '@rosettadash/vue/visual/chart/line';
import { GridLayout } from '@rosettadash/vue/layout/grid';
import RoleGatePanel from '../components/RoleGatePanel.vue';
import { KpiCard } from '@rosettadash/vue/visual/kpi';
import { MetricChip } from '@rosettadash/vue/visual/plugin/metric-chip';
import { StatusBadge } from '@rosettadash/vue/visual/plugin/status-badge';
import { MOCK_DESTINATIONS, formatVisitorCount } from '@destination-atlas';
import type { AtlasUserRole } from '../lib/roles';
import { computeVisitorDelta, localizedDestinationName } from '../lib/atlas-utils';

defineProps<{ locale: string; userRole: AtlasUserRole }>();
</script>

<template>
  <section class="da-panel">
    <h2>Overview</h2>
    <p>Current visitor KPIs and historic trends across sample destinations.</p>
    <div class="da-stack">
      <GridLayout :columns="3" :gap="12" title="Destination KPIs">
        <KpiCard
          v-for="dest in MOCK_DESTINATIONS"
          :key="dest.id"
          :title="localizedDestinationName(dest, locale)"
          :value="formatVisitorCount(dest.visitorsCurrent)"
          :delta="computeVisitorDelta(dest)"
          format="number"
        />
      </GridLayout>
      <div class="da-stack da-stack--2">
        <LineChart title="Visitors over time (aggregate trend)" />
        <BarChart title="2024 visitors by destination" />
      </div>
      <RoleGatePanel
        gate-label="Operations metrics"
        :current-role="userRole"
        :allowed-roles="['admin']"
        status-text="Admin operations panel"
        hidden-status-text="Operations metrics are hidden for Viewer and Editor roles."
      >
        <div class="da-stack da-stack--2 da-stack--metrics">
          <MetricChip chip-label="Avg. stay" chip-value="4.2 nights" />
          <StatusBadge status-text="Data freshness: current" tone="success" />
        </div>
      </RoleGatePanel>
    </div>
  </section>
</template>

// apps/proof-svelte/src/screens/OverviewScreen.svelte
<script module lang="ts">
  export const OVERVIEW_SOURCE = `<OverviewScreen locale={locale} userRole={userRole}>
  <GridLayout columns={3} gap={12} title="Destination KPIs">
    {MOCK_DESTINATIONS.map((dest) => (
      <KpiCard title={...} value={...} delta={...} />
    ))}
  </GridLayout>
  <LineChart points={aggregateVisitorTrend()} xAxisLabel="Year" yAxisLabel="Total visitors" />
  <BarChart bars={destinationBarSeries(locale)} yAxisLabel="Visitors" />
  <RoleGate currentRole={userRole} allowedRoles={['admin']} label="Operations metrics">
    <MetricChip chipLabel="Avg. stay" chipValue="4.2 nights" />
    <StatusBadge statusText="Data freshness: current" tone="success" />
  </RoleGate>
</OverviewScreen>`;
</script>

<script lang="ts">
  import BarChart from '@rosettadash/svelte/visual/chart/bar';
  import LineChart from '@rosettadash/svelte/visual/chart/line';
  import GridLayout from '@rosettadash/svelte/layout/grid';
  import KpiCard from '@rosettadash/svelte/visual/kpi';
  import MetricChip from '@rosettadash/svelte/visual/plugin/metric-chip';
  import StatusBadge from '@rosettadash/svelte/visual/plugin/status-badge';
  import RoleGatePanel from '../components/RoleGatePanel.svelte';
  import { MOCK_DESTINATIONS, formatVisitorCount } from '@destination-atlas';
  import type { AtlasUserRole } from '../lib/roles';
  import { computeVisitorDelta, localizedDestinationName } from '../lib/atlas-utils';

  let { locale, userRole }: { locale: string; userRole: AtlasUserRole } = $props();
</script>

<section class="da-panel">
  <h2>Overview</h2>
  <p>Current visitor KPIs and historic trends across sample destinations.</p>
  <div class="da-stack">
    <GridLayout columns={3} gap={12} title="Destination KPIs">
      {#each MOCK_DESTINATIONS as dest (dest.id)}
        <KpiCard
          title={localizedDestinationName(dest, locale)}
          value={formatVisitorCount(dest.visitorsCurrent)}
          delta={computeVisitorDelta(dest)}
          format="number"
        />
      {/each}
    </GridLayout>
    <div class="da-stack da-stack--2">
      <LineChart title="Visitors over time (aggregate trend)" />
      <BarChart title="2024 visitors by destination" />
    </div>
    <RoleGatePanel
      gateLabel="Operations metrics"
      currentRole={userRole}
      allowedRoles={['admin']}
      statusText="Admin operations panel"
      hiddenStatusText="Operations metrics are hidden for Viewer and Editor roles."
    >
      <div class="da-stack da-stack--2 da-stack--metrics">
        <MetricChip chipLabel="Avg. stay" chipValue="4.2 nights" />
        <StatusBadge statusText="Data freshness: current" tone="success" />
      </div>
    </RoleGatePanel>
  </div>
</section>
