// apps/proof-vue/src/screens/SettingsScreen.vue
<script lang="ts">
export const SETTINGS_SOURCE = `<SettingsScreen>
  <header><h2>Settings</h2><ThemeToggle /></header>
  <AtlasContextControls highlightField={…} />
  <Collapsible title="Integration keys (BYOK)">…</Collapsible>
  <Collapsible title="Scout / AI providers (BYOK)">…</Collapsible>
  <TextareaInput label="Feedback" />
</SettingsScreen>`;
</script>

<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import type { GeoMapProvider } from '@destination-atlas';
import BoundTextInput from '../components/BoundTextInput.vue';
import BoundTextareaInput from '../components/BoundTextareaInput.vue';
import AtlasContextControls from '../components/AtlasContextControls.vue';
import Collapsible from '../components/Collapsible.vue';
import RoleGatePanel from '../components/RoleGatePanel.vue';
import ScoutSettingsSection from '../components/ScoutSettingsSection.vue';
import ThemeToggle from '../components/ThemeToggle.vue';
import { useConsumerSecrets } from '../composables/use-consumer-secrets';
import type { ThemePreference } from '../composables/use-theme-preference';
import { roleLabel, type AtlasUserRole } from '../lib/roles';
import { isSettingFieldTarget, type SettingsHighlightTarget } from '../lib/settings-highlight';

const FEEDBACK_MESSAGE = 'Hope you like the app, please leave comments on github.';

const props = defineProps<{
  locale: string;
  userRole: AtlasUserRole;
  mapProvider: GeoMapProvider;
  selectedId: string;
  highlightTarget: SettingsHighlightTarget;
  theme: ThemePreference;
}>();

const emit = defineEmits<{
  'update:locale': [string];
  'update:userRole': [AtlasUserRole];
  'update:mapProvider': [GeoMapProvider];
  'update:selectedId': [string];
  'update:highlightTarget': [SettingsHighlightTarget];
  'update:theme': [ThemePreference];
}>();

const secrets = useConsumerSecrets();
const preferencesRef = ref<HTMLElement | null>(null);
const themeRef = ref<HTMLElement | null>(null);
const integrationsRef = ref<HTMLElement | null>(null);
const aiRef = ref<HTMLElement | null>(null);
const feedbackRef = ref<HTMLElement | null>(null);
const integrationsOpen = ref(props.highlightTarget === 'integrations');
const aiOpen = ref(props.highlightTarget === 'ai');
const feedbackDraft = ref('');
const feedbackSent = ref(false);

const settingFieldHighlight = computed(() =>
  isSettingFieldTarget(props.highlightTarget) ? props.highlightTarget : null,
);

watch(
  () => props.highlightTarget,
  (highlightTarget) => {
    if (!highlightTarget) return;

    const scrollTarget =
      highlightTarget === 'theme'
        ? themeRef.value
        : highlightTarget === 'integrations'
          ? integrationsRef.value
          : highlightTarget === 'ai'
            ? aiRef.value
            : highlightTarget === 'feedback'
              ? feedbackRef.value
              : isSettingFieldTarget(highlightTarget)
                ? preferencesRef.value?.querySelector(`[data-setting="${highlightTarget}"]`)
                : preferencesRef.value;

    scrollTarget?.scrollIntoView({ behavior: 'smooth', block: 'center' });

    if (highlightTarget === 'integrations') integrationsOpen.value = true;
    if (highlightTarget === 'ai') aiOpen.value = true;

    const timer = window.setTimeout(() => emit('update:highlightTarget', null), 2400);
    return () => window.clearTimeout(timer);
  },
  { immediate: true },
);

function submitFeedback() {
  feedbackSent.value = true;
  feedbackDraft.value = '';
}
</script>

<template>
  <section class="da-panel da-settings-panel">
    <div class="da-settings-head">
      <h2>Settings</h2>
      <ThemeToggle
        ref="themeRef"
        :theme="theme"
        :class="highlightTarget === 'theme' ? 'rd-highlight-target' : undefined"
        @change="emit('update:theme', $event)"
      />
    </div>

    <div ref="preferencesRef" class="da-settings-preferences">
      <AtlasContextControls
        :locale="locale"
        :user-role="userRole"
        :map-provider="mapProvider"
        :selected-id="selectedId"
        :highlight-field="settingFieldHighlight"
        @update:locale="emit('update:locale', $event)"
        @update:user-role="emit('update:userRole', $event)"
        @update:map-provider="emit('update:mapProvider', $event)"
        @update:selected-id="emit('update:selectedId', $event)"
      />
    </div>

    <div
      ref="integrationsRef"
      :class="highlightTarget === 'integrations' ? 'rd-highlight-target' : undefined"
    >
      <Collapsible
        panel-title="Integration keys (BYOK)"
        panel-summary="Google Maps, MapTiler, News API"
        :open="integrationsOpen"
        class="da-byok-collapsible"
        @open-change="integrationsOpen = $event"
      >
        <RoleGatePanel
          gate-label="Integration keys (BYOK)"
          :current-role="userRole"
          :allowed-roles="['admin']"
          status-text="Admin can manage API keys for Map, Intel, and Stack"
          :hidden-status-text="`Integration keys are read-only for ${roleLabel(userRole)}. Switch to Admin to configure BYOK.`"
        >
          <p v-if="!secrets.loaded" class="da-note">Loading encrypted key vault…</p>
          <div class="da-byok-fields">
            <div v-for="field in secrets.integrationFields" :key="field.id" class="da-byok-field">
              <BoundTextInput
                :field-label="field.label"
                :placeholder="field.placeholder"
                input-type="password"
                :value="secrets.getDraftValue(field.envKey)"
                @update:value="secrets.setDraftValue(field.envKey, $event)"
              />
              <p class="da-byok-field__desc">{{ field.description }}</p>
              <p class="da-byok-field__meta">
                Env key: <code>{{ field.envKey }}</code>
                <span
                  v-if="secrets.hasConfiguredKey(field.envKey)"
                  class="da-byok-field__status da-byok-field__status--ok"
                >
                  configured
                </span>
                <span v-else class="da-byok-field__status">not set</span>
              </p>
            </div>
          </div>
          <label class="da-byok-remember">
            <input
              type="checkbox"
              :checked="secrets.rememberKeys"
              @change="secrets.setRememberKeys(($event.target as HTMLInputElement).checked)"
            />
            Remember keys in this browser (localStorage + encryption)
          </label>
          <div class="da-byok-actions">
            <button type="button" class="rd-button" :disabled="!secrets.loaded" @click="void secrets.save()">
              Save keys
            </button>
            <button type="button" class="rd-button rd-button--ghost" @click="void secrets.clearAll()">
              Clear keys
            </button>
          </div>
          <p v-if="secrets.saveMessage" class="da-byok-save-msg">{{ secrets.saveMessage }}</p>
        </RoleGatePanel>
      </Collapsible>
    </div>

    <div ref="aiRef" :class="highlightTarget === 'ai' ? 'rd-highlight-target' : undefined">
      <Collapsible
        panel-title="Scout / AI providers (BYOK)"
        panel-summary="Deal scout — OpenAI, Anthropic, Gemini, Azure, Ollama"
        :open="aiOpen"
        class="da-byok-collapsible"
        @open-change="aiOpen = $event"
      >
        <ScoutSettingsSection :locale="locale" :selected-id="selectedId" />
        <RoleGatePanel
          gate-label="AI providers (BYOK)"
          :current-role="userRole"
          :allowed-roles="['admin']"
          status-text="Admin can manage AI keys for Scout and future premium features"
          :hidden-status-text="`AI keys are read-only for ${roleLabel(userRole)}. Switch to Admin to configure BYOK.`"
        >
          <p v-if="!secrets.loaded" class="da-note">Loading encrypted key vault…</p>
          <div class="da-byok-fields">
            <div v-for="field in secrets.aiFields" :key="field.id" class="da-byok-field">
              <BoundTextInput
                :field-label="field.label"
                :placeholder="field.placeholder"
                :input-type="field.sensitive ? 'password' : 'text'"
                :value="secrets.getDraftValue(field.envKey)"
                @update:value="secrets.setDraftValue(field.envKey, $event)"
              />
              <p class="da-byok-field__desc">{{ field.description }}</p>
              <p class="da-byok-field__meta">
                Env key: <code>{{ field.envKey }}</code>
                <span v-if="field.optional" class="da-byok-field__optional">optional</span>
                <span
                  v-if="secrets.hasConfiguredKey(field.envKey)"
                  class="da-byok-field__status da-byok-field__status--ok"
                >
                  configured
                </span>
                <span v-else-if="field.sensitive" class="da-byok-field__status">not set</span>
              </p>
            </div>
          </div>
          <label class="da-byok-remember">
            <input
              type="checkbox"
              :checked="secrets.rememberKeys"
              @change="secrets.setRememberKeys(($event.target as HTMLInputElement).checked)"
            />
            Remember keys in this browser (localStorage + encryption)
          </label>
          <div class="da-byok-actions">
            <button type="button" class="rd-button" :disabled="!secrets.loaded" @click="void secrets.save()">
              Save keys
            </button>
            <button type="button" class="rd-button rd-button--ghost" @click="void secrets.clearAll()">
              Clear keys
            </button>
          </div>
          <p v-if="secrets.saveMessage" class="da-byok-save-msg">{{ secrets.saveMessage }}</p>
        </RoleGatePanel>
      </Collapsible>
    </div>

    <div
      ref="feedbackRef"
      :class="['da-settings-feedback', highlightTarget === 'feedback' ? 'rd-highlight-target' : undefined].filter(Boolean)"
    >
      <BoundTextareaInput
        field-label="Feedback"
        placeholder="This is a demonstration, and feedback is not functional here."
        :value="feedbackDraft"
        @update:value="feedbackDraft = $event"
      />
      <div class="da-settings-feedback__actions">
        <button type="button" class="rd-button" @click="submitFeedback">Submit feedback</button>
      </div>
      <p v-if="feedbackSent" class="da-settings-feedback__msg">{{ FEEDBACK_MESSAGE }}</p>
    </div>
  </section>
</template>

// apps/proof-svelte/src/screens/SettingsScreen.svelte
<script module lang="ts">
  export const SETTINGS_SOURCE = `<SettingsScreen>
  <header><h2>Settings</h2><ThemeToggle /></header>
  <AtlasContextControls highlightField={…} />
  <Collapsible title="Integration keys (BYOK)">…</Collapsible>
  <Collapsible title="Scout / AI providers (BYOK)">…</Collapsible>
  <TextareaInput label="Feedback" />
</SettingsScreen>`;
</script>

<script lang="ts">
  import type { GeoMapProvider } from '@destination-atlas';
  import BoundTextInput from '../components/BoundTextInput.svelte';
  import BoundTextareaInput from '../components/BoundTextareaInput.svelte';
  import AtlasContextControls from '../components/AtlasContextControls.svelte';
  import Collapsible from '../components/Collapsible.svelte';
  import RoleGatePanel from '../components/RoleGatePanel.svelte';
  import ScoutSettingsSection from '../components/ScoutSettingsSection.svelte';
  import ThemeToggle from '../components/ThemeToggle.svelte';
  import { useConsumerSecrets } from '../lib/consumer-secrets.svelte';
  import type { ThemePreference } from '../lib/theme-preference.svelte';
  import { roleLabel, type AtlasUserRole } from '../lib/roles';
  import { isSettingFieldTarget, type SettingsHighlightTarget } from '../lib/settings-highlight';

  const FEEDBACK_MESSAGE = 'Hope you like the app, please leave comments on github.';

  let {
    locale,
    userRole,
    mapProvider,
    selectedId,
    highlightTarget,
    theme,
    onLocaleChange,
    onUserRoleChange,
    onMapProviderChange,
    onSelectedIdChange,
    onHighlightTargetChange,
    onThemeChange,
  }: {
    locale: string;
    userRole: AtlasUserRole;
    mapProvider: GeoMapProvider;
    selectedId: string;
    highlightTarget: SettingsHighlightTarget;
    theme: ThemePreference;
    onLocaleChange?: (locale: string) => void;
    onUserRoleChange?: (role: AtlasUserRole) => void;
    onMapProviderChange?: (provider: GeoMapProvider) => void;
    onSelectedIdChange?: (id: string) => void;
    onHighlightTargetChange?: (target: SettingsHighlightTarget) => void;
    onThemeChange?: (theme: ThemePreference) => void;
  } = $props();

  const secrets = useConsumerSecrets();
  let preferencesRef = $state<HTMLElement | null>(null);
  let themeRef = $state<HTMLElement | null>(null);
  let integrationsRef = $state<HTMLElement | null>(null);
  let aiRef = $state<HTMLElement | null>(null);
  let feedbackRef = $state<HTMLElement | null>(null);
  let integrationsOpen = $state(false);
  let aiOpen = $state(false);
  let feedbackDraft = $state('');
  let feedbackSent = $state(false);

  const settingFieldHighlight = $derived(
    isSettingFieldTarget(highlightTarget) ? highlightTarget : null,
  );

  $effect(() => {
    const target = highlightTarget;
    if (!target) {
      return;
    }

    const scrollTarget =
      target === 'theme'
        ? themeRef
        : target === 'integrations'
          ? integrationsRef
          : target === 'ai'
            ? aiRef
            : target === 'feedback'
              ? feedbackRef
              : isSettingFieldTarget(target)
                ? preferencesRef?.querySelector(`[data-setting="${target}"]`)
                : preferencesRef;

    scrollTarget?.scrollIntoView({ behavior: 'smooth', block: 'center' });

    if (target === 'integrations') integrationsOpen = true;
    if (target === 'ai') aiOpen = true;

    const timer = window.setTimeout(() => onHighlightTargetChange?.(null), 2400);
    return () => window.clearTimeout(timer);
  });

  function submitFeedback() {
    feedbackSent = true;
    feedbackDraft = '';
  }
</script>

<section class="da-panel da-settings-panel">
  <div class="da-settings-head">
    <h2>Settings</h2>
    <div bind:this={themeRef} class:rd-highlight-target={highlightTarget === 'theme'}>
      <ThemeToggle {theme} onChange={onThemeChange} />
    </div>
  </div>

  <div bind:this={preferencesRef} class="da-settings-preferences">
    <AtlasContextControls
      {locale}
      {userRole}
      {mapProvider}
      {selectedId}
      highlightField={settingFieldHighlight}
      onLocaleChange={onLocaleChange}
      onUserRoleChange={onUserRoleChange}
      onMapProviderChange={onMapProviderChange}
      onSelectedIdChange={onSelectedIdChange}
    />
  </div>

  <div
    bind:this={integrationsRef}
    class:rd-highlight-target={highlightTarget === 'integrations'}
  >
    <Collapsible
      panelTitle="Integration keys (BYOK)"
      panelSummary="Google Maps, MapTiler, News API"
      open={integrationsOpen}
      class="da-byok-collapsible"
      onOpenChange={(open) => (integrationsOpen = open)}
    >
      <RoleGatePanel
        gateLabel="Integration keys (BYOK)"
        currentRole={userRole}
        allowedRoles={['admin']}
        statusText="Admin can manage API keys for Map, Intel, and Stack"
        hiddenStatusText={`Integration keys are read-only for ${roleLabel(userRole)}. Switch to Admin to configure BYOK.`}
      >
        {#if !secrets.loaded}<p class="da-note">Loading encrypted key vault…</p>{/if}
        <div class="da-byok-fields">
          {#each secrets.integrationFields as field (field.id)}
            <div class="da-byok-field">
              <BoundTextInput
                fieldLabel={field.label}
                placeholder={field.placeholder}
                inputType="password"
                value={secrets.getDraftValue(field.envKey)}
                onValueChange={(value) => secrets.setDraftValue(field.envKey, value)}
              />
              <p class="da-byok-field__desc">{field.description}</p>
              <p class="da-byok-field__meta">
                Env key: <code>{field.envKey}</code>
                {#if secrets.hasConfiguredKey(field.envKey)}
                  <span class="da-byok-field__status da-byok-field__status--ok">configured</span>
                {:else}
                  <span class="da-byok-field__status">not set</span>
                {/if}
              </p>
            </div>
          {/each}
        </div>
        <label class="da-byok-remember">
          <input
            type="checkbox"
            checked={secrets.rememberKeys}
            onchange={(event) => secrets.setRememberKeys((event.currentTarget as HTMLInputElement).checked)}
          />
          Remember keys in this browser (localStorage + encryption)
        </label>
        <div class="da-byok-actions">
          <button type="button" class="rd-button" disabled={!secrets.loaded} onclick={() => void secrets.save()}>
            Save keys
          </button>
          <button type="button" class="rd-button rd-button--ghost" onclick={() => void secrets.clearAll()}>
            Clear keys
          </button>
        </div>
        {#if secrets.saveMessage}<p class="da-byok-save-msg">{secrets.saveMessage}</p>{/if}
      </RoleGatePanel>
    </Collapsible>
  </div>

  <div bind:this={aiRef} class:rd-highlight-target={highlightTarget === 'ai'}>
    <Collapsible
      panelTitle="Scout / AI providers (BYOK)"
      panelSummary="Deal scout — OpenAI, Anthropic, Gemini, Azure, Ollama"
      open={aiOpen}
      class="da-byok-collapsible"
      onOpenChange={(open) => (aiOpen = open)}
    >
      <ScoutSettingsSection {locale} {selectedId} />
      <RoleGatePanel
        gateLabel="AI providers (BYOK)"
        currentRole={userRole}
        allowedRoles={['admin']}
        statusText="Admin can manage AI keys for Scout and future premium features"
        hiddenStatusText={`AI keys are read-only for ${roleLabel(userRole)}. Switch to Admin to configure BYOK.`}
      >
        {#if !secrets.loaded}<p class="da-note">Loading encrypted key vault…</p>{/if}
        <div class="da-byok-fields">
          {#each secrets.aiFields as field (field.id)}
            <div class="da-byok-field">
              <BoundTextInput
                fieldLabel={field.label}
                placeholder={field.placeholder}
                inputType={field.sensitive ? 'password' : 'text'}
                value={secrets.getDraftValue(field.envKey)}
                onValueChange={(value) => secrets.setDraftValue(field.envKey, value)}
              />
              <p class="da-byok-field__desc">{field.description}</p>
              <p class="da-byok-field__meta">
                Env key: <code>{field.envKey}</code>
                {#if field.optional}<span class="da-byok-field__optional">optional</span>{/if}
                {#if secrets.hasConfiguredKey(field.envKey)}
                  <span class="da-byok-field__status da-byok-field__status--ok">configured</span>
                {:else if field.sensitive}
                  <span class="da-byok-field__status">not set</span>
                {/if}
              </p>
            </div>
          {/each}
        </div>
        <label class="da-byok-remember">
          <input
            type="checkbox"
            checked={secrets.rememberKeys}
            onchange={(event) => secrets.setRememberKeys((event.currentTarget as HTMLInputElement).checked)}
          />
          Remember keys in this browser (localStorage + encryption)
        </label>
        <div class="da-byok-actions">
          <button type="button" class="rd-button" disabled={!secrets.loaded} onclick={() => void secrets.save()}>
            Save keys
          </button>
          <button type="button" class="rd-button rd-button--ghost" onclick={() => void secrets.clearAll()}>
            Clear keys
          </button>
        </div>
        {#if secrets.saveMessage}<p class="da-byok-save-msg">{secrets.saveMessage}</p>{/if}
      </RoleGatePanel>
    </Collapsible>
  </div>

  <div
    bind:this={feedbackRef}
    class={['da-settings-feedback', highlightTarget === 'feedback' ? 'rd-highlight-target' : '']
      .filter(Boolean)
      .join(' ')}
  >
    <BoundTextareaInput
      fieldLabel="Feedback"
      placeholder="This is a demonstration, and feedback is not functional here."
      value={feedbackDraft}
      onValueChange={(value) => (feedbackDraft = value)}
    />
    <div class="da-settings-feedback__actions">
      <button type="button" class="rd-button" onclick={submitFeedback}>Submit feedback</button>
    </div>
    {#if feedbackSent}<p class="da-settings-feedback__msg">{FEEDBACK_MESSAGE}</p>{/if}
  </div>
</section>
