// packages/angular/src/visual/plugin/status-badge/status-badge.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface StatusBadgeProps {
  statusText?: string;
  tone?: 'success' | 'warning' | 'error' | 'neutral';
  className?: string;
}

/** @rosettadash/angular/visual/plugin/status-badge — visual.plugin.status-badge */
@Component({
  selector: 'rd-plugin-status-badge',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span [attr.data-testid]="'rd-plugin-status-badge'" [ngClass]="badgeClass()">{{ statusText() ?? 'Active' }}</span>
  `,
})
export class StatusBadge {
  readonly className = input<string | undefined>(undefined);
  readonly statusText = input<string | undefined>(undefined);
  readonly tone = input<'success' | 'warning' | 'error' | 'neutral' | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-plugin-status-badge', this.className()].filter(Boolean).join(' '),
  );
  badgeClass(): string {
    return ['rd-plugin-status-badge', 'rd-plugin-status-badge--' + (this.tone() ?? 'success'), this.className()].filter(Boolean).join(' ');
  }
}

// packages/react/src/visual/plugin/status-badge/StatusBadge.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface StatusBadgeProps {
  statusText?: string;
  tone?: 'success' | 'warning' | 'error' | 'neutral';
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/plugin/status-badge — visual.plugin.status-badge */
export const StatusBadge = forwardRef<HTMLElement, StatusBadgeProps>(function StatusBadge(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-plugin-status-badge', className].filter(Boolean).join(' ');

  return (
    <span ref={ref as React.RefObject<HTMLElement>} className={[rootClass, `rd-status-badge--${props.tone ?? 'success'}`].join(' ')} style={style} data-testid="rd-plugin-status-badge">{props.statusText ?? 'Active'}</span>
  );
});
