// packages/svelte/src/visual/chart/bar/BarChart.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { BarChartProps } from './types';

	type Props = BarChartProps & { children?: Snippet };

	let {
		className,
		title,
		children,
	}: Props = $props();
	const barHeights = [40, 65, 55, 80, 48];
	const rootClass = $derived(['rd-chart-bar', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-chart-bar">
	<header class="rd-chart-bar__header"><span>{title ?? 'Bar chart'}</span></header>
	<div class="rd-chart-bar__bars" aria-hidden="true">
		{#each barHeights as h, i (i)}<div class="rd-chart-bar__bar-wrap"><div class="rd-chart-bar__bar" style:height="{h}%"></div></div>{/each}
	</div>
	{@render children?.()}
</section>

// packages/react/src/visual/chart/bar/BarChart.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface BarChartProps {
  title?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/chart/bar — visual.chart.bar */
export const BarChart = forwardRef<HTMLElement, BarChartProps>(function BarChart(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-chart-bar', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-chart-bar">
      <header className="rd-chart-bar__header"><span>{props.title ?? 'Bar chart'}</span></header>
      <div className="rd-chart-bar__bars" aria-hidden="true">
        {[40, 65, 55, 80, 48].map((h, i) => (
          <div key={i} className="rd-chart-bar__bar-wrap"><div className="rd-chart-bar__bar" style={{ height: `${h}%` }} /></div>
        ))}
      </div>
      {children}
    </section>
  );
});
