// packages/angular/src/visual/chart/bar/bar-chart.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface BarChartProps {
  title?: string;
  className?: string;
}

/** @rosettadash/angular/visual/chart/bar — visual.chart.bar */
@Component({
  selector: 'rd-chart-bar',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-chart-bar'" [ngClass]="rootClass()">
      <header class="rd-chart-bar__header"><span>{{ title() ?? 'Bar chart' }}</span></header>
      <div class="rd-chart-bar__bars" aria-hidden="true">
        @for (h of barHeights; track $index) {
          <div class="rd-chart-bar__bar-wrap"><div class="rd-chart-bar__bar" [style.height.%]="h"></div></div>
        }
      </div>
      <ng-content />
    </section>
  `,
})
export class BarChart {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-chart-bar', this.className()].filter(Boolean).join(' '),
  );
  readonly barHeights = [40, 65, 55, 80, 48];
}

// packages/react/src/visual/chart/bar/BarChart.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface BarChartProps {
  title?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/chart/bar — visual.chart.bar */
export const BarChart = forwardRef<HTMLElement, BarChartProps>(function BarChart(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-chart-bar', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-chart-bar">
      <header className="rd-chart-bar__header"><span>{props.title ?? 'Bar chart'}</span></header>
      <div className="rd-chart-bar__bars" aria-hidden="true">
        {[40, 65, 55, 80, 48].map((h, i) => (
          <div key={i} className="rd-chart-bar__bar-wrap"><div className="rd-chart-bar__bar" style={{ height: `${h}%` }} /></div>
        ))}
      </div>
      {children}
    </section>
  );
});
