// packages/react/src/domain/person-invite/PersonInvite.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface PersonInviteProps {
  emailPlaceholder?: string;
  onInvite?: (email: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/domain/person-invite — domain.person-invite */
export const PersonInvite = forwardRef<HTMLElement, PersonInviteProps>(function PersonInvite(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-person-invite', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-person-invite">
      <span className="rd-field__label">Invite team member</span>
      <input type="email" className="rd-input" placeholder={props.emailPlaceholder ?? 'name@company.com'} />
      <button type="button" className="rd-button" onClick={() => props.onInvite?.('')}>Send invite</button>
      {children}
    </section>
  );
});

// packages/angular/src/domain/person-invite/person-invite.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface PersonInviteProps {
  emailPlaceholder?: string;
  onInvite?: (email: string) => void;
  className?: string;
}

/** @rosettadash/angular/domain/person-invite — domain.person-invite */
@Component({
  selector: 'rd-person-invite',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-person-invite'" [ngClass]="rootClass()">
      <span class="rd-field__label">Invite team member</span>
      <input type="email" class="rd-input" [placeholder]="emailPlaceholder() ?? 'name@company.com'" />
      <button type="button" class="rd-button">Send invite</button>
      <ng-content />
    </section>
  `,
})
export class PersonInvite {
  readonly className = input<string | undefined>(undefined);
  readonly emailPlaceholder = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-person-invite', this.className()].filter(Boolean).join(' '),
  );
}
