// packages/react/src/visual/news/search-box/NewsSearchBox.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface NewsSearchBoxProps {
  label?: string;
  placeholder?: string;
  value?: string;
  onSearch?: (query: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/news/search-box — visual.news.search-box */
export const NewsSearchBox = forwardRef<HTMLElement, NewsSearchBoxProps>(function NewsSearchBox(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-news-search-box', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-news-search-box">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <div className="rd-search__row">
        <input type="search" className="rd-input" placeholder={props.placeholder ?? 'Search news…'} value={props.value} onChange={(e) => props.onSearch?.(e.target.value)} />
        <button type="button" className="rd-button">Search</button>
      </div>
      {children}
    </section>
  );
});

// packages/angular/src/visual/news/search-box/news-search-box.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface NewsSearchBoxProps {
  label?: string;
  placeholder?: string;
  value?: string;
  onSearch?: (query: string) => void;
  className?: string;
}

/** @rosettadash/angular/visual/news/search-box — visual.news.search-box */
@Component({
  selector: 'rd-news-search-box',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-news-search-box'" [ngClass]="rootClass()">
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      <div class="rd-search__row">
        <input type="search" class="rd-input" [placeholder]="placeholder() ?? 'Search news…'" [value]="value() ?? ''" />
        <button type="button" class="rd-button">Search</button>
      </div>
      <ng-content />
    </section>
  `,
})
export class NewsSearchBox {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly placeholder = input<string | undefined>(undefined);
  readonly value = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-news-search-box', this.className()].filter(Boolean).join(' '),
  );
}
