// packages/angular/src/visual/wasm/module/wasm-module.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface WasmModuleProps {
  moduleLabel?: string;
  exportName?: string;
  className?: string;
}

/** @rosettadash/angular/visual/wasm/module — visual.wasm.module */
@Component({
  selector: 'rd-wasm-module',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-wasm-module'" [ngClass]="rootClass()">
      <span class="rd-wasm__label">{{ moduleLabel() ?? 'WASM Module' }}</span>
      <code>{{ exportFn() ?? 'run()' }}()</code>
      <ng-content />
    </section>
  `,
})
export class WasmModule {
  readonly className = input<string | undefined>(undefined);
  readonly moduleLabel = input<string | undefined>(undefined);
  readonly exportName = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-wasm-module', this.className()].filter(Boolean).join(' '),
  );
  exportFn(): string | undefined {
    return this.exportName();
  }
}

// packages/react/src/visual/wasm/module/WasmModule.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface WasmModuleProps {
  moduleLabel?: string;
  exportName?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/wasm/module — visual.wasm.module */
export const WasmModule = forwardRef<HTMLElement, WasmModuleProps>(function WasmModule(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-wasm-module', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-wasm-module">
      <span className="rd-wasm__label">{props.moduleLabel ?? 'WASM Module'}</span>
      <code>{props.exportName ?? 'run()'}()</code>
      {children}
    </section>
  );
});
