// packages/svelte/src/visual/news/search-box/NewsSearchBox.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { NewsSearchBoxProps } from './types';

	type Props = NewsSearchBoxProps & { children?: Snippet };

	let {
		className,
		label,
		placeholder,
		value,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-news-search-box', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-news-search-box">
	{#if label}<span class="rd-field__label">{label}</span>{/if}
	<div class="rd-search__row">
		<input type="search" class="rd-input" placeholder={placeholder ?? 'Search news…'} value={value ?? ''} />
		<button type="button" class="rd-button">Search</button>
	</div>
	{@render children?.()}
</section>

// packages/react/src/visual/news/search-box/NewsSearchBox.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface NewsSearchBoxProps {
  label?: string;
  placeholder?: string;
  value?: string;
  onSearch?: (query: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/news/search-box — visual.news.search-box */
export const NewsSearchBox = forwardRef<HTMLElement, NewsSearchBoxProps>(function NewsSearchBox(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-news-search-box', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-news-search-box">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <div className="rd-search__row">
        <input type="search" className="rd-input" placeholder={props.placeholder ?? 'Search news…'} value={props.value} onChange={(e) => props.onSearch?.(e.target.value)} />
        <button type="button" className="rd-button">Search</button>
      </div>
      {children}
    </section>
  );
});
