// packages/angular/src/visual/detail/detail-panel.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface DetailPanelProps {
  title?: string;
  emptyMessage?: string;
  className?: string;
}

/** @rosettadash/angular/visual/detail — visual.detail */
@Component({
  selector: 'rd-detail',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-detail'" [ngClass]="rootClass()">
      <header class="rd-detail__header"><span>{{ title() ?? 'Details' }}</span></header>
      <p class="rd-detail__empty">{{ emptyMessage() ?? 'Select a row to view details' }}</p>
      <ng-content />
    </section>
  `,
})
export class DetailPanel {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly emptyMessage = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-detail', this.className()].filter(Boolean).join(' '),
  );
}

// packages/react/src/visual/detail/DetailPanel.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface DetailPanelProps {
  title?: string;
  emptyMessage?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/detail — visual.detail */
export const DetailPanel = forwardRef<HTMLElement, DetailPanelProps>(function DetailPanel(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-detail', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-detail">
      <header className="rd-detail__header"><span>{props.title ?? 'Details'}</span></header>
      <p className="rd-detail__empty">{props.emptyMessage ?? 'Select a row to view details'}</p>
      {children}
    </section>
  );
});
