// packages/angular/src/visual/display/3d-scene/three-scene-point-cloud.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface ThreeScenePointCloudProps {
  title?: string;
  mode?: string;
  className?: string;
}

/** @rosettadash/angular/visual/display/3d-scene — visual.display.3d-scene */
@Component({
  selector: 'rd-display-3d-scene',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-display-3d-scene'" [ngClass]="rootClass()" [attr.data-three-mode]="mode()" [attr.data-three-title]="title()" [attr.aria-label]="title() ?? '3D host'"><ng-content /></section>
  `,
})
export class ThreeScenePointCloud {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly mode = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-display-3d-scene', this.className()].filter(Boolean).join(' '),
  );
}

// packages/react/src/visual/display/3d-scene/ThreeScenePointCloud.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface ThreeScenePointCloudProps {
  title?: string;
  mode?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/display/3d-scene — visual.display.3d-scene */
export const ThreeScenePointCloud = forwardRef<HTMLElement, ThreeScenePointCloudProps>(function ThreeScenePointCloud(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-display-3d-scene', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-display-3d-scene" data-three-mode={props.mode} data-three-title={props.title} aria-label={props.title ?? '3D host'}>{children}</section>
  );
});
