// packages/react/src/visual/input/text/TextInput.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface TextInputProps {
  label?: string;
  placeholder?: string;
  required?: boolean;
  value?: string;
  defaultValue?: string;
  onChange?: (value: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/input/text — visual.input.text */
export const TextInput = forwardRef<HTMLElement, TextInputProps>(function TextInput(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-input-text', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-input-text">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <input
        type="text"
        className="rd-input"
        placeholder={props.placeholder}
        required={props.required}
        value={props.value}
        defaultValue={props.defaultValue}
        onChange={(e) => props.onChange?.(e.target.value)}
      />
      {children}
    </section>
  );
});

// packages/svelte/src/visual/input/text/TextInput.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { TextInputProps } from './types';

	type Props = TextInputProps & { children?: Snippet };

	let {
		className,
		label,
		placeholder,
		required,
		value,
		defaultValue,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-input-text', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-input-text">
	{#if label}<span class="rd-field__label">{label}</span>{/if}
	<input type="text" class="rd-input" placeholder={placeholder ?? ''} required={required ?? false} value={value ?? ''} />
	{@render children?.()}
</section>
