// packages/angular/src/visual/news/region-select/news-region-select.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface NewsRegionSelectProps {
  label?: string;
  placeholder?: string;
  options?: { value: string; label: string }[];
  value?: string;
  onChange?: (value: string) => void;
  className?: string;
}

/** @rosettadash/angular/visual/news/region-select — visual.news.region-select */
@Component({
  selector: 'rd-news-region-select',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-news-region-select'" [ngClass]="rootClass()">
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      <select class="rd-select" [value]="value() ?? ''">
        <option value="">{{ placeholder() ?? 'Select…' }}</option>
        @for (o of options() ?? []; track o.value) {
          <option [value]="o.value">{{ o.label }}</option>
        }
      </select>
      <ng-content />
    </section>
  `,
})
export class NewsRegionSelect {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly placeholder = input<string | undefined>(undefined);
  readonly value = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-news-region-select', this.className()].filter(Boolean).join(' '),
  );
}

// packages/react/src/visual/news/region-select/NewsRegionSelect.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface NewsRegionSelectProps {
  label?: string;
  placeholder?: string;
  options?: { value: string; label: string }[];
  value?: string;
  onChange?: (value: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/news/region-select — visual.news.region-select */
export const NewsRegionSelect = forwardRef<HTMLElement, NewsRegionSelectProps>(function NewsRegionSelect(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-news-region-select', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-news-region-select">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <select className="rd-select" value={props.value} onChange={(e) => props.onChange?.(e.target.value)}>
        <option value="">{props.placeholder ?? 'Select…'}</option>
        {(props.options ?? []).map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}
      </select>
      {children}
    </section>
  );
});
