// packages/angular/src/logic/timer/timer.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface TimerProps {
  label?: string;
  mode?: 'interval' | 'countdown';
  intervalMs?: number;
  tickCount?: number;
  className?: string;
}

/** @rosettadash/angular/logic/timer — logic.timer */
@Component({
  selector: 'rd-timer',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-timer'" [ngClass]="rootClass()">
      @if (label()) { <span class="rd-timer__label">{{ label() }}</span> }
      <span class="rd-timer__value">{{ tickCount() ?? 0 }} ticks</span>
      <ng-content />
    </section>
  `,
})
export class Timer {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly mode = input<'interval' | 'countdown' | undefined>(undefined);
  readonly intervalMs = input<number | undefined>(undefined);
  readonly tickCount = input<number | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-timer', this.className()].filter(Boolean).join(' '),
  );
}

// packages/react/src/logic/timer/Timer.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface TimerProps {
  label?: string;
  mode?: 'interval' | 'countdown';
  intervalMs?: number;
  tickCount?: number;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/logic/timer — logic.timer */
export const Timer = forwardRef<HTMLElement, TimerProps>(function Timer(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-timer', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-timer">
      {props.label ? <span className="rd-timer__label">{props.label}</span> : null}
      <span className="rd-timer__value">{props.tickCount ?? 0} ticks</span>
      {children}
    </section>
  );
});
