// packages/svelte/src/visual/input/textarea/TextareaInput.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { TextareaInputProps } from './types';

	type Props = TextareaInputProps & { children?: Snippet };

	let {
		className,
		label,
		placeholder,
		rows,
		value,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-input-textarea', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-input-textarea">
	{#if label}<span class="rd-field__label">{label}</span>{/if}
	<textarea class="rd-textarea" rows={rows ?? 4} placeholder={placeholder ?? ''}>{value ?? ''}</textarea>
	{@render children?.()}
</section>

// packages/react/src/visual/input/textarea/TextareaInput.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface TextareaInputProps {
  label?: string;
  placeholder?: string;
  rows?: number;
  value?: string;
  onChange?: (value: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/input/textarea — visual.input.textarea */
export const TextareaInput = forwardRef<HTMLElement, TextareaInputProps>(function TextareaInput(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-input-textarea', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-input-textarea">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <textarea
        className="rd-textarea"
        rows={props.rows ?? 4}
        placeholder={props.placeholder}
        value={props.value}
        onChange={(e) => props.onChange?.(e.target.value)}
      />
      {children}
    </section>
  );
});
