// apps/proof-svelte/src/App.svelte
<script lang="ts">
  import { buildAtlasLocation } from '@rosettadash/core';
  import { DESTINATION_ATLAS_SCREENS, MOCK_DESTINATIONS } from '@destination-atlas';
  import { screenAllowedForRole } from './lib/roles';
  import { provideConsumerSecrets } from './lib/consumer-secrets.svelte';
  import { createThemePreference } from './lib/theme-preference.svelte';
  import { createClientRouterMode } from './state/client-router-mode.svelte';
  import { createDestinationAtlasState } from './state/destination-atlas-state.svelte';
  import type { SettingFieldTarget } from './lib/settings-highlight';
  import ErrorBoundary from './components/ErrorBoundary.svelte';
  import ScreenWorkbenchMobileToggle from './components/ScreenWorkbenchMobileToggle.svelte';
  import ScreenWorkbenchPreview from './components/ScreenWorkbenchPreview.svelte';
  import ComponentSourcePanel from './components/ComponentSourcePanel.svelte';
  import RouterModeSelect from './components/RouterModeSelect.svelte';
  import AtlasContextSummary from './components/AtlasContextSummary.svelte';
  import AboutScreen, { ABOUT_SOURCE } from './screens/AboutScreen.svelte';
  import OverviewScreen, { OVERVIEW_SOURCE } from './screens/OverviewScreen.svelte';
  import DestinationsScreen, { DESTINATIONS_SOURCE } from './screens/DestinationsScreen.svelte';
  import MapsScreen, { MAPS_SOURCE } from './screens/MapsScreen.svelte';
  import MediaScreen, { MEDIA_SOURCE } from './screens/MediaScreen.svelte';
  import AuthoringScreen, { AUTHORING_SOURCE } from './screens/AuthoringScreen.svelte';
  import IntelScreen, { INTEL_SOURCE } from './screens/IntelScreen.svelte';
  import PlanScreen, { PLAN_SOURCE } from './screens/PlanScreen.svelte';
  import ViewsScreen, { VIEWS_SOURCE } from './screens/ViewsScreen.svelte';
  import StackScreen, { STACK_SOURCE } from './screens/StackScreen.svelte';
  import SettingsScreen, { SETTINGS_SOURCE } from './screens/SettingsScreen.svelte';

  provideConsumerSecrets();

  const initialDestId = MOCK_DESTINATIONS[0]?.id ?? '';
  const atlas = createDestinationAtlasState(initialDestId);
  const themeStore = createThemePreference();
  const routerModeStore = createClientRouterMode();

  let mobileView = $state<'preview' | 'source'>('preview');

  const SCREEN_SOURCES: Record<string, string> = {
    about: ABOUT_SOURCE,
    overview: OVERVIEW_SOURCE,
    destinations: DESTINATIONS_SOURCE,
    maps: MAPS_SOURCE,
    media: MEDIA_SOURCE,
    authoring: AUTHORING_SOURCE,
    intel: INTEL_SOURCE,
    plan: PLAN_SOURCE,
    views: VIEWS_SOURCE,
    stack: STACK_SOURCE,
    settings: SETTINGS_SOURCE,
  };

  const activeScreen = $derived(DESTINATION_ATLAS_SCREENS.find((screen) => screen.id === atlas.screen));
  const visibleScreens = $derived(
    DESTINATION_ATLAS_SCREENS.filter((screen) => screenAllowedForRole(screen.id, atlas.userRole)),
  );

  const atlasQuery = $derived({
    dest: atlas.selectedId,
    locale: atlas.locale,
    provider: atlas.mapProvider,
    role: atlas.userRole,
  });

  const urlDefaults = {
    dest: initialDestId,
    locale: 'en',
    provider: 'leaflet' as const,
    role: 'viewer' as const,
  };

  function screenTo(screenId: (typeof visibleScreens)[number]['id']) {
    const mapsPanel = screenId === 'maps' ? atlas.mapsPanel : 'map';
    const { pathname, search } = buildAtlasLocation(screenId, atlasQuery, urlDefaults, mapsPanel);
    const query = Object.fromEntries(new URLSearchParams(search.replace(/^\?/, '')));
    return { path: pathname, query };
  }

  function screenHref(screenId: (typeof visibleScreens)[number]['id']) {
    const { path, query } = screenTo(screenId);
    const search = new URLSearchParams(query).toString();
    return search ? `${path}?${search}` : path;
  }

  function navigateScreen(screenId: (typeof visibleScreens)[number]['id'], event: MouseEvent) {
    event.preventDefault();
    atlas.setScreen(screenId);
  }

  function openSetting(field: SettingFieldTarget | 'theme' | 'ai') {
    atlas.setHighlightTarget(field);
    atlas.setScreen('settings');
  }

  const settingsIndex = $derived(visibleScreens.findIndex((screen) => screen.id === 'settings'));
  const navScreensBeforeScout = $derived(
    settingsIndex >= 0 ? visibleScreens.slice(0, settingsIndex) : visibleScreens,
  );
  const navScreensFromSettings = $derived(settingsIndex >= 0 ? visibleScreens.slice(settingsIndex) : []);
</script>

<div class="da-shell">
  <header class="da-header">
    <h1>Destination Atlas</h1>
    <p>Current and historic information about world locations — Svelte proof (DAS-125)</p>
  </header>

  <div class="da-body-row">
    <div class="da-preview-column">
      <div class="da-context-strip">
        <RouterModeSelect
          mode={routerModeStore.routerMode}
          onChange={routerModeStore.setRouterMode}
        />
        <AtlasContextSummary
          locale={atlas.locale}
          userRole={atlas.userRole}
          mapProvider={atlas.mapProvider}
          selectedId={atlas.selectedId}
          theme={themeStore.theme}
          onOpenSetting={openSetting}
        />
      </div>

      <nav class="da-nav da-tabbar" aria-label="Screens">
        {#each navScreensBeforeScout as screen (screen.id)}
          <a
            href={screenHref(screen.id)}
            class="da-tabbar__tab"
            aria-current={atlas.screen === screen.id ? 'page' : undefined}
            onclick={(event) => navigateScreen(screen.id, event)}
          >
            {screen.label}
          </a>
        {/each}
        <button
          type="button"
          class="da-tabbar__tab"
          aria-current={atlas.settingsScoutFocus ? 'page' : undefined}
          onclick={() => atlas.openScoutSettings()}
        >
          Scout
        </button>
        {#each navScreensFromSettings as screen (screen.id)}
          <a
            href={screenHref(screen.id)}
            class="da-tabbar__tab"
            aria-current={atlas.screen === screen.id && !atlas.settingsScoutFocus ? 'page' : undefined}
            onclick={(event) => navigateScreen(screen.id, event)}
          >
            {screen.label}
          </a>
        {/each}
      </nav>

      <div class="da-workbench-host">
        <ErrorBoundary label={activeScreen?.label ?? atlas.screen}>
          <ScreenWorkbenchMobileToggle {mobileView} onChange={(view) => (mobileView = view)} />
          <ScreenWorkbenchPreview {mobileView}>
            {#if atlas.screen === 'about'}
              <AboutScreen />
            {:else if atlas.screen === 'overview'}
              <OverviewScreen locale={atlas.locale} userRole={atlas.userRole} />
            {:else if atlas.screen === 'destinations'}
              <DestinationsScreen
                locale={atlas.locale}
                userRole={atlas.userRole}
                selectedId={atlas.selectedId}
                destSearch={atlas.destSearch}
                destRegion={atlas.destRegion}
                timePreset={atlas.timePreset}
                visitPeriodStart={atlas.visitPeriodStart}
                visitPeriodEnd={atlas.visitPeriodEnd}
                onSelectedIdChange={atlas.setSelectedId}
                onDestSearchChange={atlas.setDestSearch}
                onDestRegionChange={atlas.setDestRegion}
                onTimePresetChange={atlas.setTimePreset}
                onVisitPeriodChange={atlas.setVisitPeriod}
                onFocusDestinationOnMap={atlas.focusDestinationOnMap}
              />
            {:else if atlas.screen === 'maps'}
              <MapsScreen
                locale={atlas.locale}
                selectedId={atlas.selectedId}
                mapProvider={atlas.mapProvider}
                mapLocationQuery={atlas.mapLocationQuery}
                mapViewOverride={atlas.mapViewOverride}
                mapsPanel={atlas.mapsPanel}
                onSelectedIdChange={atlas.setSelectedId}
                onMapProviderChange={atlas.setMapProvider}
                onMapLocationQueryChange={atlas.setMapLocationQuery}
                onMapsPanelChange={atlas.setMapsPanel}
                onFocusDestinationOnMap={atlas.focusDestinationOnMap}
                onGoToMapView={atlas.goToMapView}
                onOpenSettings={() => openSetting('integrations')}
              />
            {:else if atlas.screen === 'media'}
              <MediaScreen
                locale={atlas.locale}
                selectedId={atlas.selectedId}
                onSelectedIdChange={atlas.setSelectedId}
                onOpenAuthoring={atlas.openAuthoringForDestination}
              />
            {:else if atlas.screen === 'authoring'}
              <AuthoringScreen locale={atlas.locale} selectedId={atlas.selectedId} />
            {:else if atlas.screen === 'intel'}
              <IntelScreen
                userRole={atlas.userRole}
                newsQuery={atlas.newsQuery}
                newsRegion={atlas.newsRegion}
                selectedArticleId={atlas.selectedArticleId}
                onNewsQueryChange={atlas.setNewsQuery}
                onNewsRegionChange={atlas.setNewsRegion}
                onSelectedArticleIdChange={atlas.setSelectedArticleId}
                onOpenSettings={() => openSetting('integrations')}
              />
            {:else if atlas.screen === 'plan'}
              <PlanScreen userRole={atlas.userRole} locale={atlas.locale} />
            {:else if atlas.screen === 'views'}
              <ViewsScreen
                locale={atlas.locale}
                selectedId={atlas.selectedId}
                onSelectedIdChange={atlas.setSelectedId}
              />
            {:else if atlas.screen === 'stack'}
              <StackScreen userRole={atlas.userRole} />
            {:else if atlas.screen === 'settings'}
              <SettingsScreen
                locale={atlas.locale}
                userRole={atlas.userRole}
                mapProvider={atlas.mapProvider}
                selectedId={atlas.selectedId}
                highlightTarget={atlas.highlightTarget}
                theme={themeStore.theme}
                onLocaleChange={atlas.setLocale}
                onUserRoleChange={atlas.setUserRole}
                onMapProviderChange={atlas.setMapProvider}
                onSelectedIdChange={atlas.setSelectedId}
                onHighlightTargetChange={atlas.setHighlightTarget}
                onThemeChange={themeStore.setTheme}
              />
            {/if}
          </ScreenWorkbenchPreview>
        </ErrorBoundary>
      </div>
    </div>
    <ComponentSourcePanel source={SCREEN_SOURCES[atlas.screen] ?? ''} hidden={mobileView === 'preview'} />
  </div>
</div>

// apps/proof-react/src/App.tsx
import { useState } from 'react';
import { NavLink } from 'react-router-dom';
import { buildAtlasLocation } from '@rosettadash/core';
import { DESTINATION_ATLAS_SCREENS, MOCK_DESTINATIONS } from '@destination-atlas';
import { screenAllowedForRole } from './lib/roles';
import { useClientRouterMode } from './lib/client-router';
import { useDestinationAtlasState } from './state/useDestinationAtlasState';
import { AboutScreen, ABOUT_SOURCE } from './screens/AboutScreen';
import { OverviewScreen, OVERVIEW_SOURCE } from './screens/OverviewScreen';
import { DestinationsScreen, DESTINATIONS_SOURCE } from './screens/DestinationsScreen';
import { MapsScreen, MAPS_SOURCE } from './screens/MapsScreen';
import { MediaScreen, MEDIA_SOURCE } from './screens/MediaScreen';
import { AuthoringScreen, AUTHORING_SOURCE } from './screens/AuthoringScreen';
import { IntelScreen, INTEL_SOURCE } from './screens/IntelScreen';
import { PlanScreen, PLAN_SOURCE } from './screens/PlanScreen';
import { ViewsScreen, VIEWS_SOURCE } from './screens/ViewsScreen';
import { StackScreen, STACK_SOURCE } from './screens/StackScreen';
import { SettingsScreen, SETTINGS_SOURCE } from './screens/SettingsScreen';
import { useThemePreference } from './lib/theme';
import type { SettingFieldTarget } from './lib/settings-highlight';
import { ErrorBoundary } from './components/ErrorBoundary';
import {
  ComponentSourcePanel,
  ScreenWorkbenchMobileToggle,
  ScreenWorkbenchPreview,
} from './components/ScreenWorkbench';
import { RouterModeSelect } from './components/RouterModeSelect';
import { AtlasContextSummary } from './components/AtlasContextSummary';

const SCREEN_SOURCES: Record<string, string> = {
  about: ABOUT_SOURCE,
  overview: OVERVIEW_SOURCE,
  destinations: DESTINATIONS_SOURCE,
  maps: MAPS_SOURCE,
  media: MEDIA_SOURCE,
  authoring: AUTHORING_SOURCE,
  intel: INTEL_SOURCE,
  plan: PLAN_SOURCE,
  views: VIEWS_SOURCE,
  stack: STACK_SOURCE,
  settings: SETTINGS_SOURCE,
};

export function App() {
  const initialDestId = MOCK_DESTINATIONS[0]?.id ?? '';
  const atlas = useDestinationAtlasState(initialDestId);
  const { theme, setTheme } = useThemePreference();
  const { routerMode, setRouterMode } = useClientRouterMode();
  const [mobileView, setMobileView] = useState<'preview' | 'source'>('preview');
  const activeScreen = DESTINATION_ATLAS_SCREENS.find((screen) => screen.id === atlas.screen);
  const visibleScreens = DESTINATION_ATLAS_SCREENS.filter((screen) =>
    screenAllowedForRole(screen.id, atlas.userRole),
  );

  const atlasQuery = {
    dest: atlas.selectedId,
    locale: atlas.locale,
    provider: atlas.mapProvider,
    role: atlas.userRole,
  };

  const urlDefaults = {
    dest: initialDestId,
    locale: 'en',
    provider: 'leaflet' as const,
    role: 'viewer' as const,
  };

  const screenTo = (screenId: (typeof visibleScreens)[number]['id']) => {
    const mapsPanel = screenId === 'maps' ? atlas.mapsPanel : 'map';
    const { pathname, search } = buildAtlasLocation(screenId, atlasQuery, urlDefaults, mapsPanel);
    return { pathname, search };
  };

  const openSetting = (field: SettingFieldTarget | 'theme' | 'ai') => {
    atlas.setHighlightTarget(field);
    atlas.setScreen('settings');
  };

  const settingsIndex = visibleScreens.findIndex((screen) => screen.id === 'settings');
  const navScreensBeforeScout = settingsIndex >= 0 ? visibleScreens.slice(0, settingsIndex) : visibleScreens;
  const navScreensFromSettings = settingsIndex >= 0 ? visibleScreens.slice(settingsIndex) : [];

  return (
    <div className="da-shell">
      <header className="da-header">
        <h1>Destination Atlas</h1>
        <p>Current and historic information about world locations — React proof (DAS-137 Scout + Maps)</p>
      </header>

      <div className="da-body-row">
        <div className="da-preview-column">
          <div className="da-context-strip">
            <RouterModeSelect mode={routerMode} onChange={setRouterMode} />
            <AtlasContextSummary
              locale={atlas.locale}
              userRole={atlas.userRole}
              mapProvider={atlas.mapProvider}
              selectedId={atlas.selectedId}
              theme={theme}
              onOpenSetting={openSetting}
            />
          </div>

          <nav className="da-nav da-tabbar" aria-label="Screens">
            {navScreensBeforeScout.map((screen) => (
              <NavLink
                key={screen.id}
                className="da-tabbar__tab"
                to={screenTo(screen.id)}
                aria-current={atlas.screen === screen.id ? 'page' : undefined}
              >
                {screen.label}
              </NavLink>
            ))}
            <button
              type="button"
              className="da-tabbar__tab"
              aria-current={atlas.settingsScoutFocus ? 'page' : undefined}
              onClick={atlas.openScoutSettings}
            >
              Scout
            </button>
            {navScreensFromSettings.map((screen) => (
              <NavLink
                key={screen.id}
                className="da-tabbar__tab"
                to={screenTo(screen.id)}
                aria-current={
                  atlas.screen === screen.id && !atlas.settingsScoutFocus ? 'page' : undefined
                }
              >
                {screen.label}
              </NavLink>
            ))}
          </nav>

          <div className="da-workbench-host">
            <ErrorBoundary label={activeScreen?.label ?? atlas.screen}>
              <ScreenWorkbenchMobileToggle mobileView={mobileView} onChange={setMobileView} />
              <ScreenWorkbenchPreview mobileView={mobileView}>
              {atlas.screen === 'about' ? <AboutScreen /> : null}
              {atlas.screen === 'overview' ? (
                <OverviewScreen locale={atlas.locale} userRole={atlas.userRole} />
              ) : null}
              {atlas.screen === 'destinations' ? (
                <DestinationsScreen
                  locale={atlas.locale}
                  userRole={atlas.userRole}
                  selectedId={atlas.selectedId}
                  setSelectedId={atlas.setSelectedId}
                  destSearch={atlas.destSearch}
                  setDestSearch={atlas.setDestSearch}
                  destRegion={atlas.destRegion}
                  setDestRegion={atlas.setDestRegion}
                  timePreset={atlas.timePreset}
                  setTimePreset={atlas.setTimePreset}
                  visitPeriodStart={atlas.visitPeriodStart}
                  visitPeriodEnd={atlas.visitPeriodEnd}
                  setVisitPeriod={atlas.setVisitPeriod}
                  focusDestinationOnMap={atlas.focusDestinationOnMap}
                />
              ) : null}
              {atlas.screen === 'maps' ? (
                <MapsScreen
                  locale={atlas.locale}
                  selectedId={atlas.selectedId}
                  setSelectedId={atlas.setSelectedId}
                  mapProvider={atlas.mapProvider}
                  setMapProvider={atlas.setMapProvider}
                  mapLocationQuery={atlas.mapLocationQuery}
                  setMapLocationQuery={atlas.setMapLocationQuery}
                  mapViewOverride={atlas.mapViewOverride}
                  focusDestinationOnMap={atlas.focusDestinationOnMap}
                  goToMapView={atlas.goToMapView}
                  setScreen={atlas.setScreen}
                  setHighlightTarget={atlas.setHighlightTarget}
                  mapsPanel={atlas.mapsPanel}
                  setMapsPanel={atlas.setMapsPanel}
                />
              ) : null}
              {atlas.screen === 'media' ? (
                <MediaScreen
                  locale={atlas.locale}
                  selectedId={atlas.selectedId}
                  setSelectedId={atlas.setSelectedId}
                  openAuthoringForDestination={atlas.openAuthoringForDestination}
                />
              ) : null}
              {atlas.screen === 'authoring' ? (
                <AuthoringScreen locale={atlas.locale} selectedId={atlas.selectedId} />
              ) : null}
              {atlas.screen === 'intel' ? (
                <IntelScreen
                  userRole={atlas.userRole}
                  newsQuery={atlas.newsQuery}
                  setNewsQuery={atlas.setNewsQuery}
                  newsRegion={atlas.newsRegion}
                  setNewsRegion={atlas.setNewsRegion}
                  selectedArticleId={atlas.selectedArticleId}
                  setSelectedArticleId={atlas.setSelectedArticleId}
                  setScreen={atlas.setScreen}
                  setHighlightTarget={atlas.setHighlightTarget}
                />
              ) : null}
              {atlas.screen === 'plan' ? <PlanScreen userRole={atlas.userRole} locale={atlas.locale} /> : null}
              {atlas.screen === 'views' ? (
                <ViewsScreen locale={atlas.locale} selectedId={atlas.selectedId} setSelectedId={atlas.setSelectedId} />
              ) : null}
              {atlas.screen === 'stack' ? <StackScreen userRole={atlas.userRole} /> : null}
              {atlas.screen === 'settings' ? (
                <SettingsScreen
                  locale={atlas.locale}
                  userRole={atlas.userRole}
                  setLocale={atlas.setLocale}
                  setUserRole={atlas.setUserRole}
                  mapProvider={atlas.mapProvider}
                  setMapProvider={atlas.setMapProvider}
                  selectedId={atlas.selectedId}
                  setSelectedId={atlas.setSelectedId}
                  highlightTarget={atlas.highlightTarget}
                  setHighlightTarget={atlas.setHighlightTarget}
                  theme={theme}
                  setTheme={setTheme}
                />
              ) : null}
            </ScreenWorkbenchPreview>
            </ErrorBoundary>
          </div>
        </div>
        <ComponentSourcePanel
          source={SCREEN_SOURCES[atlas.screen] ?? ''}
          hidden={mobileView === 'preview'}
        />
      </div>
    </div>
  );
}
