// packages/exporters-react/src/lib/media-component-templates.ts
import { joinLines } from './utils';

/** Inlined into exported React apps (mirrors @rosettadash/core media helpers). */
export function generateEquirectFilterHelperFile(): string {
  return joinLines([
    `export interface EquirectFlatCropOptions {`,
    `  cropX: number;`,
    `  cropY: number;`,
    `  cropWidth: number;`,
    `  cropHeight: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}`,
    ``,
    `export function buildEquirectFlatCropFilter(options: EquirectFlatCropOptions): string {`,
    `  const cropX = Math.max(0, Math.round(options.cropX));`,
    `  const cropY = Math.max(0, Math.round(options.cropY));`,
    `  const cropWidth = Math.max(2, Math.round(options.cropWidth));`,
    `  const cropHeight = Math.max(2, Math.round(options.cropHeight));`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return \`crop=\${cropWidth}:\${cropHeight}:\${cropX}:\${cropY},scale=\${outputWidth}:\${outputHeight}\`;`,
    `}`,
    ``,
    `export function buildEquirectRectilinearFilter(options: {`,
    `  yaw: number;`,
    `  pitch: number;`,
    `  roll?: number;`,
    `  horizontalFov: number;`,
    `  outputWidth: number;`,
    `  outputHeight: number;`,
    `}): string {`,
    `  const yaw = Number(options.yaw) || 0;`,
    `  const pitch = Number(options.pitch) || 0;`,
    `  const roll = Number(options.roll ?? 0) || 0;`,
    `  const horizontalFov = Math.max(1, Number(options.horizontalFov) || 90);`,
    `  const outputWidth = Math.max(2, Math.round(options.outputWidth));`,
    `  const outputHeight = Math.max(2, Math.round(options.outputHeight));`,
    `  return [`,
    `    \`v360=input=equirect:output=rectilinear:yaw=\${yaw}:pitch=\${pitch}:roll=\${roll}:d_fov=\${horizontalFov}\`,`,
    `    \`scale=\${outputWidth}:\${outputHeight}\`,`,
    `  ].join(',');`,
    `}`,
    ``,
    `export function buildEquirectExtractFilter(`,
    `  mode: 'flat-crop' | 'rectilinear',`,
    `  options: EquirectFlatCropOptions & {`,
    `    yaw?: number;`,
    `    pitch?: number;`,
    `    roll?: number;`,
    `    horizontalFov?: number;`,
    `  },`,
    `): string {`,
    `  if (mode === 'rectilinear') {`,
    `    return buildEquirectRectilinearFilter({`,
    `      yaw: options.yaw ?? 0,`,
    `      pitch: options.pitch ?? 0,`,
    `      roll: options.roll ?? 0,`,
    `      horizontalFov: options.horizontalFov ?? 90,`,
    `      outputWidth: options.outputWidth,`,
    `      outputHeight: options.outputHeight,`,
    `    });`,
    `  }`,
    `  return buildEquirectFlatCropFilter(options);`,
    `}`,
    ``,
  ]);
}

export function generateVideoSource(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import { useRef, useState } from 'react';`,
    `import type { Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  accept?: string;`,
    `  url?: string;`,
    `  sourceWidth?: number;`,
    `  sourceHeight?: number;`,
    `  captureBlob?: Blob;`,
    `  onVideoFile?: (file: File) => void;`,
    `  onMetadata?: (row: Row) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Video source',`,
    `  accept = 'video/*',`,
    `  url = '',`,
    `  sourceWidth = 4096,`,
    `  sourceHeight = 2048,`,
    `  captureBlob,`,
    `  onVideoFile,`,
    `  onMetadata,`,
    `}: ${name}Props) {`,
    `  const inputRef = useRef<HTMLInputElement>(null);`,
    `  const [fileName, setFileName] = useState('');`,
    ``,
    `  const emitFile = (file: File) => {`,
    `    setFileName(file.name);`,
    `    onVideoFile?.(file);`,
    `    onMetadata?.({`,
    `      name: file.name,`,
    `      sourceWidth,`,
    `      sourceHeight,`,
    `      size: file.size,`,
    `    });`,
    `  };`,
    ``,
    `  return (`,
    `    <section className="media-source" id={id}>`,
    `      <header className="media-source__header">`,
    `        <h3>{label}</h3>`,
    `        <span>{sourceWidth}×{sourceHeight}</span>`,
    `      </header>`,
    `      <label className="media-source__upload">`,
    `        <input`,
    `          ref={inputRef}`,
    `          type="file"`,
    `          accept={accept}`,
    `          onChange={(event) => {`,
    `            const file = event.target.files?.[0];`,
    `            if (file) emitFile(file);`,
    `          }}`,
    `        />`,
    `        <span>{fileName || 'Choose video file'}</span>`,
    `      </label>`,
    `      {url ? <p className="media-source__url">URL: {url}</p> : null}`,
    `      {captureBlob ? <p className="media-source__capture">Live capture attached</p> : null}`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

export function generateEquirectViewport(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import type { Row } from '../types';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  sourceWidth?: number;`,
    `  sourceHeight?: number;`,
    `  cropX?: number;`,
    `  cropY?: number;`,
    `  cropWidth?: number;`,
    `  cropHeight?: number;`,
    `  outputWidth?: number;`,
    `  outputHeight?: number;`,
    `  onCropRegion?: (region: Row) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Equirect viewport',`,
    `  sourceWidth = 4096,`,
    `  sourceHeight = 2048,`,
    `  cropX = 1508,`,
    `  cropY = 664,`,
    `  cropWidth = 1080,`,
    `  cropHeight = 720,`,
    `  outputWidth = 720,`,
    `  outputHeight = 480,`,
    `  onCropRegion,`,
    `}: ${name}Props) {`,
    `  const cropStyle = {`,
    `    left: \`\${(cropX / sourceWidth) * 100}%\`,`,
    `    top: \`\${(cropY / sourceHeight) * 100}%\`,`,
    `    width: \`\${(cropWidth / sourceWidth) * 100}%\`,`,
    `    height: \`\${(cropHeight / sourceHeight) * 100}%\`,`,
    `  };`,
    ``,
    `  const region = { cropX, cropY, cropWidth, cropHeight, outputWidth, outputHeight };`,
    ``,
    `  return (`,
    `    <section className="media-viewport" id={id}>`,
    `      <header className="media-viewport__header">`,
    `        <h3>{label}</h3>`,
    `        <button type="button" onClick={() => onCropRegion?.(region)}>`,
    `          Emit crop region`,
    `        </button>`,
    `      </header>`,
    `      <div className="media-viewport__frame">`,
    `        <div className="media-viewport__crop" style={cropStyle} />`,
    `      </div>`,
    `      <p className="media-viewport__meta">`,
    `        Crop {cropWidth}×{cropHeight} → Output {outputWidth}×{outputHeight}`,
    `      </p>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

export function generateLiveCapture(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `import { useEffect, useRef, useState } from 'react';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  includeInExport?: boolean;`,
    `  facingMode?: 'user' | 'environment';`,
    `  audio?: boolean;`,
    `  onCaptureBlob?: (blob: Blob) => void;`,
    `  onPreviewUrl?: (url: string) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Live capture',`,
    `  includeInExport = false,`,
    `  facingMode = 'environment',`,
    `  audio = true,`,
    `  onCaptureBlob,`,
    `  onPreviewUrl,`,
    `}: ${name}Props) {`,
    `  const videoRef = useRef<HTMLVideoElement>(null);`,
    `  const [active, setActive] = useState(false);`,
    `  const streamRef = useRef<MediaStream | null>(null);`,
    ``,
    `  useEffect(() => () => {`,
    `    streamRef.current?.getTracks().forEach((track) => track.stop());`,
    `  }, []);`,
    ``,
    `  const startCapture = async () => {`,
    `    const stream = await navigator.mediaDevices.getUserMedia({`,
    `      video: { facingMode },`,
    `      audio,`,
    `    });`,
    `    streamRef.current = stream;`,
    `    if (videoRef.current) {`,
    `      videoRef.current.srcObject = stream;`,
    `      await videoRef.current.play();`,
    `    }`,
    `    setActive(true);`,
    `    onPreviewUrl?.('live');`,
    `  };`,
    ``,
    `  if (!includeInExport) {`,
    `    return (`,
    `      <section className="media-capture media-capture--authoring" id={id}>`,
    `        <p>{label} (authoring only — enable includeInExport for runtime capture)</p>`,
    `      </section>`,
    `    );`,
    `  }`,
    ``,
    `  return (`,
    `    <section className="media-capture" id={id}>`,
    `      <header><h3>{label}</h3></header>`,
    `      <video ref={videoRef} className="media-capture__video" muted playsInline />`,
    `      <button type="button" onClick={() => void startCapture()}>`,
    `        {active ? 'Camera active' : 'Start camera'}`,
    `      </button>`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

export function generateWasmMediaEquirect(name: string): string {
  return joinLines([
    `'use client';`,
    ``,
    `/** Requires: npm install @ffmpeg/ffmpeg @ffmpeg/util */`,
    `import { useCallback, useRef, useState } from 'react';`,
    `import { FFmpeg } from '@ffmpeg/ffmpeg';`,
    `import { fetchFile, toBlobURL } from '@ffmpeg/util';`,
    `import type { Row } from '../types';`,
    `import { buildEquirectExtractFilter } from '../media/equirect-filter';`,
    ``,
    `export interface ${name}Props {`,
    `  id?: string;`,
    `  label?: string;`,
    `  operation?: string;`,
    `  extractionMode?: 'flat-crop' | 'rectilinear';`,
    `  outputFormat?: string;`,
    `  cropX?: number;`,
    `  cropY?: number;`,
    `  cropWidth?: number;`,
    `  cropHeight?: number;`,
    `  outputWidth?: number;`,
    `  outputHeight?: number;`,
    `  yaw?: number;`,
    `  pitch?: number;`,
    `  horizontalFov?: number;`,
    `  showProgress?: boolean;`,
    `  inputFile?: File | Blob;`,
    `  cropRegion?: Row;`,
    `  onOutputBlob?: (blob: Blob) => void;`,
    `  onProgress?: (value: number) => void;`,
    `  onMetadata?: (rows: Row[]) => void;`,
    `}`,
    ``,
    `export function ${name}({`,
    `  id,`,
    `  label = 'Media transcode',`,
    `  operation = 'transcode',`,
    `  extractionMode = 'flat-crop',`,
    `  outputFormat = 'mp4',`,
    `  cropX = 1508,`,
    `  cropY = 664,`,
    `  cropWidth = 1080,`,
    `  cropHeight = 720,`,
    `  outputWidth = 720,`,
    `  outputHeight = 480,`,
    `  yaw = 0,`,
    `  pitch = 0,`,
    `  horizontalFov = 90,`,
    `  showProgress = true,`,
    `  inputFile,`,
    `  cropRegion,`,
    `  onOutputBlob,`,
    `  onProgress,`,
    `  onMetadata,`,
    `}: ${name}Props) {`,
    `  const ffmpegRef = useRef<FFmpeg | null>(null);`,
    `  const [progress, setProgress] = useState(0);`,
    `  const [busy, setBusy] = useState(false);`,
    `  const [error, setError] = useState<string | null>(null);`,
    ``,
    `  const resolveCrop = useCallback(() => ({`,
    `    cropX: Number(cropRegion?.cropX ?? cropX),`,
    `    cropY: Number(cropRegion?.cropY ?? cropY),`,
    `    cropWidth: Number(cropRegion?.cropWidth ?? cropWidth),`,
    `    cropHeight: Number(cropRegion?.cropHeight ?? cropHeight),`,
    `    outputWidth: Number(cropRegion?.outputWidth ?? outputWidth),`,
    `    outputHeight: Number(cropRegion?.outputHeight ?? outputHeight),`,
    `  }), [cropRegion, cropX, cropY, cropWidth, cropHeight, outputWidth, outputHeight]);`,
    ``,
    `  const ensureFfmpeg = useCallback(async () => {`,
    `    if (ffmpegRef.current) return ffmpegRef.current;`,
    `    const ffmpeg = new FFmpeg();`,
    `    ffmpeg.on('progress', ({ progress: ratio }) => {`,
    `      const next = Math.round(ratio * 100);`,
    `      setProgress(next);`,
    `      onProgress?.(next);`,
    `    });`,
    `    const baseURL = 'https://unpkg.com/@ffmpeg/core@0.12.6/dist/umd';`,
    `    await ffmpeg.load({`,
    `      coreURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.js\`, 'text/javascript'),`,
    `      wasmURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.wasm\`, 'application/wasm'),`,
    `    });`,
    `    ffmpegRef.current = ffmpeg;`,
    `    return ffmpeg;`,
    `  }, [onProgress]);`,
    ``,
    `  const runEquirectExtract = useCallback(async () => {`,
    `    if (!inputFile) {`,
    `      setError('Attach a video file before extracting.');`,
    `      return;`,
    `    }`,
    `    setBusy(true);`,
    `    setError(null);`,
    `    try {`,
    `      const ffmpeg = await ensureFfmpeg();`,
    `      const inputName = 'input.mp4';`,
    `      const outputName = \`output.\${outputFormat}\`;`,
    `      await ffmpeg.writeFile(inputName, await fetchFile(inputFile));`,
    `      const crop = resolveCrop();`,
    `      const filter = buildEquirectExtractFilter(extractionMode, {`,
    `        ...crop,`,
    `        yaw,`,
    `        pitch,`,
    `        horizontalFov,`,
    `      });`,
    `      await ffmpeg.exec(['-i', inputName, '-vf', filter, '-c:a', 'copy', outputName]);`,
    `      const data = await ffmpeg.readFile(outputName);`,
    `      const blob = new Blob([data], { type: \`video/\${outputFormat}\` });`,
    `      onOutputBlob?.(blob);`,
    `      onMetadata?.([{`,
    `        filter,`,
    `        outputWidth: crop.outputWidth,`,
    `        outputHeight: crop.outputHeight,`,
    `        format: outputFormat,`,
    `      }]);`,
    `    } catch (nextError) {`,
    `      setError(nextError instanceof Error ? nextError.message : 'Extract failed');`,
    `    } finally {`,
    `      setBusy(false);`,
    `    }`,
    `  }, [`,
    `    ensureFfmpeg,`,
    `    extractionMode,`,
    `    horizontalFov,`,
    `    inputFile,`,
    `    onMetadata,`,
    `    onOutputBlob,`,
    `    onProgress,`,
    `    outputFormat,`,
    `    pitch,`,
    `    resolveCrop,`,
    `    yaw,`,
    `  ]);`,
    ``,
    `  const filterPreview =`,
    `    operation === 'equirect-extract'`,
    `      ? buildEquirectExtractFilter(extractionMode, {`,
    `          ...resolveCrop(),`,
    `          yaw,`,
    `          pitch,`,
    `          horizontalFov,`,
    `        })`,
    `      : '';`,
    ``,
    `  return (`,
    `    <section className="wasm-media" id={id}>`,
    `      <header className="wasm-media__header">`,
    `        <h3>{label}</h3>`,
    `        <span>{operation} → {outputFormat}</span>`,
    `      </header>`,
    `      {filterPreview ? <code className="wasm-media__filter">{filterPreview}</code> : null}`,
    `      {showProgress ? (`,
    `        <div className="wasm-media__progress" role="progressbar" aria-valuenow={progress}>`,
    `          <span style={{ width: \`\${progress}%\` }} />`,
    `        </div>`,
    `      ) : null}`,
    `      {operation === 'equirect-extract' ? (`,
    `        <button type="button" disabled={busy || !inputFile} onClick={() => void runEquirectExtract()}>`,
    `          {busy ? 'Extracting…' : 'Extract subsection'}`,
    `        </button>`,
    `      ) : (`,
    `        <p className="wasm-media__hint">Wire input file and choose equirect-extract operation.</p>`,
    `      )}`,
    `      {error ? <p className="wasm-media__error">{error}</p> : null}`,
    `    </section>`,
    `  );`,
    `}`,
    ``,
  ]);
}

// packages/exporters-web-components/src/lib/media-component-templates.ts
import { joinLines } from './utils';

export function generateVideoSourceStandalone(exportName: string, tag: string): string {
  return joinLines([
    `import { defineRosettaElement } from '../define-element';`,
    ``,
    `const STYLES = \`:host { display: block; font-family: system-ui, sans-serif; }\`;`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${tag}';`,
    `  label = 'Video source';`,
    `  accept = 'video/*';`,
    `  sourceWidth = 4096;`,
    `  sourceHeight = 2048;`,
    ``,
    `  connectedCallback(): void { this.render(); }`,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    `  private render(): void {`,
    `    if (!this.shadowRoot) this.attachShadow({ mode: 'open' });`,
    `    this.shadowRoot!.innerHTML = \`<style>\${STYLES}</style><section><h3>\${this.label}</h3><label><input type="file" accept="\${this.accept}" /><span>Choose video</span></label></section>\`;`,
    `    this.shadowRoot!.querySelector('input')?.addEventListener('change', (event) => {`,
    `      const file = (event.target as HTMLInputElement).files?.[0];`,
    `      if (!file) return;`,
    `      this.dispatchEvent(new CustomEvent('video-file', { detail: { file, metadata: { name: file.name, sourceWidth: this.sourceWidth, sourceHeight: this.sourceHeight, size: file.size } }, bubbles: true, composed: true }));`,
    `    });`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineRosettaElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

export function generateEquirectViewportStandalone(exportName: string, tag: string): string {
  return joinLines([
    `import { buildEquirectExtractFilter } from '@rosettadash/core';`,
    `import { defineRosettaElement } from '../define-element';`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${tag}';`,
    `  label = 'Equirect viewport';`,
    `  previewMode: 'flat-crop' | 'rectilinear' = 'flat-crop';`,
    `  sourceWidth = 4096;`,
    `  sourceHeight = 2048;`,
    `  cropX = 1508;`,
    `  cropY = 664;`,
    `  cropWidth = 1080;`,
    `  cropHeight = 720;`,
    `  outputWidth = 720;`,
    `  outputHeight = 480;`,
    `  yaw = 0;`,
    `  pitch = 0;`,
    `  horizontalFov = 90;`,
    ``,
    `  connectedCallback(): void { this.render(); this.emitCropRegion(); }`,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `    this.emitCropRegion();`,
    `  }`,
    `  private emitCropRegion(): void {`,
    `    const detail = {`,
    `      cropX: this.cropX, cropY: this.cropY, cropWidth: this.cropWidth, cropHeight: this.cropHeight,`,
    `      outputWidth: this.outputWidth, outputHeight: this.outputHeight,`,
    `      yaw: this.yaw, pitch: this.pitch, horizontalFov: this.horizontalFov, previewMode: this.previewMode,`,
    `      filter: buildEquirectExtractFilter(this.previewMode, {`,
    `        cropX: this.cropX, cropY: this.cropY, cropWidth: this.cropWidth, cropHeight: this.cropHeight,`,
    `        outputWidth: this.outputWidth, outputHeight: this.outputHeight,`,
    `        yaw: this.yaw, pitch: this.pitch, horizontalFov: this.horizontalFov,`,
    `      }),`,
    `    };`,
    `    this.dispatchEvent(new CustomEvent('crop-region', { detail, bubbles: true, composed: true }));`,
    `  }`,
    `  private render(): void {`,
    `    if (!this.shadowRoot) this.attachShadow({ mode: 'open' });`,
    `    const left = (this.cropX / this.sourceWidth) * 100;`,
    `    const top = (this.cropY / this.sourceHeight) * 100;`,
    `    const width = (this.cropWidth / this.sourceWidth) * 100;`,
    `    const height = (this.cropHeight / this.sourceHeight) * 100;`,
    `    this.shadowRoot!.innerHTML = \`<style>:host{display:block;font:system-ui,sans-serif}.frame{aspect-ratio:2/1;background:#0f172a;position:relative}.crop{position:absolute;border:2px solid #38bdf8;box-shadow:0 0 0 9999px rgb(15 23 42/55%)}</style><section><h3>\${this.label}</h3>\${this.previewMode === 'flat-crop' ? \`<div class="frame"><div class="crop" style="left:\${left}%;top:\${top}%;width:\${width}%;height:\${height}%"></div></div>\` : \`<p>Rectilinear yaw \${this.yaw}° pitch \${this.pitch}° fov \${this.horizontalFov}°</p>\`}</section>\`;`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineRosettaElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}

export function generateWasmMediaEquirectStandalone(exportName: string, tag: string): string {
  return joinLines([
    `/** Standalone export — install @ffmpeg/ffmpeg @ffmpeg/util for runtime extract. */`,
    `import { buildEquirectExtractFilter } from '@rosettadash/core';`,
    `import { defineRosettaElement } from '../define-element';`,
    ``,
    `export class ${exportName} extends HTMLElement {`,
    `  static readonly tagName = '${tag}';`,
    `  label = 'Media transcode';`,
    `  operation = 'equirect-extract';`,
    `  extractionMode: 'flat-crop' | 'rectilinear' = 'flat-crop';`,
    `  outputFormat = 'mp4';`,
    `  cropX = 1508;`,
    `  cropY = 664;`,
    `  cropWidth = 1080;`,
    `  cropHeight = 720;`,
    `  outputWidth = 720;`,
    `  outputHeight = 480;`,
    `  yaw = 0;`,
    `  pitch = 0;`,
    `  horizontalFov = 90;`,
    `  inputFile: File | Blob | null = null;`,
    `  cropRegion: Record<string, unknown> | null = null;`,
    ``,
    `  connectedCallback(): void { this.render(); }`,
    `  setProperty(name: string, value: unknown): void {`,
    `    (this as Record<string, unknown>)[name] = value;`,
    `    this.render();`,
    `  }`,
    `  private filterPreview(): string {`,
    `    const crop = this.cropRegion ?? { cropX: this.cropX, cropY: this.cropY, cropWidth: this.cropWidth, cropHeight: this.cropHeight, outputWidth: this.outputWidth, outputHeight: this.outputHeight };`,
    `    return buildEquirectExtractFilter(this.extractionMode, { ...crop, yaw: this.yaw, pitch: this.pitch, horizontalFov: this.horizontalFov });`,
    `  }`,
    `  private render(): void {`,
    `    if (!this.shadowRoot) this.attachShadow({ mode: 'open' });`,
    `    this.shadowRoot!.innerHTML = \`<style>:host{display:block;font:system-ui,sans-serif}code{display:block;margin:0.5rem 0;font-size:0.75rem}</style><section><h3>\${this.label}</h3><code>\${this.filterPreview()}</code><button type="button" data-role="extract" \${this.inputFile ? '' : 'disabled'}>Extract subsection</button></section>\`;`,
    `    this.shadowRoot!.querySelector('[data-role="extract"]')?.addEventListener('click', () => void this.runExtract());`,
    `  }`,
    `  private async runExtract(): Promise<void> {`,
    `    if (!this.inputFile) return;`,
    `    const { FFmpeg } = await import('@ffmpeg/ffmpeg');`,
    `    const { fetchFile, toBlobURL } = await import('@ffmpeg/util');`,
    `    const ffmpeg = new FFmpeg();`,
    `    const baseURL = 'https://unpkg.com/@ffmpeg/core@0.12.6/dist/umd';`,
    `    await ffmpeg.load({ coreURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.js\`, 'text/javascript'), wasmURL: await toBlobURL(\`\${baseURL}/ffmpeg-core.wasm\`, 'application/wasm') });`,
    `    const filter = this.filterPreview();`,
    `    await ffmpeg.writeFile('input.mp4', await fetchFile(this.inputFile));`,
    `    await ffmpeg.exec(['-i', 'input.mp4', '-vf', filter, '-c:a', 'copy', 'output.mp4']);`,
    `    const data = await ffmpeg.readFile('output.mp4');`,
    `    const blob = new Blob([data], { type: 'video/mp4' });`,
    `    this.dispatchEvent(new CustomEvent('extract-complete', { detail: { blob, metadata: { filter } }, bubbles: true, composed: true }));`,
    `  }`,
    `}`,
    ``,
    `export function register${exportName}(): void {`,
    `  defineRosettaElement(${exportName}.tagName, ${exportName});`,
    `}`,
    ``,
  ]);
}
