// packages/svelte/src/layout/flex/FlexLayout.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { FlexLayoutProps } from './types';

	type Props = FlexLayoutProps & { children?: Snippet };

	let {
		className,
		title,
		direction,
		gap,
		children,
	}: Props = $props();
	const flexGap = $derived(typeof gap === 'number' ? gap : 12);
	const rootClass = $derived(['rd-flex', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-flex">
	{#if title}<span class="rd-flex__title">{title}</span>{/if}
	<div class="rd-flex__flex" style:flex-direction={direction ?? 'row'} style:gap="{flexGap}px">{@render children?.()}</div>
</section>

// packages/react/src/layout/flex/FlexLayout.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface FlexLayoutProps {
  title?: string;
  direction?: 'row' | 'column';
  gap?: number | string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/layout/flex — layout.flex */
export const FlexLayout = forwardRef<HTMLElement, FlexLayoutProps>(function FlexLayout(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-flex', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-flex">
      {props.title ? <span className="rd-flex__title">{props.title}</span> : null}
      <div className="rd-flex__flex" style={{ flexDirection: props.direction ?? 'row', gap: props.gap ?? 12 }}>{children}</div>
    </section>
  );
});
