// packages/angular/src/layout/accordion/accordion.ts
import { NgClass } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
  OnInit,
  output,
  signal,
} from '@angular/core';

/** Public props contract for layout/accordion (parity with other runtimes). */
export interface AccordionProps {
  title: string;
  open?: boolean;
  defaultOpen?: boolean;
  className?: string;
}

@Component({
  selector: 'rd-accordion',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section data-testid="rd-accordion" [ngClass]="rootClass()">
      <button
        type="button"
        class="rd-accordion__header"
        [attr.aria-expanded]="isOpen()"
        aria-controls="rd-accordion-panel"
        (click)="toggle()"
      >
        <span class="rd-accordion__title">{{ title() }}</span>
        <span class="rd-accordion__chevron" aria-hidden="true">›</span>
      </button>
      @if (isOpen()) {
        <div class="rd-accordion__panel" id="rd-accordion-panel" role="region">
          <ng-content />
        </div>
      }
    </section>
  `,
})
export class Accordion implements OnInit {
  readonly title = input.required<string>();
  /** Controlled open — use with `[(open)]`. */
  readonly open = input<boolean | undefined>(undefined);
  readonly defaultOpen = input(false);
  readonly className = input<string | undefined>(undefined);

  readonly openChange = output<boolean>();
  readonly toggleChange = output<boolean>();

  private readonly uncontrolledOpen = signal(false);

  readonly isOpen = computed(() => {
    const controlled = this.open();
    return controlled !== undefined ? controlled : this.uncontrolledOpen();
  });

  readonly rootClass = computed(() =>
    ['rd-accordion', this.isOpen() ? 'rd-accordion--open' : '', this.className()]
      .filter(Boolean)
      .join(' '),
  );

  ngOnInit(): void {
    this.uncontrolledOpen.set(this.defaultOpen());
  }

  toggle(): void {
    const next = !this.isOpen();
    if (this.open() === undefined) {
      this.uncontrolledOpen.set(next);
    }
    this.openChange.emit(next);
    this.toggleChange.emit(next);
  }
}

// packages/react/src/layout/accordion/Accordion.tsx
import {
  useId,
  useState,
  type CSSProperties,
  type ReactNode,
} from 'react';

/** Public props contract for layout/accordion (parity with web-components). */
export interface AccordionProps {
  title: string;
  /** Controlled open state. When set, pair with `onOpenChange`. */
  open?: boolean;
  defaultOpen?: boolean;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
  onOpenChange?: (open: boolean) => void;
  /** @deprecated Prefer `onOpenChange` — still emitted for compatibility. */
  onToggle?: (open: boolean) => void;
}

export function Accordion({
  title,
  open: openProp,
  defaultOpen = false,
  className,
  style,
  children,
  onOpenChange,
  onToggle,
}: AccordionProps) {
  const [uncontrolledOpen, setUncontrolledOpen] = useState(defaultOpen);
  const isControlled = openProp !== undefined;
  const open = isControlled ? Boolean(openProp) : uncontrolledOpen;
  const panelId = useId();

  function setOpen(next: boolean): void {
    if (!isControlled) {
      setUncontrolledOpen(next);
    }
    onOpenChange?.(next);
    onToggle?.(next);
  }

  function toggle(): void {
    setOpen(!open);
  }

  const rootClass = ['rd-accordion', open ? 'rd-accordion--open' : '', className]
    .filter(Boolean)
    .join(' ');

  return (
    <section className={rootClass} style={style} data-testid="rd-accordion">
      <button
        type="button"
        className="rd-accordion__header"
        aria-expanded={open}
        aria-controls={panelId}
        onClick={toggle}
      >
        <span className="rd-accordion__title">{title}</span>
        <span className="rd-accordion__chevron" aria-hidden="true">
          ›
        </span>
      </button>
      {open ? (
        <div className="rd-accordion__panel" id={panelId} role="region">
          {children}
        </div>
      ) : null}
    </section>
  );
}
