// packages/angular/src/visual/wasm/worker-host/wasm-worker-host.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface WasmWorkerHostProps {
  workerLabel?: string;
  workerStatus?: string;
  className?: string;
}

/** @rosettadash/angular/visual/wasm/worker-host — visual.wasm.worker-host */
@Component({
  selector: 'rd-wasm-worker-host',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-wasm-worker-host'" [ngClass]="rootClass()">
      <span class="rd-wasm__label">{{ workerLabel() ?? 'Worker' }}</span>
      <span class="rd-wasm__status">{{ workerStatus() ?? 'Idle' }}</span>
      <ng-content />
    </section>
  `,
})
export class WasmWorkerHost {
  readonly className = input<string | undefined>(undefined);
  readonly workerLabel = input<string | undefined>(undefined);
  readonly workerStatus = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-wasm-worker-host', this.className()].filter(Boolean).join(' '),
  );
}

// packages/react/src/visual/wasm/worker-host/WasmWorkerHost.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface WasmWorkerHostProps {
  workerLabel?: string;
  workerStatus?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/wasm/worker-host — visual.wasm.worker-host */
export const WasmWorkerHost = forwardRef<HTMLElement, WasmWorkerHostProps>(function WasmWorkerHost(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-wasm-worker-host', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-wasm-worker-host">
      <span className="rd-wasm__label">{props.workerLabel ?? 'Worker'}</span>
      <span className="rd-wasm__status">{props.workerStatus ?? 'Idle'}</span>
      {children}
    </section>
  );
});
