// packages/angular/src/visual/link-list/link-list.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

/** Single link item for visual/link-list. */
export interface LinkListItem {
  label: string;
  href: string;
}

/** Public props contract for visual/link-list. */
export interface LinkListProps {
  items?: LinkListItem[];
  className?: string;
  dense?: boolean;
}

@Component({
  selector: 'rd-link-list',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <ul data-testid="rd-link-list" [ngClass]="rootClass()">
      @for (item of items(); track item.href + ':' + item.label) {
        <li class="rd-link-list__item">
          <a class="rd-link-list__link" [href]="item.href">{{ item.label }}</a>
        </li>
      }
    </ul>
  `,
})
export class LinkList {
  readonly items = input<LinkListItem[]>([]);
  readonly className = input<string | undefined>(undefined);
  readonly dense = input(false);

  readonly rootClass = computed(() =>
    [
      'rd-link-list',
      this.dense() ? 'rd-link-list--dense' : '',
      this.className(),
    ]
      .filter(Boolean)
      .join(' '),
  );
}

// packages/react/src/visual/link-list/LinkList.tsx
import type { CSSProperties } from 'react';

/** Single link item for visual/link-list. */
export interface LinkListItem {
  label: string;
  href: string;
}

/** Public props contract for visual/link-list (parity with web-components). */
export interface LinkListProps {
  items?: LinkListItem[];
  className?: string;
  dense?: boolean;
  style?: CSSProperties;
}

export function LinkList({
  items = [],
  className,
  dense = false,
  style,
}: LinkListProps) {
  const rootClass = [
    'rd-link-list',
    dense ? 'rd-link-list--dense' : '',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <ul className={rootClass} style={style} data-testid="rd-link-list">
      {items.map((item) => (
        <li
          className="rd-link-list__item"
          key={`${item.href}:${item.label}`}
        >
          <a className="rd-link-list__link" href={item.href}>
            {item.label}
          </a>
        </li>
      ))}
    </ul>
  );
}
