// packages/angular/src/visual/input/select/select-input.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface SelectInputOption {
  value: string;
  label: string;
}

export interface SelectInputProps {
  label?: string;
  placeholder?: string;
  options?: SelectInputOption[];
  value?: string;
  onChange?: (value: string) => void;
  className?: string;
}

/** @rosettadash/angular/visual/input/select — visual.input.select */
@Component({
  selector: 'rd-input-select',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-input-select'" [ngClass]="rootClass()">
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      <select class="rd-select" [value]="value() ?? ''">
        <option value="">{{ placeholder() ?? 'Select…' }}</option>
        @for (o of options() ?? []; track o.value) {
          <option [value]="o.value">{{ o.label }}</option>
        }
      </select>
      <ng-content />
    </section>
  `,
})
export class SelectInput {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly placeholder = input<string | undefined>(undefined);
  readonly options = input<SelectInputOption[] | undefined>(undefined);
  readonly value = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-input-select', this.className()].filter(Boolean).join(' '),
  );
}

// packages/react/src/visual/input/select/SelectInput.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface SelectInputOption {
  value: string;
  label: string;
}

export interface SelectInputProps {
  label?: string;
  placeholder?: string;
  options?: SelectInputOption[];
  value?: string;
  onChange?: (value: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/input/select — visual.input.select */
export const SelectInput = forwardRef<HTMLElement, SelectInputProps>(function SelectInput(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-input-select', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-input-select">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <select
        className="rd-select"
        value={props.value}
        onChange={(e) => props.onChange?.(e.target.value)}
      >
        <option value="">{props.placeholder ?? 'Select…'}</option>
        {(props.options ?? []).map((o) => (
          <option key={o.value} value={o.value}>{o.label}</option>
        ))}
      </select>
      {children}
    </section>
  );
});
