// apps/proof-vue/src/authoring/AuthoringScreen.tsx
import { useEffect, useMemo, useRef, useState } from 'react';
import {
  AUTHORING_OUTPUT_CUSTOM_ID,
  AUTHORING_OUTPUT_PRESETS,
  centerCropForOutput,
  flatCropToCropRegion,
  getAuthoringOutputPreset,
  isEquirectSourceDimensions,
  authoringExtractDownloadName,
  type AuthoringRecordRange,
  virtualCameraToCropRegion,
} from '@rosettadash/core';
import {
  EquirectSphereViewport,
} from '@rosettadash/react/visual/media/equirect-sphere-viewport';
import {
  FlatVideoViewport,
} from '@rosettadash/react/visual/media/flat-video-viewport';
import { WasmMedia } from '@rosettadash/react/visual/wasm/media';
import { NumberInput } from '@rosettadash/react/visual/input/number';
import { SelectInput } from '@rosettadash/react/visual/input/select';
import {
  DEFAULT_AUTHORING_EXAMPLE_ID,
  DESTINATION_ATLAS_AUTHORING_EXAMPLES,
  getAuthoringExampleById,
  getAuthoringExampleForDestinationId,
  getDestinationById,
} from '@destination-atlas';
import { AuthoringPlaybackBar } from './AuthoringPlaybackBar';
import { PlaybackReverseIcon } from './authoring-playback-icons';
import { AuthoringCameraControls, LITTLE_PLANET_HFOV, LITTLE_PLANET_PITCH } from './AuthoringCameraControls';
import { localizedDestinationName } from '../lib/atlas-utils';
import type { AuthoringViewportHandle } from '../lib/authoring-viewport';

export const AUTHORING_SOURCE = `<AuthoringScreen>
  <VideoSource onVideoFile={…} />
  <EquirectSphereViewport videoSrc={sourceUrl} yaw={…} pitch={…} />
  <WasmMedia operation="equirect-extract" inputFile={inputFile} />
</AuthoringScreen>`;

type CropRegion = Record<string, string | number | boolean | null | undefined>;

function probeVideoFile(file: File): Promise<{ width: number; height: number }> {
  return new Promise((resolve) => {
    const url = URL.createObjectURL(file);
    const video = document.createElement('video');
    video.preload = 'metadata';
    video.onloadedmetadata = () => {
      resolve({ width: video.videoWidth, height: video.videoHeight });
      URL.revokeObjectURL(url);
    };
    video.onerror = () => {
      URL.revokeObjectURL(url);
      resolve({ width: 0, height: 0 });
    };
    video.src = url;
  });
}

function matchOutputPreset(width: number, height: number): string {
  const match = AUTHORING_OUTPUT_PRESETS.find((entry) => entry.width === width && entry.height === height);
  return match?.id ?? AUTHORING_OUTPUT_CUSTOM_ID;
}

function evenDimension(value: number): number {
  const rounded = Math.max(2, Math.round(value));
  return rounded % 2 === 0 ? rounded : rounded - 1;
}

export function AuthoringScreen({
  locale = 'en',
  selectedId,
}: {
  locale?: string;
  selectedId?: string;
}) {
  const [exampleId, setExampleId] = useState(DEFAULT_AUTHORING_EXAMPLE_ID);
  const [inputFile, setInputFile] = useState<File | null>(null);
  const [sourceUrl, setSourceUrl] = useState<string | null>(null);
  const [sourceLoadBusy, setSourceLoadBusy] = useState(false);
  const [sourceLoadError, setSourceLoadError] = useState<string | null>(null);
  const [cropRegion, setCropRegion] = useState<CropRegion | null>(null);
  const [extractUrl, setExtractUrl] = useState<string | null>(null);
  const [extractFilter, setExtractFilter] = useState('');
  const [extractProgress, setExtractProgress] = useState(0);
  const [extractError, setExtractError] = useState<string | null>(null);
  const [extractBusy, setExtractBusy] = useState(false);

  const example = getAuthoringExampleById(exampleId) ?? DESTINATION_ATLAS_AUTHORING_EXAMPLES[0];
  const destination = example ? getDestinationById(example.destinationId) : undefined;

  const [yaw, setYaw] = useState(example?.defaultYaw ?? 25);
  const [pitch, setPitch] = useState(example?.defaultPitch ?? -8);
  const [horizontalFov, setHorizontalFov] = useState(example?.defaultHorizontalFov ?? 75);
  const [outputWidth, setOutputWidth] = useState(720);
  const [outputHeight, setOutputHeight] = useState(480);
  const [outputPresetId, setOutputPresetId] = useState('720x480');
  const [reverse, setReverse] = useState(false);
  const [sourceWidth, setSourceWidth] = useState<number | undefined>();
  const [sourceHeight, setSourceHeight] = useState<number | undefined>();
  const [cropX, setCropX] = useState(0);
  const [cropY, setCropY] = useState(0);
  const [cropWidth, setCropWidth] = useState(640);
  const [cropHeight, setCropHeight] = useState(360);
  const [recordRange, setRecordRange] = useState<AuthoringRecordRange | null>(null);

  const outputPreviewHostRef = useRef<HTMLDivElement>(null);
  const viewportRef = useRef<AuthoringViewportHandle>(null);
  const userPickedFileRef = useRef(false);

  const sourceReady = Boolean(sourceUrl && sourceWidth && sourceHeight && !sourceLoadBusy);

  const isEquirectSource = useMemo(
    () => sourceReady && sourceWidth && sourceHeight && isEquirectSourceDimensions(sourceWidth, sourceHeight),
    [sourceReady, sourceWidth, sourceHeight],
  );
  const sourceModeLabel = isEquirectSource
    ? '360° equirectangular — camera framing controls'
    : 'Flat video — drag the crop rectangle on source';
  const isCustomOutput = outputPresetId === AUTHORING_OUTPUT_CUSTOM_ID;
  const sourceAspect =
    sourceWidth && sourceHeight && sourceHeight > 0 ? sourceWidth / sourceHeight : null;
  const equirectAspectWarning =
    isEquirectSource && sourceAspect !== null && Math.abs(sourceAspect - 2) > 0.05;

  useEffect(() => {
    if (!selectedId) {
      return;
    }
    const linkedExample = getAuthoringExampleForDestinationId(selectedId);
    if (linkedExample) {
      setExampleId(linkedExample.id);
    }
  }, [selectedId]);

  useEffect(() => {
    userPickedFileRef.current = false;
  }, [selectedId, exampleId]);

  useEffect(() => {
    if (!inputFile || (sourceWidth && sourceHeight)) {
      return;
    }
    void probeVideoFile(inputFile).then(({ width, height }) => {
      if (width > 0 && height > 0) {
        setSourceWidth(width);
        setSourceHeight(height);
      }
    });
  }, [inputFile, sourceWidth, sourceHeight]);

  useEffect(() => {
    if (!example) {
      return;
    }
    if (userPickedFileRef.current) {
      return;
    }
    setYaw(example.defaultYaw);
    setPitch(example.defaultPitch);
    setHorizontalFov(example.defaultHorizontalFov);
    const preset = getAuthoringOutputPreset('720x480');
    setOutputPresetId('720x480');
    setOutputWidth(preset?.width ?? 720);
    setOutputHeight(preset?.height ?? 480);
    setSourceWidth(undefined);
    setSourceHeight(undefined);
    setRecordRange(null);
    setCropRegion(null);
    setExtractFilter('');
    setExtractProgress(0);
    setExtractError(null);
    setExtractBusy(false);
    setInputFile(null);
    setSourceUrl(null);
    setSourceLoadBusy(false);
    setSourceLoadError(null);
    setExtractUrl((previous) => {
      if (previous) {
        URL.revokeObjectURL(previous);
      }
      return null;
    });
  }, [exampleId, example]);

  useEffect(() => {
    if (!inputFile) {
      return;
    }
    const url = URL.createObjectURL(inputFile);
    setSourceUrl(url);
    return () => {
      URL.revokeObjectURL(url);
    };
  }, [inputFile]);

  useEffect(
    () => () => {
      if (extractUrl) {
        URL.revokeObjectURL(extractUrl);
      }
    },
    [extractUrl],
  );

  useEffect(() => {
    if (!sourceWidth || !sourceHeight || isEquirectSource || outputPresetId === AUTHORING_OUTPUT_CUSTOM_ID) {
      return;
    }
    const centered = centerCropForOutput(sourceWidth, sourceHeight, outputWidth, outputHeight);
    setCropX(centered.cropX);
    setCropY(centered.cropY);
    setCropWidth(centered.cropWidth);
    setCropHeight(centered.cropHeight);
  }, [sourceWidth, sourceHeight, outputWidth, outputHeight, outputPresetId, isEquirectSource]);

  useEffect(() => {
    if (isEquirectSource) {
      setCropRegion(
        virtualCameraToCropRegion({
          camera: { yaw, pitch, roll: 0, fov: horizontalFov },
          sourceWidth,
          sourceHeight,
          outputWidth,
          outputHeight,
          reverse,
        }),
      );
      const filter = virtualCameraToCropRegion({
        camera: { yaw, pitch, roll: 0, fov: horizontalFov },
        sourceWidth,
        sourceHeight,
        outputWidth,
        outputHeight,
        reverse,
      }).filter;
      setExtractFilter(typeof filter === 'string' ? filter : '');
      return;
    }
    if (!sourceWidth || !sourceHeight) {
      setCropRegion(null);
      setExtractFilter('');
      return;
    }
    const region = flatCropToCropRegion({
      cropX,
      cropY,
      cropWidth,
      cropHeight,
      sourceWidth,
      sourceHeight,
      outputWidth,
      outputHeight,
      reverse,
    });
    setCropRegion(region);
    setExtractFilter(region.filter);
  }, [
    isEquirectSource,
    yaw,
    pitch,
    horizontalFov,
    cropX,
    cropY,
    cropWidth,
    cropHeight,
    outputWidth,
    outputHeight,
    sourceWidth,
    sourceHeight,
    reverse,
  ]);

  const exampleLabel = useMemo(() => {
    if (!example || !destination) {
      return example?.label ?? 'Authoring example';
    }
    return `${example.label} · ${localizedDestinationName(destination, locale)}`;
  }, [destination, example, locale]);

  const handleOutputPresetChange = (presetId: string) => {
    setOutputPresetId(presetId);
    if (presetId === AUTHORING_OUTPUT_CUSTOM_ID) {
      return;
    }
    const preset = getAuthoringOutputPreset(presetId);
    if (preset) {
      setOutputWidth(preset.width);
      setOutputHeight(preset.height);
    }
  };

  const handleCustomDimensionChange = (width: number, height: number) => {
    setOutputWidth(width);
    setOutputHeight(height);
    setOutputPresetId(matchOutputPreset(width, height));
  };

  const handleVideoFile = (detail: {
    file: File;
    metadata: Record<string, string | number | boolean | null | undefined>;
  }) => {
    userPickedFileRef.current = true;
    setSourceLoadBusy(false);
    setSourceLoadError(null);
    setRecordRange(null);
    setInputFile(detail.file);
    if (example) {
      setYaw(example.defaultYaw);
      setPitch(example.defaultPitch);
      setHorizontalFov(example.defaultHorizontalFov);
    }
    const width = Number(detail.metadata.sourceWidth);
    const height = Number(detail.metadata.sourceHeight);
    if (Number.isFinite(width) && width > 0 && Number.isFinite(height) && height > 0) {
      setSourceWidth(width);
      setSourceHeight(height);
    } else {
      setSourceWidth(undefined);
      setSourceHeight(undefined);
    }
    setExtractUrl((previous) => {
      if (previous) {
        URL.revokeObjectURL(previous);
      }
      return null;
    });
    setExtractProgress(0);
    setExtractError(null);
    setExtractBusy(false);
  };

  const handleFlatCropChange = (detail: {
    cropX: number;
    cropY: number;
    cropWidth: number;
    cropHeight: number;
  }) => {
    setCropX(detail.cropX);
    setCropY(detail.cropY);
    setCropWidth(detail.cropWidth);
    setCropHeight(detail.cropHeight);
    setOutputWidth(evenDimension(detail.cropWidth));
    setOutputHeight(evenDimension(detail.cropHeight));
    setOutputPresetId(AUTHORING_OUTPUT_CUSTOM_ID);
  };

  const updateFlatCrop = (partial: Partial<{ cropX: number; cropY: number; cropWidth: number; cropHeight: number }>) => {
    handleFlatCropChange({
      cropX: partial.cropX ?? cropX,
      cropY: partial.cropY ?? cropY,
      cropWidth: partial.cropWidth ?? cropWidth,
      cropHeight: partial.cropHeight ?? cropHeight,
    });
  };

  const onAuthoringFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    event.target.value = '';
    if (!file) {
      return;
    }
    void probeVideoFile(file).then(({ width, height }) => {
      handleVideoFile({
        file,
        metadata: {
          name: file.name,
          sourceWidth: width > 0 ? width : undefined,
          sourceHeight: height > 0 ? height : undefined,
          size: file.size,
        },
      });
    });
  };

  return (
    <section className="da-panel da-panel--authoring">
      <h2>Authoring</h2>

      <div className="da-authoring-workspace">
        <header className="da-authoring-workspace__headers">
          <h3 className="da-authoring-pane__title">Source</h3>
          <h3 className="da-authoring-pane__title">Output</h3>
        </header>

        <div className="da-authoring-workspace__videos">
          <div className="da-authoring-workspace__video-col da-authoring-workspace__video-col--source">
            {sourceUrl ? (
              <div className="da-authoring-source-toolbar">
                <label className="da-authoring-change-file">
                  <input
                    type="file"
                    className="da-authoring-choose-file__input"
                    accept="video/*"
                    onChange={onAuthoringFileChange}
                  />
                  Change video file
                </label>
              </div>
            ) : null}
            {sourceUrl && isEquirectSource ? (
              <EquirectSphereViewport
                ref={viewportRef}
                className="da-authoring-sphere-viewport"
                videoSrc={sourceUrl}
                flipInterior
                yaw={yaw}
                pitch={pitch}
                horizontalFov={horizontalFov}
                outputWidth={outputWidth}
                outputHeight={outputHeight}
                outputPreviewHostRef={outputPreviewHostRef}
                onCameraChange={({ yaw: nextYaw, pitch: nextPitch, horizontalFov: nextFov }) => {
                  setYaw(nextYaw);
                  setPitch(nextPitch);
                  setHorizontalFov(nextFov);
                }}
              />
            ) : sourceUrl && sourceWidth && sourceHeight ? (
              <FlatVideoViewport
                ref={viewportRef}
                className="da-authoring-flat-viewport"
                videoSrc={sourceUrl}
                sourceWidth={sourceWidth}
                sourceHeight={sourceHeight}
                cropX={cropX}
                cropY={cropY}
                cropWidth={cropWidth}
                cropHeight={cropHeight}
                outputWidth={outputWidth}
                outputHeight={outputHeight}
                outputPreviewHostRef={outputPreviewHostRef}
                onCropChange={handleFlatCropChange}
              />
            ) : sourceUrl && !sourceReady ? (
              <div
                className="da-authoring-sphere-viewport da-authoring-sphere-viewport--placeholder"
                aria-busy="true"
                aria-label="Reading source video"
              />
            ) : sourceLoadBusy ? (
              <div
                className="da-authoring-sphere-viewport da-authoring-sphere-viewport--placeholder"
                aria-busy="true"
                aria-label="Loading source video"
              />
            ) : (
              <div className="da-authoring-sphere-viewport da-authoring-sphere-viewport--placeholder">
                <label className="da-authoring-choose-file">
                  <input
                    type="file"
                    className="da-authoring-choose-file__input"
                    accept="video/*"
                    onChange={onAuthoringFileChange}
                  />
                  Choose video file
                </label>
              </div>
            )}
          </div>

          <div className="da-authoring-workspace__video-col">
            {sourceUrl ? (
              <div ref={outputPreviewHostRef} className="da-authoring-program-preview-host" />
            ) : (
              <div className="da-authoring-program-preview-host da-authoring-program-preview-host--placeholder">
                <p className="da-authoring-output-placeholder">Choose source file to create output</p>
              </div>
            )}
          </div>
        </div>

        <div className="da-authoring-workspace__footers">
          <div className="da-authoring-pane da-authoring-pane--source" aria-label="Authoring source controls">
            {!sourceUrl && !sourceLoadBusy ? (
              <p className="da-note da-authoring-controls-placeholder">
                Choose a source video to show playback and framing controls.
              </p>
            ) : !sourceReady ? (
              <p className="da-note da-authoring-controls-placeholder" aria-busy="true">
                Loading source video…
              </p>
            ) : (
              <>
                <p className="da-note da-authoring-source-mode">{sourceModeLabel}</p>
                <AuthoringPlaybackBar
                  viewportRef={viewportRef}
                  disabled={false}
                  recordRange={recordRange}
                  onRecordRangeChange={setRecordRange}
                  hint={
                    isEquirectSource
                      ? 'Drag on the sphere or use Camera framing sliders · FOV above 130° enters little-planet'
                      : 'Drag the crop rectangle · corner handles set a custom output size · presets snap to standard dimensions'
                  }
                  onResetView={() => {
                    if (!example) {
                      return;
                    }
                    if (isEquirectSource) {
                      setYaw(example.defaultYaw);
                      setPitch(example.defaultPitch);
                      setHorizontalFov(example.defaultHorizontalFov);
                      return;
                    }
                    if (sourceWidth && sourceHeight) {
                      const centered = centerCropForOutput(sourceWidth, sourceHeight, outputWidth, outputHeight);
                      setCropX(centered.cropX);
                      setCropY(centered.cropY);
                      setCropWidth(centered.cropWidth);
                      setCropHeight(centered.cropHeight);
                    }
                  }}
                />
                {isEquirectSource ? (
                  <AuthoringCameraControls
                    yaw={yaw}
                    pitch={pitch}
                    horizontalFov={horizontalFov}
                    disabled={false}
                    onYawChange={setYaw}
                    onPitchChange={setPitch}
                    onHorizontalFovChange={setHorizontalFov}
                    onReset={() => {
                      if (!example) {
                        return;
                      }
                      setYaw(example.defaultYaw);
                      setPitch(example.defaultPitch);
                      setHorizontalFov(example.defaultHorizontalFov);
                    }}
                    onLittlePlanetPreset={() => {
                      setHorizontalFov(LITTLE_PLANET_HFOV);
                      setPitch(LITTLE_PLANET_PITCH);
                    }}
                  />
                ) : (
                  <div className="da-authoring-crop-controls" aria-label="Crop region controls">
                    <h4 className="da-authoring-crop-controls__title">Crop region</h4>
                    <p className="da-note da-authoring-crop-controls__hint">
                      Drag corners for any output size (updates export dimensions live). Pick a preset to snap to
                      320×240, 640×360, or 720×480.
                    </p>
                    <div className="da-authoring-crop-controls__grid">
                      <NumberInput label="Crop X" value={cropX} step={1} min={0} max={sourceWidth ?? 99999} onChange={(value) => updateFlatCrop({ cropX: value })} />
                      <NumberInput label="Crop Y" value={cropY} step={1} min={0} max={sourceHeight ?? 99999} onChange={(value) => updateFlatCrop({ cropY: value })} />
                      <NumberInput label="Crop width" value={cropWidth} step={2} min={2} max={sourceWidth ?? 99999} onChange={(value) => updateFlatCrop({ cropWidth: value })} />
                      <NumberInput
                        label="Crop height"
                        value={cropHeight}
                        step={2}
                        min={2}
                        max={sourceHeight ?? 99999}
                        onChange={(value) => updateFlatCrop({ cropHeight: value })}
                      />
                    </div>
                  </div>
                )}
              </>
            )}
          </div>

          <div className="da-authoring-pane da-authoring-pane--output" aria-label="Authoring output controls">
            {!sourceReady ? (
              <p className="da-note da-authoring-controls-placeholder">
                Output and export settings appear after you load a source video.
              </p>
            ) : (
              <>
            <p className="da-note">Same view as source — live mirror scaled to export dimensions.</p>

            {sourceWidth && sourceHeight ? (
              <p className={`da-note${equirectAspectWarning ? ' da-note--warn' : ''}`}>
                Source dimensions: {sourceWidth}×{sourceHeight} ({sourceAspect?.toFixed(2)}:1)
                {isEquirectSource ? ' — interior view flips texture for inside-out viewing' : ''}
                {equirectAspectWarning ? ' · aspect ratio differs from 2:1; extract may look wrong' : ''}
              </p>
            ) : null}

            <div className="da-media-extract-controls">
              <div className="da-media-extract-size-row">
                <SelectInput
                  label="Export rectangle size"
                  className="da-media-extract-size-row__preset"
                  value={outputPresetId}
                  options={[
                    ...AUTHORING_OUTPUT_PRESETS.map((entry) => ({ value: entry.id, label: entry.label })),
                    { value: AUTHORING_OUTPUT_CUSTOM_ID, label: 'Custom' },
                  ]}
                  onChange={handleOutputPresetChange}
                />
                <NumberInput
                  label="W"
                  className="da-media-extract-size-row__dim"
                  value={outputWidth}
                  step={2}
                  min={160}
                  max={3840}
                  disabled={!isCustomOutput}
                  onChange={(value) => isCustomOutput && handleCustomDimensionChange(value, outputHeight)}
                />
                <span className="da-media-extract-size-row__sep" aria-hidden="true">
                  ×
                </span>
                <NumberInput
                  label="H"
                  className="da-media-extract-size-row__dim"
                  value={outputHeight}
                  step={2}
                  min={120}
                  max={2160}
                  disabled={!isCustomOutput}
                  onChange={(value) => isCustomOutput && handleCustomDimensionChange(outputWidth, value)}
                />
                <button
                  type="button"
                  className={`da-media-extract-size-row__reverse${reverse ? ' is-active' : ''}`}
                  aria-label="Reverse playback"
                  aria-pressed={reverse}
                  onClick={() => setReverse((previous) => !previous)}
                >
                  <PlaybackReverseIcon />
                </button>
              </div>
              {isEquirectSource ? (
                <div className="da-media-extract-controls__camera">
                  <NumberInput
                    label="Yaw (°)"
                    value={yaw}
                    step={0.5}
                    min={-180}
                    max={180}
                    onChange={setYaw}
                  />
                  <NumberInput
                    label="Pitch (°)"
                    value={pitch}
                    step={0.5}
                    min={-85}
                    max={85}
                    onChange={setPitch}
                  />
                  <NumberInput
                    label="Horizontal FOV (°)"
                    value={horizontalFov}
                    step={1}
                    min={30}
                    max={360}
                    onChange={setHorizontalFov}
                  />
                </div>
              ) : null}
            </div>

            {extractFilter ? (
              <p className="da-note da-note--filter">
                Filter:{' '}
                <code className="da-value-ellipsis" tabIndex={0}>
                  {extractFilter}
                </code>
              </p>
            ) : null}

            {inputFile ? (
              <>
                {!recordRange ? (
                  <p className="da-note">Record a segment on the playback bar, then extract that subsection.</p>
                ) : null}
                <WasmMedia
                  label="ffmpeg.wasm extract"
                  operation="equirect-extract"
                  extractionMode={isEquirectSource ? 'rectilinear' : 'flat-crop'}
                  outputFormat="mp4"
                  showProgress
                  yaw={yaw}
                  pitch={pitch}
                  horizontalFov={horizontalFov}
                  outputWidth={outputWidth}
                  outputHeight={outputHeight}
                  reverse={reverse}
                  inputFile={inputFile}
                  cropRegion={cropRegion}
                  recordRange={recordRange}
                onProgress={({ progress }) => {
                  setExtractBusy(true);
                  setExtractProgress(progress);
                }}
                onExtractComplete={({ blob, metadata }) => {
                  setExtractBusy(false);
                  setExtractProgress(100);
                  setExtractError(null);
                  setExtractUrl((previous) => {
                    if (previous) {
                      URL.revokeObjectURL(previous);
                    }
                    return URL.createObjectURL(blob);
                  });
                  const filter = metadata.filter;
                  setExtractFilter(typeof filter === 'string' ? filter : '');
                }}
                onExtractError={({ message }) => {
                  setExtractBusy(false);
                  setExtractError(message);
                }}
              />
              </>
            ) : (
              <p className="da-note">Attach a video file to enable ffmpeg.wasm extract.</p>
            )}

            {extractBusy ? (
              <p className="da-note" aria-live="polite">
                Extracting… {extractProgress > 0 ? `${extractProgress}%` : 'loading ffmpeg.wasm (~31 MB first run)'}
              </p>
            ) : null}
            {extractError ? (
              <p className="da-note da-note--warn" role="alert">
                Extract failed: {extractError}
              </p>
            ) : null}
            {extractUrl ? (
              <>
                <p className="da-note">Extracted MP4 (ffmpeg.wasm):</p>
                <video className="da-authoring-pane__video" src={extractUrl} controls playsInline autoPlay muted />
                <a
                  className="da-media-extract-output__download"
                  href={extractUrl}
                  download={authoringExtractDownloadName(inputFile)}
                >
                  Download extracted video
                </a>
              </>
            ) : null}
              </>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}

// apps/proof-angular/src/screens/authoring-screen.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  ElementRef,
  inject,
  signal,
  viewChild,
} from '@angular/core';
import {
  AUTHORING_OUTPUT_CUSTOM_ID,
  AUTHORING_OUTPUT_PRESETS,
  getAuthoringOutputPreset,
  virtualCameraToCropRegion,
} from '@rosettadash/core';
import { EquirectSphereViewport } from '@rosettadash/angular/visual/media/equirect-sphere-viewport';
import { type VideoFileDetail } from '@rosettadash/angular/visual/media/video-source';
import { WasmMedia } from '@rosettadash/angular/visual/wasm/media';
import {
  DEFAULT_AUTHORING_EXAMPLE_ID,
  DESTINATION_ATLAS_AUTHORING_EXAMPLES,
  getAuthoringExampleById,
  getAuthoringExampleForDestinationId,
  getDestinationById,
  resolveEquirectSourceVideoUrl,
} from '@destination-atlas';
import { localizedDestinationName } from '../lib/atlas-utils';
import { AtlasStateService } from '../services/atlas-state.service';
import { AuthoringPlaybackBarComponent } from '../components/authoring-playback-bar.component';
import { AuthoringCameraControlsComponent } from '../components/authoring-camera-controls.component';
import { DaBoundSelectInputComponent } from '../components/proof-form-fields.component';

type CropRegion = Record<string, string | number | boolean | null | undefined>;

function matchOutputPreset(width: number, height: number): string {
  const match = AUTHORING_OUTPUT_PRESETS.find(
    (entry) => entry.width === width && entry.height === height,
  );
  return match?.id ?? AUTHORING_OUTPUT_CUSTOM_ID;
}

function probeVideoFile(file: File): Promise<{ width: number; height: number }> {
  return new Promise((resolve) => {
    const url = URL.createObjectURL(file);
    const video = document.createElement('video');
    video.preload = 'metadata';
    video.onloadedmetadata = () => {
      resolve({ width: video.videoWidth, height: video.videoHeight });
      URL.revokeObjectURL(url);
    };
    video.onerror = () => {
      URL.revokeObjectURL(url);
      resolve({ width: 0, height: 0 });
    };
    video.src = url;
  });
}

@Component({
  selector: 'da-authoring-screen',
  standalone: true,
  imports: [
    EquirectSphereViewport,
    WasmMedia,
    AuthoringPlaybackBarComponent,
    AuthoringCameraControlsComponent,
    DaBoundSelectInputComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="da-panel da-panel--authoring">
      <h2>Authoring</h2>

      <div class="da-authoring-workspace">
        <header class="da-authoring-workspace__headers">
          <h3 class="da-authoring-pane__title">Source</h3>
          <h3 class="da-authoring-pane__title">Output</h3>
        </header>

        <div class="da-authoring-workspace__videos">
          <div class="da-authoring-workspace__video-col">
            @if (isEquirectExample()) {
              @if (sourceUrl()) {
                <rd-equirect-sphere-viewport
                  #sphereViewport
                  class="da-authoring-sphere-viewport"
                  [videoSrc]="sourceUrl()"
                  [flipInterior]="true"
                  [yaw]="yaw()"
                  [pitch]="pitch()"
                  [horizontalFov]="horizontalFov()"
                  [outputWidth]="outputWidth()"
                  [outputHeight]="outputHeight()"
                  [outputPreviewElement]="outputPreviewElement()"
                  (cameraChange)="onCameraChange($event)"
                />
              } @else if (sourceLoadBusy()) {
                <div
                  class="da-authoring-sphere-viewport da-authoring-sphere-viewport--placeholder"
                  aria-busy="true"
                  aria-label="Loading source video"
                ></div>
              } @else {
                <div class="da-authoring-sphere-viewport da-authoring-sphere-viewport--placeholder">
                  <label class="da-authoring-choose-file">
                    <input
                      type="file"
                      class="da-authoring-choose-file__input"
                      accept="video/*"
                      (change)="onAuthoringFileSelected($event)"
                    />
                    Choose video file
                  </label>
                </div>
              }
            } @else {
              <div class="da-authoring-sphere-viewport da-authoring-sphere-viewport--placeholder">
                <label class="da-authoring-choose-file">
                  <input
                    type="file"
                    class="da-authoring-choose-file__input"
                    accept="video/*"
                    (change)="onAuthoringFileSelected($event)"
                  />
                  Choose video file
                </label>
              </div>
            }
          </div>

          <div class="da-authoring-workspace__video-col">
            @if (sourceUrl()) {
              <div #outputPreviewHost class="da-authoring-program-preview-host"></div>
            } @else {
              <div class="da-authoring-program-preview-host da-authoring-program-preview-host--placeholder">
                <p class="da-authoring-output-placeholder">Choose source file to create output</p>
              </div>
            }
          </div>
        </div>

        <div class="da-authoring-workspace__footers">
          <div class="da-authoring-pane da-authoring-pane--source" aria-label="Authoring source controls">
            <da-authoring-playback-bar
              [viewport]="viewportRef()"
              [disabled]="!sourceUrl()"
              (resetView)="resetView()"
            />
            <da-authoring-camera-controls
              [yaw]="yaw()"
              [pitch]="pitch()"
              [horizontalFov]="horizontalFov()"
              [disabled]="!sourceUrl() || !isEquirectExample()"
              (yawChange)="yaw.set($event)"
              (pitchChange)="pitch.set($event)"
              (horizontalFovChange)="horizontalFov.set($event)"
              (reset)="resetView()"
              (littlePlanetPreset)="applyLittlePlanetPreset()"
            />
          </div>

          <div class="da-authoring-pane da-authoring-pane--output" aria-label="Authoring output controls">
            <p class="da-note">Same view as source — live mirror scaled to export dimensions.</p>

            @if (sourceWidth() && sourceHeight()) {
              <p class="da-note" [class.da-note--warn]="equirectAspectWarning()">
                Source dimensions: {{ sourceWidth() }}×{{ sourceHeight() }} ({{ sourceAspect()?.toFixed(2) }}:1)
                @if (isEquirectExample()) {
                  — interior view flips texture for inside-out viewing
                }
                @if (equirectAspectWarning()) {
                  · aspect ratio differs from 2:1; extract may look wrong
                }
              </p>
            }

            <div class="da-media-extract-controls">
              <da-bound-select-input
                [fieldLabel]="'Export rectangle size'"
                [options]="outputPresetOptions()"
                [value]="outputPresetId()"
                (valueChange)="handleOutputPresetChange($event)"
              />
              <section class="rd-input-number">
                <span class="rd-field__label">Yaw (°)</span>
                <input type="number" class="rd-input" step="0.5" min="-180" max="180" [value]="formatDegree(yaw())" (change)="yaw.set(+$any($event.target).value)" />
              </section>
              <section class="rd-input-number">
                <span class="rd-field__label">Pitch (°)</span>
                <input type="number" class="rd-input" step="0.5" min="-85" max="85" [value]="formatDegree(pitch())" (change)="pitch.set(+$any($event.target).value)" />
              </section>
              <section class="rd-input-number">
                <span class="rd-field__label">Horizontal FOV (°)</span>
                <input type="number" class="rd-input" step="1" min="30" max="360" [value]="horizontalFov()" (change)="horizontalFov.set(+$any($event.target).value)" />
              </section>
              <section class="rd-input-number">
                <span class="rd-field__label">Output width</span>
                <input
                  type="number"
                  class="rd-input"
                  step="2"
                  min="160"
                  max="3840"
                  [value]="outputWidth()"
                  [disabled]="!isCustomOutput()"
                  (change)="handleCustomDimensionChange(+$any($event.target).value, outputHeight())"
                />
              </section>
              <section class="rd-input-number">
                <span class="rd-field__label">Output height</span>
                <input
                  type="number"
                  class="rd-input"
                  step="2"
                  min="120"
                  max="2160"
                  [value]="outputHeight()"
                  [disabled]="!isCustomOutput()"
                  (change)="handleCustomDimensionChange(outputWidth(), +$any($event.target).value)"
                />
              </section>
              <label class="rd-input-checkbox">
                <input type="checkbox" [checked]="reverse()" (change)="reverse.set($any($event.target).checked)" />
                Reverse playback
              </label>
            </div>

            @if (extractFilter()) {
              <p class="da-note da-note--filter">
                Filter:
                <code class="da-value-ellipsis" tabindex="0">{{ extractFilter() }}</code>
              </p>
            }

            @if (inputFile()) {
              <rd-wasm-media
                label="ffmpeg.wasm extract"
                operation="equirect-extract"
                extractionMode="rectilinear"
                outputFormat="mp4"
                [showProgress]="true"
                [yaw]="yaw()"
                [pitch]="pitch()"
                [horizontalFov]="horizontalFov()"
                [outputWidth]="outputWidth()"
                [outputHeight]="outputHeight()"
                [reverse]="reverse()"
                [inputFile]="inputFile()"
                [cropRegion]="cropRegion()"
                (progress)="onExtractProgress($event)"
                (extractComplete)="onExtractComplete($event)"
                (extractError)="onExtractError($event)"
              />
            } @else {
              <p class="da-note">Attach a video file to enable ffmpeg.wasm extract.</p>
            }

            @if (extractBusy()) {
              <p class="da-note" aria-live="polite">
                Extracting…
                @if (extractProgress() > 0) {
                  {{ extractProgress() }}%
                } @else {
                  loading ffmpeg.wasm (~31 MB first run)
                }
              </p>
            }
            @if (extractError(); as error) {
              <p class="da-note da-note--warn" role="alert">Extract failed: {{ error }}</p>
            }
            @if (extractUrl(); as url) {
              <p class="da-note">Extracted MP4 (ffmpeg.wasm):</p>
              <video class="da-authoring-pane__video" [src]="url" controls playsinline autoplay muted></video>
              <a class="da-media-extract-output__download" [href]="url" [download]="downloadName()">
                Download extracted video
              </a>
            }
          </div>
        </div>
      </div>
    </section>
  `,
})
export class AuthoringScreenComponent {
  readonly atlas = inject(AtlasStateService);

  readonly exampleId = signal(DEFAULT_AUTHORING_EXAMPLE_ID);
  readonly inputFile = signal<File | null>(null);
  readonly sourceUrl = signal<string | null>(null);
  readonly sourceLoadBusy = signal(false);
  readonly sourceLoadError = signal<string | null>(null);
  readonly cropRegion = signal<CropRegion | null>(null);
  readonly extractUrl = signal<string | null>(null);
  readonly extractFilter = signal('');
  readonly extractProgress = signal(0);
  readonly extractError = signal<string | null>(null);
  readonly extractBusy = signal(false);

  readonly yaw = signal(25);
  readonly pitch = signal(-8);
  readonly horizontalFov = signal(75);
  readonly outputWidth = signal(720);
  readonly outputHeight = signal(480);
  readonly outputPresetId = signal('720x480');
  readonly reverse = signal(false);
  readonly sourceWidth = signal<number | undefined>(undefined);
  readonly sourceHeight = signal<number | undefined>(undefined);

  private userPickedFile = false;

  private objectUrl: string | null = null;
  private extractObjectUrl: string | null = null;

  readonly sphereViewport = viewChild<EquirectSphereViewport>('sphereViewport');
  readonly outputPreviewHostEl = viewChild<ElementRef<HTMLElement>>('outputPreviewHost');

  readonly example = computed(
    () => getAuthoringExampleById(this.exampleId()) ?? DESTINATION_ATLAS_AUTHORING_EXAMPLES[0],
  );

  readonly exampleOptions = computed(() =>
    DESTINATION_ATLAS_AUTHORING_EXAMPLES.map((entry) => ({
      value: entry.id,
      label: entry.label,
    })),
  );

  readonly isEquirectExample = computed(() => this.example()?.projection === 'equirect');

  readonly isCustomOutput = computed(() => this.outputPresetId() === AUTHORING_OUTPUT_CUSTOM_ID);

  readonly sourceAspect = computed(() => {
    const width = this.sourceWidth();
    const height = this.sourceHeight();
    return width && height && height > 0 ? width / height : null;
  });

  readonly equirectAspectWarning = computed(
    () =>
      this.isEquirectExample() &&
      this.sourceAspect() !== null &&
      Math.abs(this.sourceAspect()! - 2) > 0.05,
  );

  readonly exampleLabel = computed(() => {
    const example = this.example();
    const destination = example ? getDestinationById(example.destinationId) : undefined;
    if (!example || !destination) {
      return example?.label ?? 'Authoring example';
    }
    return `${example.label} · ${localizedDestinationName(destination, this.atlas.locale())}`;
  });

  readonly outputPresetOptions = computed(() => [
    ...AUTHORING_OUTPUT_PRESETS.map((entry) => ({ value: entry.id, label: entry.label })),
    { value: AUTHORING_OUTPUT_CUSTOM_ID, label: 'Custom' },
  ]);

  readonly downloadName = computed(() => `${this.example()?.id ?? 'authoring'}-extract.mp4`);

  constructor() {
    effect(() => {
      const selectedId = this.atlas.selectedId();
      if (!selectedId) {
        return;
      }
      const linkedExample = getAuthoringExampleForDestinationId(selectedId);
      if (linkedExample) {
        this.exampleId.set(linkedExample.id);
      }
    });

    effect(() => {
      this.atlas.selectedId();
      this.exampleId();
      this.userPickedFile = false;
    });

    effect((onCleanup) => {
      const example = this.example();
      const selectedId = this.atlas.selectedId();
      if (!example) {
        return;
      }

      if (!this.userPickedFile) {
        this.yaw.set(example.defaultYaw);
        this.pitch.set(example.defaultPitch);
        this.horizontalFov.set(example.defaultHorizontalFov);
        const preset = getAuthoringOutputPreset('720x480');
        this.outputPresetId.set('720x480');
        this.outputWidth.set(preset?.width ?? 720);
        this.outputHeight.set(preset?.height ?? 480);
        this.sourceWidth.set(undefined);
        this.sourceHeight.set(undefined);
        this.cropRegion.set(null);
        this.extractFilter.set('');
        this.extractProgress.set(0);
        this.extractError.set(null);
        this.extractBusy.set(false);
        this.revokeExtractUrl();
      }

      const destination = selectedId ? getDestinationById(selectedId) : undefined;
      const shippedUrl = resolveEquirectSourceVideoUrl(destination);
      const shouldLoadShipped =
        Boolean(selectedId) && example.destinationId === selectedId && Boolean(shippedUrl);

      if (this.userPickedFile || !shouldLoadShipped || !shippedUrl || !destination) {
        if (!this.userPickedFile) {
          this.inputFile.set(null);
          this.sourceUrl.set(null);
          this.sourceLoadBusy.set(false);
          this.sourceLoadError.set(null);
        }
        return;
      }

      let cancelled = false;
      this.sourceLoadError.set(null);
      this.sourceLoadBusy.set(true);
      this.inputFile.set(null);
      this.sourceUrl.set(null);

      void (async () => {
        try {
          const response = await fetch(shippedUrl);
          if (!response.ok) {
            throw new Error(`HTTP ${response.status}`);
          }
          const blob = await response.blob();
          if (cancelled || this.userPickedFile) {
            return;
          }
          const ext = shippedUrl.includes('.webm') ? 'webm' : 'mp4';
          this.inputFile.set(
            new File([blob], `${destination.id}-equirect.${ext}`, {
              type: blob.type || `video/${ext}`,
            }),
          );
        } catch (error) {
          if (cancelled) {
            return;
          }
          this.sourceLoadError.set(
            error instanceof Error ? error.message : 'Could not load shipped 360° video',
          );
          this.sourceUrl.set(shippedUrl);
        } finally {
          if (!cancelled) {
            this.sourceLoadBusy.set(false);
          }
        }
      })();

      onCleanup(() => {
        cancelled = true;
      });
    });

    effect((onCleanup) => {
      const file = this.inputFile();
      if (!file) {
        return;
      }
      const url = URL.createObjectURL(file);
      this.objectUrl = url;
      this.sourceUrl.set(url);
      onCleanup(() => {
        URL.revokeObjectURL(url);
        if (this.objectUrl === url) {
          this.objectUrl = null;
        }
      });
    });

    effect(() => {
      const region = virtualCameraToCropRegion({
        camera: { yaw: this.yaw(), pitch: this.pitch(), roll: 0, fov: this.horizontalFov() },
        sourceWidth: this.sourceWidth(),
        sourceHeight: this.sourceHeight(),
        outputWidth: this.outputWidth(),
        outputHeight: this.outputHeight(),
        reverse: this.reverse(),
      });
      this.cropRegion.set(region);
      const filter = region.filter;
      this.extractFilter.set(typeof filter === 'string' ? filter : '');
    });
  }

  viewportRef(): EquirectSphereViewport | null {
    return this.sphereViewport() ?? null;
  }

  outputPreviewElement(): HTMLElement | null {
    return this.outputPreviewHostEl()?.nativeElement ?? null;
  }

  formatDegree(value: number): number {
    return Math.round(value * 10) / 10;
  }

  onCameraChange(detail: { yaw: number; pitch: number; horizontalFov: number }): void {
    this.yaw.set(detail.yaw);
    this.pitch.set(detail.pitch);
    this.horizontalFov.set(detail.horizontalFov);
  }

  handleOutputPresetChange(presetId: string): void {
    this.outputPresetId.set(presetId);
    if (presetId === AUTHORING_OUTPUT_CUSTOM_ID) {
      return;
    }
    const preset = getAuthoringOutputPreset(presetId);
    if (preset) {
      this.outputWidth.set(preset.width);
      this.outputHeight.set(preset.height);
    }
  }

  handleCustomDimensionChange(width: number, height: number): void {
    if (!this.isCustomOutput()) {
      return;
    }
    this.outputWidth.set(width);
    this.outputHeight.set(height);
    this.outputPresetId.set(matchOutputPreset(width, height));
  }

  handleVideoFile(detail: VideoFileDetail): void {
    this.userPickedFile = true;
    this.sourceLoadBusy.set(false);
    this.sourceLoadError.set(null);
    this.inputFile.set(detail.file);
    const example = this.example();
    if (example) {
      this.yaw.set(example.defaultYaw);
      this.pitch.set(example.defaultPitch);
      this.horizontalFov.set(example.defaultHorizontalFov);
    }
    const width = Number(detail.metadata.sourceWidth);
    const height = Number(detail.metadata.sourceHeight);
    if (Number.isFinite(width) && width > 0 && Number.isFinite(height) && height > 0) {
      this.sourceWidth.set(width);
      this.sourceHeight.set(height);
    } else {
      this.sourceWidth.set(undefined);
      this.sourceHeight.set(undefined);
    }
    this.revokeExtractUrl();
    this.extractProgress.set(0);
    this.extractError.set(null);
    this.extractBusy.set(false);
  }

  onAuthoringFileSelected(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (!file) {
      return;
    }
    void probeVideoFile(file).then(({ width, height }) => {
      this.handleVideoFile({
        file,
        metadata: {
          name: file.name,
          sourceWidth: width > 0 ? width : undefined,
          sourceHeight: height > 0 ? height : undefined,
          size: file.size,
        },
      });
    });
  }

  resetView(): void {
    const example = this.example();
    if (!example) {
      return;
    }
    this.yaw.set(example.defaultYaw);
    this.pitch.set(example.defaultPitch);
    this.horizontalFov.set(example.defaultHorizontalFov);
  }

  applyLittlePlanetPreset(): void {
    this.horizontalFov.set(360);
    this.pitch.set(-85);
  }

  onExtractProgress(detail: { progress: number }): void {
    this.extractBusy.set(true);
    this.extractProgress.set(detail.progress);
  }

  onExtractComplete(detail: {
    blob: Blob;
    metadata: Record<string, string | number | boolean | null | undefined>;
  }): void {
    this.extractBusy.set(false);
    this.extractProgress.set(100);
    this.extractError.set(null);
    this.revokeExtractUrl();
    const url = URL.createObjectURL(detail.blob);
    this.extractObjectUrl = url;
    this.extractUrl.set(url);
    const filter = detail.metadata.filter;
    this.extractFilter.set(typeof filter === 'string' ? filter : '');
  }

  onExtractError(detail: { message: string }): void {
    this.extractBusy.set(false);
    this.extractError.set(detail.message);
  }

  private revokeExtractUrl(): void {
    if (this.extractObjectUrl) {
      URL.revokeObjectURL(this.extractObjectUrl);
      this.extractObjectUrl = null;
    }
    this.extractUrl.set(null);
  }
}
