// apps/proof-react/src/screens/IntelScreen.tsx
import { useEffect, useMemo, useState } from 'react';
import { RoleGate } from '@rosettadash/react/domain/role-gate';
import { NewsArticleDetail } from '@rosettadash/react/visual/news/article-detail';
import { NewsRegionSelect } from '@rosettadash/react/visual/news/region-select';
import { NewsResultsTable } from '@rosettadash/react/visual/news/results-table';
import { NewsSearchBox } from '@rosettadash/react/visual/news/search-box';
import type { AtlasContext } from '../state/useDestinationAtlasState';
import { useConsumerSecrets } from '../state/consumer-secrets-context';
import { MOCK_NEWS } from '../lib/atlas-utils';
import { fetchLiveNewsArticles, type LiveNewsArticle } from '../lib/news-api';

export const INTEL_SOURCE = `<IntelScreen userRole={userRole} newsQuery={newsQuery}>
  <RoleGate currentRole={userRole} allowedRoles={['editor', 'admin']}>
    <NewsSearchBox value={newsQuery} onSearch={setNewsQuery} />
    <NewsRegionSelect value={newsRegion} />
  </RoleGate>
  <NewsResultsTable rows={filteredArticles} selectedRowId={selectedArticleId} />
</IntelScreen>`;

const REGION_OPTIONS = [
  { value: 'asia-pacific', label: 'Asia Pacific' },
  { value: 'europe', label: 'Europe' },
  { value: 'americas', label: 'Americas' },
  { value: 'africa', label: 'Africa' },
];

type Props = Pick<
  AtlasContext,
  | 'userRole'
  | 'newsQuery'
  | 'setNewsQuery'
  | 'newsRegion'
  | 'setNewsRegion'
  | 'selectedArticleId'
  | 'setSelectedArticleId'
  | 'setScreen'
  | 'setHighlightTarget'
>;

export function IntelScreen({
  userRole,
  newsQuery,
  setNewsQuery,
  newsRegion,
  setNewsRegion,
  selectedArticleId,
  setSelectedArticleId,
  setScreen,
  setHighlightTarget,
}: Props) {
  const secrets = useConsumerSecrets();
  const newsApiKey = secrets.newsApiKey;
  const [liveArticles, setLiveArticles] = useState<LiveNewsArticle[] | null>(null);
  const [liveWarning, setLiveWarning] = useState<string | null>(null);
  const [liveMode, setLiveMode] = useState<'idle' | 'loading' | 'mock' | 'live'>('idle');

  useEffect(() => {
    if (!newsApiKey) {
      setLiveArticles(null);
      setLiveWarning(null);
      setLiveMode('mock');
      return;
    }

    let cancelled = false;
    setLiveMode('loading');
    void fetchLiveNewsArticles({ apiKey: newsApiKey, query: newsQuery, region: newsRegion }).then(
      (result) => {
        if (cancelled) {
          return;
        }
        if (!result) {
          setLiveArticles(null);
          setLiveWarning(
            'NEWS_API_KEY is configured but the browser blocked the request (typical NewsAPI CORS). Showing mock headlines — use a server proxy in production.',
          );
          setLiveMode('mock');
          return;
        }
        if (result.articles.length) {
          setLiveArticles(result.articles);
          setLiveWarning(result.warning ?? null);
          setLiveMode('live');
          return;
        }
        setLiveArticles(null);
        setLiveWarning(result.warning ?? 'News API returned no results — showing mock headlines.');
        setLiveMode('mock');
      },
    );

    return () => {
      cancelled = true;
    };
  }, [newsApiKey, newsQuery, newsRegion]);

  const articleSource = liveMode === 'live' && liveArticles?.length ? liveArticles : MOCK_NEWS;

  const filtered = useMemo(
    () =>
      articleSource.filter((article) => {
        const matchesQuery =
          !newsQuery ||
          article.headline.toLowerCase().includes(newsQuery.toLowerCase()) ||
          article.summary.toLowerCase().includes(newsQuery.toLowerCase());
        const matchesRegion = !newsRegion || article.region === newsRegion;
        return matchesQuery && matchesRegion;
      }),
    [articleSource, newsQuery, newsRegion],
  );

  const selected = filtered.find((article) => article.id === selectedArticleId) ??
    articleSource.find((article) => article.id === selectedArticleId);

  const openIntegrationsSettings = () => {
    setHighlightTarget('integrations');
    setScreen('settings');
  };

  return (
    <section className="da-panel">
      <h2>Intel</h2>
      <p>Regional news discovery with search, region filter, results, and article detail.</p>
      {newsApiKey ? (
        <p className="da-note">
          {liveMode === 'loading'
            ? 'Fetching live headlines…'
            : liveMode === 'live'
              ? 'Live News API headlines (BYOK).'
              : 'BYOK key present — mock headlines used as fallback.'}
          {liveWarning ? <> {liveWarning}</> : null}
        </p>
      ) : (
        <p className="da-note da-byok-cta">
          Showing mock headlines. Add a News API key in{' '}
          <button type="button" className="da-locale-link" onClick={openIntegrationsSettings}>
            Settings → Integrations
          </button>{' '}
          for live fetch (may require a server proxy due to CORS).
        </p>
      )}
      <div className="da-stack">
        <RoleGate
          label="News discovery tools"
          currentRole={userRole}
          allowedRoles={['editor', 'admin']}
          statusText="Search and region filters enabled"
          hiddenStatusText="Viewer role can browse headlines only — switch to Editor to search and filter."
        >
          <div className="da-stack da-stack--2">
            <NewsSearchBox
              label="Search news"
              placeholder="Search headlines…"
              value={newsQuery}
              onSearch={setNewsQuery}
            />
            <NewsRegionSelect
              label="Region"
              placeholder="All regions"
              options={REGION_OPTIONS}
              value={newsRegion}
              onChange={setNewsRegion}
            />
          </div>
        </RoleGate>
        <NewsResultsTable
          title="News results"
          rows={filtered.map((article) => ({
            id: article.id,
            headline: article.headline,
            source: article.source,
            region: article.region,
            published: article.published,
          }))}
          selectedRowId={selectedArticleId}
          onRowSelect={userRole === 'viewer' ? undefined : setSelectedArticleId}
        />
        <RoleGate
          label="Article detail"
          currentRole={userRole}
          allowedRoles={['editor', 'admin']}
          statusText="Full article summaries"
          hiddenStatusText="Article summaries are hidden for Viewer — headlines remain visible above."
        >
          <NewsArticleDetail title="Article detail">
            {selected ? (
              <div className="da-detail-body">
                <p>
                  <strong>{selected.headline}</strong>
                </p>
                <p>
                  {selected.source} · {selected.region} · {selected.published}
                </p>
                <p>{selected.summary}</p>
              </div>
            ) : (
              <p className="da-detail-body">Select a headline to read the summary.</p>
            )}
          </NewsArticleDetail>
        </RoleGate>
      </div>
    </section>
  );
}

// apps/proof-angular/src/screens/intel-screen.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core';
import { NewsArticleDetail } from '@rosettadash/angular/visual/news/article-detail';
import { MOCK_NEWS } from '../lib/atlas-utils';
import { fetchLiveNewsArticles, type LiveNewsArticle } from '../lib/news-api';
import { AtlasStateService } from '../services/atlas-state.service';
import { ConsumerSecretsService } from '../services/consumer-secrets.service';
import { RoleGatePanelComponent } from '../components/role-gate-panel.component';
import {
  DaBoundSelectInputComponent,
  DaBoundTextInputComponent,
} from '../components/proof-form-fields.component';

const REGION_OPTIONS = [
  { value: 'asia-pacific', label: 'Asia Pacific' },
  { value: 'europe', label: 'Europe' },
  { value: 'americas', label: 'Americas' },
  { value: 'africa', label: 'Africa' },
];

@Component({
  selector: 'da-intel-screen',
  standalone: true,
  imports: [
    NewsArticleDetail,
    RoleGatePanelComponent,
    DaBoundSelectInputComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="da-panel">
      <h2>Intel</h2>
      <p>Regional news discovery with search, region filter, results, and article detail.</p>
      @if (secrets.newsApiKey()) {
        <p class="da-note">
          @if (liveMode() === 'loading') {
            Fetching live headlines…
          } @else if (liveMode() === 'live') {
            Live News API headlines (BYOK).
          } @else {
            BYOK key present — mock headlines used as fallback.
          }
          @if (liveWarning()) {
            {{ liveWarning() }}
          }
        </p>
      } @else {
        <p class="da-note da-byok-cta">
          Showing mock headlines. Add a News API key in
          <button type="button" class="da-locale-link" (click)="openIntegrationsSettings()">
            Settings → Integrations
          </button>
          for live fetch (may require a server proxy due to CORS).
        </p>
      }

      <div class="da-stack">
        <da-role-gate-panel
          [gateLabel]="'News discovery tools'"
          [currentRole]="atlas.userRole()"
          [allowedRoles]="['editor', 'admin']"
          statusText="Search and region filters enabled"
          hiddenStatusText="Viewer role can browse headlines only — switch to Editor to search and filter."
        >
          <div class="da-stack da-stack--2">
            <section class="rd-news-search-box">
              <span class="rd-field__label">Search news</span>
              <div class="rd-search__row">
                <input
                  type="search"
                  class="rd-input"
                  placeholder="Search headlines…"
                  [value]="atlas.newsQuery()"
                  (input)="atlas.newsQuery.set($any($event.target).value)"
                />
                <button type="button" class="rd-button" (click)="atlas.newsQuery.set(atlas.newsQuery())">
                  Search
                </button>
              </div>
            </section>
            <da-bound-select-input
              [fieldLabel]="'Region'"
              placeholder="All regions"
              [options]="regionOptions"
              [value]="atlas.newsRegion()"
              (valueChange)="atlas.newsRegion.set($event)"
            />
          </div>
        </da-role-gate-panel>

        <section class="rd-news-results-table">
          <header class="rd-table__header"><span>News results</span></header>
          <table class="rd-table">
            <thead>
              <tr>
                <th>Headline</th>
                <th>Source</th>
                <th>Region</th>
                <th>Published</th>
              </tr>
            </thead>
            <tbody>
              @for (article of filteredArticles(); track article.id) {
                <tr
                  [class.rd-table__row--selected]="article.id === atlas.selectedArticleId()"
                  [class.da-table-row--clickable]="canSelectRows()"
                  (click)="selectArticle(article.id)"
                >
                  <td>{{ article.headline }}</td>
                  <td>{{ article.source }}</td>
                  <td>{{ article.region }}</td>
                  <td>{{ article.published }}</td>
                </tr>
              }
            </tbody>
          </table>
        </section>

        <da-role-gate-panel
          [gateLabel]="'Article detail'"
          [currentRole]="atlas.userRole()"
          [allowedRoles]="['editor', 'admin']"
          statusText="Full article summaries"
          hiddenStatusText="Article summaries are hidden for Viewer — headlines remain visible above."
        >
          <rd-news-article-detail title="Article detail">
            @if (selectedArticle(); as article) {
              <div class="da-detail-body">
                <p><strong>{{ article.headline }}</strong></p>
                <p>{{ article.source }} · {{ article.region }} · {{ article.published }}</p>
                <p>{{ article.summary }}</p>
              </div>
            } @else {
              <p class="da-detail-body">Select a headline to read the summary.</p>
            }
          </rd-news-article-detail>
        </da-role-gate-panel>
      </div>
    </section>
  `,
})
export class IntelScreenComponent {
  readonly atlas = inject(AtlasStateService);
  readonly secrets = inject(ConsumerSecretsService);

  readonly regionOptions = REGION_OPTIONS;

  readonly liveArticles = signal<LiveNewsArticle[] | null>(null);
  readonly liveWarning = signal<string | null>(null);
  readonly liveMode = signal<'idle' | 'loading' | 'mock' | 'live'>('idle');

  readonly articleSource = computed(() => {
    if (this.liveMode() === 'live' && this.liveArticles()?.length) {
      return this.liveArticles()!;
    }
    return MOCK_NEWS;
  });

  readonly filteredArticles = computed(() => {
    const query = this.atlas.newsQuery().toLowerCase();
    const region = this.atlas.newsRegion();
    return this.articleSource().filter((article) => {
      const matchesQuery =
        !query ||
        article.headline.toLowerCase().includes(query) ||
        article.summary.toLowerCase().includes(query);
      const matchesRegion = !region || article.region === region;
      return matchesQuery && matchesRegion;
    });
  });

  readonly selectedArticle = computed(() => {
    const id = this.atlas.selectedArticleId();
    return (
      this.filteredArticles().find((article) => article.id === id) ??
      this.articleSource().find((article) => article.id === id) ??
      null
    );
  });

  constructor() {
    effect((onCleanup) => {
      const apiKey = this.secrets.newsApiKey();
      const query = this.atlas.newsQuery();
      const region = this.atlas.newsRegion();

      if (!apiKey) {
        this.liveArticles.set(null);
        this.liveWarning.set(null);
        this.liveMode.set('mock');
        return;
      }

      let cancelled = false;
      this.liveMode.set('loading');
      void fetchLiveNewsArticles({ apiKey, query, region }).then((result) => {
        if (cancelled) {
          return;
        }
        if (!result) {
          this.liveArticles.set(null);
          this.liveWarning.set(
            'NEWS_API_KEY is configured but the browser blocked the request (typical NewsAPI CORS). Showing mock headlines — use a server proxy in production.',
          );
          this.liveMode.set('mock');
          return;
        }
        if (result.articles.length) {
          this.liveArticles.set(result.articles);
          this.liveWarning.set(result.warning ?? null);
          this.liveMode.set('live');
          return;
        }
        this.liveArticles.set(null);
        this.liveWarning.set(result.warning ?? 'News API returned no results — showing mock headlines.');
        this.liveMode.set('mock');
      });

      onCleanup(() => {
        cancelled = true;
      });
    });
  }

  canSelectRows(): boolean {
    return this.atlas.userRole() !== 'viewer';
  }

  selectArticle(id: string): void {
    if (this.canSelectRows()) {
      this.atlas.selectedArticleId.set(id);
    }
  }

  openIntegrationsSettings(): void {
    this.atlas.setHighlightTarget('integrations');
    this.atlas.setScreen('settings');
  }
}
