// apps/proof-vue/src/screens/OverviewScreen.vue
<script lang="ts">
export const OVERVIEW_SOURCE = `<OverviewScreen locale={locale} userRole={userRole}>
  <GridLayout columns={3} gap={12} title="Destination KPIs">
    {MOCK_DESTINATIONS.map((dest) => (
      <KpiCard title={...} value={...} delta={...} />
    ))}
  </GridLayout>
  <LineChart points={aggregateVisitorTrend()} xAxisLabel="Year" yAxisLabel="Total visitors" />
  <BarChart bars={destinationBarSeries(locale)} yAxisLabel="Visitors" />
  <RoleGate currentRole={userRole} allowedRoles={['admin']} label="Operations metrics">
    <MetricChip chipLabel="Avg. stay" chipValue="4.2 nights" />
    <StatusBadge statusText="Data freshness: current" tone="success" />
  </RoleGate>
</OverviewScreen>`;
</script>

<script setup lang="ts">
import { BarChart } from '@rosettadash/vue/visual/chart/bar';
import { LineChart } from '@rosettadash/vue/visual/chart/line';
import { GridLayout } from '@rosettadash/vue/layout/grid';
import RoleGatePanel from '../components/RoleGatePanel.vue';
import { KpiCard } from '@rosettadash/vue/visual/kpi';
import { MetricChip } from '@rosettadash/vue/visual/plugin/metric-chip';
import { StatusBadge } from '@rosettadash/vue/visual/plugin/status-badge';
import { MOCK_DESTINATIONS, formatVisitorCount } from '@destination-atlas';
import type { AtlasUserRole } from '../lib/roles';
import { computeVisitorDelta, localizedDestinationName } from '../lib/atlas-utils';

defineProps<{ locale: string; userRole: AtlasUserRole }>();
</script>

<template>
  <section class="da-panel">
    <h2>Overview</h2>
    <p>Current visitor KPIs and historic trends across sample destinations.</p>
    <div class="da-stack">
      <GridLayout :columns="3" :gap="12" title="Destination KPIs">
        <KpiCard
          v-for="dest in MOCK_DESTINATIONS"
          :key="dest.id"
          :title="localizedDestinationName(dest, locale)"
          :value="formatVisitorCount(dest.visitorsCurrent)"
          :delta="computeVisitorDelta(dest)"
          format="number"
        />
      </GridLayout>
      <div class="da-stack da-stack--2">
        <LineChart title="Visitors over time (aggregate trend)" />
        <BarChart title="2024 visitors by destination" />
      </div>
      <RoleGatePanel
        gate-label="Operations metrics"
        :current-role="userRole"
        :allowed-roles="['admin']"
        status-text="Admin operations panel"
        hidden-status-text="Operations metrics are hidden for Viewer and Editor roles."
      >
        <div class="da-stack da-stack--2 da-stack--metrics">
          <MetricChip chip-label="Avg. stay" chip-value="4.2 nights" />
          <StatusBadge status-text="Data freshness: current" tone="success" />
        </div>
      </RoleGatePanel>
    </div>
  </section>
</template>

// apps/proof-angular/src/screens/overview-screen.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { GridLayout } from '@rosettadash/angular/layout/grid';
import { KpiCard } from '@rosettadash/angular/visual/kpi';
import { LineChart } from '@rosettadash/angular/visual/chart/line';
import { BarChart } from '@rosettadash/angular/visual/chart/bar';
import { RoleGate } from '@rosettadash/angular/domain/role-gate';
import { MetricChip } from '@rosettadash/angular/visual/plugin/metric-chip';
import { StatusBadge } from '@rosettadash/angular/visual/plugin/status-badge';
import { MOCK_DESTINATIONS, formatVisitorCount } from '@destination-atlas';
import type { AtlasUserRole } from '../lib/roles';
import { computeVisitorDelta, localizedDestinationName } from '../lib/atlas-utils';

@Component({
  selector: 'da-overview-screen',
  standalone: true,
  imports: [GridLayout, KpiCard, LineChart, BarChart, RoleGate, MetricChip, StatusBadge],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="da-panel">
      <h2>Overview</h2>
      <p>Current visitor KPIs and historic trends across sample destinations.</p>
      <div class="da-stack">
        <rd-grid [columns]="3" [gap]="12" title="Destination KPIs">
          @for (dest of destinations; track dest.id) {
            <rd-kpi
              [title]="destTitle(dest)"
              [value]="formatCount(dest.visitorsCurrent)"
              [delta]="visitorDelta(dest)"
              format="number"
            />
          }
        </rd-grid>
        <div class="da-stack da-stack--2">
          <rd-chart-line title="Visitors over time (aggregate trend)" />
          <rd-chart-bar title="2024 visitors by destination" />
        </div>
        <rd-role-gate
          label="Operations metrics"
          [allowedRoles]="['admin']"
          statusText="Admin operations panel"
        >
          <div class="da-stack da-stack--2 da-stack--metrics">
            <rd-plugin-metric-chip chipLabel="Avg. stay" chipValue="4.2 nights" />
            <rd-plugin-status-badge statusText="Data freshness: current" tone="success" />
          </div>
        </rd-role-gate>
      </div>
    </section>
  `,
})
export class OverviewScreenComponent {
  readonly locale = input.required<string>();
  readonly userRole = input.required<AtlasUserRole>();

  readonly destinations = MOCK_DESTINATIONS;
  readonly formatCount = formatVisitorCount;

  destTitle(dest: (typeof MOCK_DESTINATIONS)[number]): string {
    return localizedDestinationName(dest, this.locale());
  }

  visitorDelta(dest: (typeof MOCK_DESTINATIONS)[number]): string {
    return computeVisitorDelta(dest);
  }
}
