// packages/svelte/src/layout/grid/GridLayout.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { GridLayoutProps } from './types';

	type Props = GridLayoutProps & { children?: Snippet };

	let {
		className,
		title,
		columns,
		gap,
		children,
	}: Props = $props();
	const gridColumns = $derived(`repeat(${columns ?? 3}, 1fr)`);
	const gridGap = $derived(typeof gap === 'number' ? gap : 12);
	const rootClass = $derived(['rd-grid', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-grid">
	{#if title}<span class="rd-grid__title">{title}</span>{/if}
	<div class="rd-grid__grid" style:grid-template-columns={gridColumns} style:gap="{gridGap}px">{@render children?.()}</div>
</section>

// packages/react/src/layout/grid/GridLayout.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface GridLayoutProps {
  title?: string;
  columns?: number;
  gap?: number | string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/layout/grid — layout.grid */
export const GridLayout = forwardRef<HTMLElement, GridLayoutProps>(function GridLayout(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-grid', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-grid">
      {props.title ? <span className="rd-grid__title">{props.title}</span> : null}
      <div className="rd-grid__grid" style={{ gridTemplateColumns: `repeat(${props.columns ?? 3}, 1fr)`, gap: props.gap ?? 12 }}>{children}</div>
    </section>
  );
});
