// packages/react/src/visual/news/article-detail/NewsArticleDetail.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface NewsArticleDetailProps {
  title?: string;
  emptyMessage?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/news/article-detail — visual.news.article-detail */
export const NewsArticleDetail = forwardRef<HTMLElement, NewsArticleDetailProps>(function NewsArticleDetail(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-news-article-detail', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-news-article-detail">
      <header className="rd-detail__header"><span>{props.title ?? 'Article'}</span></header>
      <p className="rd-detail__empty">{props.emptyMessage ?? 'Select a headline in News Results'}</p>
      {children}
    </section>
  );
});

// packages/angular/src/visual/news/article-detail/news-article-detail.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface NewsArticleDetailProps {
  title?: string;
  emptyMessage?: string;
  className?: string;
}

/** @rosettadash/angular/visual/news/article-detail — visual.news.article-detail */
@Component({
  selector: 'rd-news-article-detail',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-news-article-detail'" [ngClass]="rootClass()">
      <header class="rd-detail__header"><span>{{ title() ?? 'Article' }}</span></header>
      <p class="rd-detail__empty">{{ emptyMessage() ?? 'Select a headline in News Results' }}</p>
      <ng-content />
    </section>
  `,
})
export class NewsArticleDetail {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly emptyMessage = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-news-article-detail', this.className()].filter(Boolean).join(' '),
  );
}
