// packages/react/src/infra/mongodb/MongodbInfra.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface MongodbInfraProps {
  label?: string;
  envKey?: string;
  tableOrCollection?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/infra/mongodb — infra.mongodb */
export const MongodbInfra = forwardRef<HTMLElement, MongodbInfraProps>(function MongodbInfra(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-mongodb', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-mongodb">
      <span className="rd-infra__badge">INFRA</span>
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      {props.envKey ? <code>{props.envKey}</code> : null}
      {props.tableOrCollection ? <span className="rd-infra__meta">{props.tableOrCollection}</span> : null}
      {children}
    </section>
  );
});

// packages/angular/src/infra/mongodb/mongodb-infra.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface MongodbInfraProps {
  label?: string;
  envKey?: string;
  tableOrCollection?: string;
  className?: string;
}

/** @rosettadash/angular/infra/mongodb — infra.mongodb */
@Component({
  selector: 'rd-mongodb',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-mongodb'" [ngClass]="rootClass()">
      <span class="rd-infra__badge">INFRA</span>
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      @if (envKey()) { <code>{{ envKey() }}</code> }
      @if (tableOrCollection()) { <span class="rd-infra__meta">{{ tableOrCollection() }}</span> }
      <ng-content />
    </section>
  `,
})
export class MongodbInfra {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly envKey = input<string | undefined>(undefined);
  readonly tableOrCollection = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-mongodb', this.className()].filter(Boolean).join(' '),
  );
}
