// packages/angular/src/infra/env/env-config.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface EnvConfigProps {
  envKeys?: string;
  className?: string;
}

/** @rosettadash/angular/infra/env — infra.env */
@Component({
  selector: 'rd-env',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-env'" [ngClass]="rootClass()">
      <span class="rd-infra__badge">INFRA</span>
      <span class="rd-field__label">Environment config</span>
      <code>{{ envKeys() ?? 'DATABASE_URL, API_KEY' }}</code>
      <ng-content />
    </section>
  `,
})
export class EnvConfig {
  readonly className = input<string | undefined>(undefined);
  readonly envKeys = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-env', this.className()].filter(Boolean).join(' '),
  );
}

// packages/react/src/infra/env/EnvConfig.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface EnvConfigProps {
  envKeys?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/infra/env — infra.env */
export const EnvConfig = forwardRef<HTMLElement, EnvConfigProps>(function EnvConfig(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-env', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-env">
      <span className="rd-infra__badge">INFRA</span>
      <span className="rd-field__label">Environment config</span>
      <code>{props.envKeys ?? 'DATABASE_URL, API_KEY'}</code>
      {children}
    </section>
  );
});
