// packages/svelte/src/infra/env/EnvConfig.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { EnvConfigProps } from './types';

	type Props = EnvConfigProps & { children?: Snippet };

	let {
		className,
		envKeys,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-env', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-env">
	<span class="rd-infra__badge">INFRA</span>
	<span class="rd-field__label">Environment config</span>
	<code>{envKeys ?? 'DATABASE_URL, API_KEY'}</code>
	{@render children?.()}
</section>

// packages/react/src/infra/env/EnvConfig.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface EnvConfigProps {
  envKeys?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/infra/env — infra.env */
export const EnvConfig = forwardRef<HTMLElement, EnvConfigProps>(function EnvConfig(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-env', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-env">
      <span className="rd-infra__badge">INFRA</span>
      <span className="rd-field__label">Environment config</span>
      <code>{props.envKeys ?? 'DATABASE_URL, API_KEY'}</code>
      {children}
    </section>
  );
});
