// packages/svelte/src/visual/skeleton/LoadingSkeleton.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { LoadingSkeletonProps } from './types';

	type Props = LoadingSkeletonProps & { children?: Snippet };

	let {
		className,
		lines,
		children,
	}: Props = $props();
	const skeletonLines = $derived.by(() => {
		const count = lines ?? 4;
		return Array.from({ length: count }, (_, i) =>
			['rd-skeleton__line', i === 2 ? 'rd-skeleton__line--short' : ''].filter(Boolean).join(' '),
		);
	});
	const rootClass = $derived(['rd-skeleton', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-skeleton">
	{#each skeletonLines as line, i (i)}<span class={line}></span>{/each}
	{@render children?.()}
</section>

// packages/react/src/visual/skeleton/LoadingSkeleton.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface LoadingSkeletonProps {
  lines?: number;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/skeleton — visual.skeleton */
export const LoadingSkeleton = forwardRef<HTMLElement, LoadingSkeletonProps>(function LoadingSkeleton(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-skeleton', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-skeleton">
      {Array.from({ length: props.lines ?? 4 }).map((_, i) => (
        <span key={i} className={['rd-skeleton__line', i === 2 ? 'rd-skeleton__line--short' : ''].filter(Boolean).join(' ')} />
      ))}
      {children}
    </section>
  );
});
