// packages/react/src/visual/input/date-range/DateRangeFilter.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface DateRangeFilterProps {
  label?: string;
  startDate?: string;
  endDate?: string;
  presetLabel?: string;
  onChange?: (range: { startDate: string; endDate: string }) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/input/date-range — visual.input.date-range */
export const DateRangeFilter = forwardRef<HTMLElement, DateRangeFilterProps>(function DateRangeFilter(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-input-date-range', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-input-date-range">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <div className="rd-date-range__controls">
        <input type="date" className="rd-input" value={props.startDate} onChange={(e) => props.onChange?.({ startDate: e.target.value, endDate: props.endDate ?? '' })} />
        <span className="rd-date-range__sep">to</span>
        <input type="date" className="rd-input" value={props.endDate} onChange={(e) => props.onChange?.({ startDate: props.startDate ?? '', endDate: e.target.value })} />
      </div>
      {props.presetLabel ? <span className="rd-date-range__preset">{props.presetLabel}</span> : null}
      {children}
    </section>
  );
});

// packages/angular/src/visual/input/date-range/date-range-filter.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface DateRangeFilterProps {
  label?: string;
  startDate?: string;
  endDate?: string;
  presetLabel?: string;
  onChange?: (range: { startDate: string; endDate: string }) => void;
  className?: string;
}

/** @rosettadash/angular/visual/input/date-range — visual.input.date-range */
@Component({
  selector: 'rd-input-date-range',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-input-date-range'" [ngClass]="rootClass()">
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      <div class="rd-date-range__controls">
        <input type="date" class="rd-input" [value]="startDate() ?? ''" />
        <span class="rd-date-range__sep">to</span>
        <input type="date" class="rd-input" [value]="endDate() ?? ''" />
      </div>
      @if (presetLabel()) { <span class="rd-date-range__preset">{{ presetLabel() }}</span> }
      <ng-content />
    </section>
  `,
})
export class DateRangeFilter {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly startDate = input<string | undefined>(undefined);
  readonly endDate = input<string | undefined>(undefined);
  readonly presetLabel = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-input-date-range', this.className()].filter(Boolean).join(' '),
  );
}
