// packages/svelte/src/infra/server/nuxt/NuxtServerInfra.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { NuxtServerInfraProps } from './types';

	type Props = NuxtServerInfraProps & { children?: Snippet };

	let {
		className,
		label,
		globalPrefix,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-server-nuxt', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-server-nuxt">
	<span class="rd-infra__badge">INFRA</span>
	{#if label}<span class="rd-field__label">{label}</span>{/if}
	{#if globalPrefix}<code>globalPrefix: {globalPrefix}</code>{/if}
	{@render children?.()}
</section>

// packages/react/src/infra/server/nuxt/NuxtServerInfra.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface NuxtServerInfraProps {
  label?: string;
  globalPrefix?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/infra/server/nuxt — infra.server.nuxt */
export const NuxtServerInfra = forwardRef<HTMLElement, NuxtServerInfraProps>(function NuxtServerInfra(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-server-nuxt', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-server-nuxt">
      <span className="rd-infra__badge">INFRA</span>
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      {props.globalPrefix ? <code>globalPrefix: {props.globalPrefix}</code> : null}
      {children}
    </section>
  );
});
