// apps/proof-vue/src/components/BoundTextareaInput.vue
<script setup lang="ts">
defineProps<{
  fieldLabel?: string;
  placeholder?: string;
  value?: string;
  rows?: number;
}>();

const emit = defineEmits<{ 'update:value': [string] }>();
</script>

<template>
  <section class="rd-input-textarea">
    <span v-if="fieldLabel" class="rd-field__label">{{ fieldLabel }}</span>
    <textarea
      class="rd-textarea"
      :rows="rows ?? 4"
      :placeholder="placeholder ?? ''"
      :value="value ?? ''"
      @input="emit('update:value', ($event.target as HTMLTextAreaElement).value)"
    />
  </section>
</template>

// apps/proof-svelte/src/components/BoundTextareaInput.svelte
<script lang="ts">
  let {
    fieldLabel,
    placeholder,
    value = '',
    rows = 4,
    onValueChange,
  }: {
    fieldLabel?: string;
    placeholder?: string;
    value?: string;
    rows?: number;
    onValueChange?: (value: string) => void;
  } = $props();
</script>

<section class="rd-input-textarea">
  {#if fieldLabel}<span class="rd-field__label">{fieldLabel}</span>{/if}
  <textarea
    class="rd-textarea"
    {rows}
    {placeholder}
    {value}
    oninput={(event) => onValueChange?.((event.currentTarget as HTMLTextAreaElement).value)}
  ></textarea>
</section>
