// apps/proof-vue/src/components/Collapsible.vue
<script setup lang="ts">
const props = defineProps<{
  panelTitle?: string;
  panelSummary?: string;
  open?: boolean;
}>();

const emit = defineEmits<{ openChange: [boolean] }>();

function toggle() {
  emit('openChange', !props.open);
}
</script>

<template>
  <section class="rd-collapsible" :class="{ 'is-open': open }">
    <button type="button" class="rd-collapsible__header" :aria-expanded="open ?? false" @click="toggle">
      <span class="rd-collapsible__titles">
        <span class="rd-collapsible__title">{{ panelTitle ?? 'Section' }}</span>
        <span v-if="panelSummary" class="rd-collapsible__summary">{{ panelSummary }}</span>
      </span>
      <span class="rd-collapsible__chevron" aria-hidden="true">{{ open ? '▾' : '▸' }}</span>
    </button>
    <div v-if="open" class="rd-collapsible__panel">
      <slot />
    </div>
  </section>
</template>

// apps/proof-svelte/src/components/Collapsible.svelte
<script lang="ts">
  let {
    panelTitle = 'Section',
    panelSummary,
    open = false,
    class: className,
    onOpenChange,
    children,
  }: {
    panelTitle?: string;
    panelSummary?: string;
    open?: boolean;
    class?: string;
    onOpenChange?: (open: boolean) => void;
    children?: import('svelte').Snippet;
  } = $props();

  function toggle() {
    onOpenChange?.(!open);
  }
</script>

<section class={['rd-collapsible', className].filter(Boolean).join(' ')} class:is-open={open}>
  <button type="button" class="rd-collapsible__header" aria-expanded={open} onclick={toggle}>
    <span class="rd-collapsible__titles">
      <span class="rd-collapsible__title">{panelTitle}</span>
      {#if panelSummary}<span class="rd-collapsible__summary">{panelSummary}</span>{/if}
    </span>
    <span class="rd-collapsible__chevron" aria-hidden="true">{open ? '▾' : '▸'}</span>
  </button>
  {#if open}
    <div class="rd-collapsible__panel">
      {@render children?.()}
    </div>
  {/if}
</section>
