// apps/proof-vue/src/components/ReactMount.vue
<script setup lang="ts">
import { createElement, type ComponentType } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';

const props = defineProps<{
  component: ComponentType<Record<string, unknown>>;
  componentProps?: Record<string, unknown>;
}>();

const host = ref<HTMLDivElement | null>(null);
let root: Root | null = null;

function renderReact() {
  if (!host.value) {
    return;
  }
  if (!root) {
    root = createRoot(host.value);
  }
  root.render(createElement(props.component, props.componentProps ?? {}));
}

onMounted(renderReact);
watch(() => props.componentProps, renderReact, { deep: true });
onBeforeUnmount(() => {
  root?.unmount();
  root = null;
});
</script>

<template>
  <div ref="host" />
</template>

// apps/proof-svelte/src/components/ReactMount.svelte
<script lang="ts">
  import { createElement, type ComponentType } from 'react';
  import { createRoot, type Root } from 'react-dom/client';

  let {
    component,
    componentProps = {},
  }: {
    component: ComponentType<Record<string, unknown>>;
    componentProps?: Record<string, unknown>;
  } = $props();

  let host = $state<HTMLDivElement | null>(null);
  let root: Root | null = null;

  function renderReact() {
    if (!host) {
      return;
    }
    if (!root) {
      root = createRoot(host);
    }
    root.render(createElement(component, { ...componentProps }));
  }

  $effect(() => {
    void component;
    const propsSnapshot = componentProps;
    if (propsSnapshot) {
      for (const key of Object.keys(propsSnapshot)) {
        void propsSnapshot[key];
      }
    }
    renderReact();
  });

  $effect(() => {
    return () => {
      root?.unmount();
      root = null;
    };
  });
</script>

<div bind:this={host}></div>
