// apps/proof-vue/src/components/ScreenWorkbenchMobileToggle.vue
<script setup lang="ts">
defineProps<{
  mobileView: 'preview' | 'source';
}>();

const emit = defineEmits<{
  change: ['preview' | 'source'];
}>();
</script>

<template>
  <div class="da-workbench__mobile-toggle" role="tablist" aria-label="Preview or source">
    <button
      type="button"
      role="tab"
      :aria-selected="mobileView === 'preview'"
      :class="{ 'is-active': mobileView === 'preview' }"
      @click="emit('change', 'preview')"
    >
      Atlas preview
    </button>
    <button
      type="button"
      role="tab"
      :aria-selected="mobileView === 'source'"
      :class="{ 'is-active': mobileView === 'source' }"
      @click="emit('change', 'source')"
    >
      Component source
    </button>
  </div>
</template>

// apps/proof-svelte/src/components/ScreenWorkbenchMobileToggle.svelte
<script lang="ts">
  let {
    mobileView,
    onChange,
  }: {
    mobileView: 'preview' | 'source';
    onChange?: (view: 'preview' | 'source') => void;
  } = $props();
</script>

<div class="da-workbench__mobile-toggle" role="tablist" aria-label="Preview or source">
  <button
    type="button"
    role="tab"
    aria-selected={mobileView === 'preview'}
    class:is-active={mobileView === 'preview'}
    onclick={() => onChange?.('preview')}
  >
    Atlas preview
  </button>
  <button
    type="button"
    role="tab"
    aria-selected={mobileView === 'source'}
    class:is-active={mobileView === 'source'}
    onclick={() => onChange?.('source')}
  >
    Component source
  </button>
</div>
