// packages/react/src/layout/modal/ModalLayout.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface ModalLayoutProps {
  title?: string;
  body?: string;
  confirmLabel?: string;
  open?: boolean;
  onConfirm?: () => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/layout/modal — layout.modal */
export const ModalLayout = forwardRef<HTMLElement, ModalLayoutProps>(function ModalLayout(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-modal', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-modal" role="dialog" aria-modal="true">
      <div className="rd-modal__dialog">
        <span className="rd-modal__title">{props.title ?? 'Dialog'}</span>
        {props.body ? <p className="rd-modal__body">{props.body}</p> : null}
        <button type="button" className="rd-modal__confirm" onClick={() => props.onConfirm?.()}>{props.confirmLabel ?? 'Confirm'}</button>
        {children}
      </div>
    </section>
  );
});

// packages/angular/src/layout/modal/modal-layout.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface ModalLayoutProps {
  title?: string;
  body?: string;
  confirmLabel?: string;
  open?: boolean;
  onConfirm?: () => void;
  className?: string;
}

/** @rosettadash/angular/layout/modal — layout.modal */
@Component({
  selector: 'rd-modal',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-modal'" [ngClass]="rootClass()" role="dialog" aria-modal="true">
      <div class="rd-modal__dialog">
        <span class="rd-modal__title">{{ title() ?? 'Dialog' }}</span>
        @if (body()) { <p class="rd-modal__body">{{ body() }}</p> }
        <button type="button" class="rd-modal__confirm">{{ confirmLabel() ?? 'Confirm' }}</button>
        <ng-content />
      </div>
    </section>
  `,
})
export class ModalLayout {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly body = input<string | undefined>(undefined);
  readonly confirmLabel = input<string | undefined>(undefined);
  readonly open = input<boolean | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-modal', this.className()].filter(Boolean).join(' '),
  );
}
