// packages/react/src/visual/table/DataTable.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface DataTableRow {
  id: string;
  name?: string;
  status?: string;
  amount?: number;
  date?: string;
  [key: string]: string | number | undefined;
}

export interface DataTableProps {
  title?: string;
  rows?: DataTableRow[];
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/table — visual.table */
export const DataTable = forwardRef<HTMLElement, DataTableProps>(function DataTable(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-table', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-table">
      <header className="rd-table__header"><span>{props.title ?? 'Data table'}</span></header>
      <table className="rd-table__table">
        <thead><tr><th>Name</th><th>Status</th><th>Amount</th><th>Date</th></tr></thead>
        <tbody>
          {(props.rows ?? []).map((row) => (
            <tr key={row.id}><td>{row.name}</td><td>{row.status}</td><td>{row.amount}</td><td>{row.date}</td></tr>
          ))}
        </tbody>
      </table>
      {children}
    </section>
  );
});

// packages/angular/src/visual/table/data-table.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface DataTableRow {
  id: string;
  name?: string;
  status?: string;
  amount?: number;
  date?: string;
  [key: string]: string | number | undefined;
}

export interface DataTableProps {
  title?: string;
  rows?: DataTableRow[];
  className?: string;
}

/** @rosettadash/angular/visual/table — visual.table */
@Component({
  selector: 'rd-table',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-table'" [ngClass]="rootClass()">
      <header class="rd-table__header"><span>{{ title() ?? 'Data table' }}</span></header>
      <table class="rd-table__table">
        <thead><tr><th>Name</th><th>Status</th><th>Amount</th><th>Date</th></tr></thead>
        <tbody>
          @for (row of rows() ?? []; track row.id) {
            <tr><td>{{ row.name }}</td><td>{{ row.status }}</td><td>{{ row.amount }}</td><td>{{ row.date }}</td></tr>
          }
        </tbody>
      </table>
      <ng-content />
    </section>
  `,
})
export class DataTable {
  readonly className = input<string | undefined>(undefined);
  readonly name = input<string | undefined>(undefined);
  readonly status = input<string | undefined>(undefined);
  readonly amount = input<number | undefined>(undefined);
  readonly date = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly rows = input<DataTableRow[] | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-table', this.className()].filter(Boolean).join(' '),
  );
}
