// packages/react/src/visual/input/checkbox/CheckboxInput.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface CheckboxInputProps {
  label?: string;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/input/checkbox — visual.input.checkbox */
export const CheckboxInput = forwardRef<HTMLElement, CheckboxInputProps>(function CheckboxInput(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-input-checkbox', className].filter(Boolean).join(' ');

  return (
    <label ref={ref as React.Ref<HTMLLabelElement>} className={[rootClass, 'rd-field--checkbox'].join(' ')} style={style} data-testid="rd-input-checkbox">
      <input
        type="checkbox"
        className="rd-checkbox"
        checked={props.checked}
        defaultChecked={props.defaultChecked}
        onChange={(e) => props.onChange?.(e.target.checked)}
      />
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      {children}
    </label>
  );
});

// packages/angular/src/visual/input/checkbox/checkbox-input.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface CheckboxInputProps {
  label?: string;
  checked?: boolean;
  defaultChecked?: boolean;
  onChange?: (checked: boolean) => void;
  className?: string;
}

/** @rosettadash/angular/visual/input/checkbox — visual.input.checkbox */
@Component({
  selector: 'rd-input-checkbox',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [attr.data-testid]="'rd-input-checkbox'" [ngClass]="rootClass() + ' rd-field--checkbox'">
      <input type="checkbox" class="rd-checkbox" [checked]="checked() ?? defaultChecked() ?? false" />
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      <ng-content />
    </label>
  `,
})
export class CheckboxInput {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly checked = input<boolean | undefined>(undefined);
  readonly defaultChecked = input<boolean | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-input-checkbox', this.className()].filter(Boolean).join(' '),
  );
}
