// packages/react/src/logic/timer/Timer.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface TimerProps {
  label?: string;
  mode?: 'interval' | 'countdown';
  intervalMs?: number;
  tickCount?: number;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/logic/timer — logic.timer */
export const Timer = forwardRef<HTMLElement, TimerProps>(function Timer(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-timer', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-timer">
      {props.label ? <span className="rd-timer__label">{props.label}</span> : null}
      <span className="rd-timer__value">{props.tickCount ?? 0} ticks</span>
      {children}
    </section>
  );
});

// packages/svelte/src/logic/timer/Timer.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { TimerProps } from './types';

	type Props = TimerProps & { children?: Snippet };

	let {
		className,
		label,
		mode,
		intervalMs,
		tickCount,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-timer', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-timer">
	{#if label}<span class="rd-timer__label">{label}</span>{/if}
	<span class="rd-timer__value">{tickCount ?? 0} ticks</span>
	{@render children?.()}
</section>
