// packages/react/src/visual/detail/DetailPanel.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface DetailPanelProps {
  title?: string;
  emptyMessage?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/detail — visual.detail */
export const DetailPanel = forwardRef<HTMLElement, DetailPanelProps>(function DetailPanel(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-detail', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-detail">
      <header className="rd-detail__header"><span>{props.title ?? 'Details'}</span></header>
      <p className="rd-detail__empty">{props.emptyMessage ?? 'Select a row to view details'}</p>
      {children}
    </section>
  );
});

// packages/svelte/src/visual/detail/DetailPanel.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { DetailPanelProps } from './types';

	type Props = DetailPanelProps & { children?: Snippet };

	let {
		className,
		title,
		emptyMessage,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-detail', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-detail">
	<header class="rd-detail__header"><span>{title ?? 'Details'}</span></header>
	<p class="rd-detail__empty">{emptyMessage ?? 'Select a row to view details'}</p>
	{@render children?.()}
</section>
