// apps/proof-react/src/components/AtlasContextControls.tsx
import { DEFAULT_APP_LOCALES, GEO_MAP_PROVIDERS, MOCK_DESTINATIONS, type GeoMapProvider } from '@destination-atlas';
import { SelectInput } from '@rosettadash/react/visual/input/select';
import { ATLAS_USER_ROLES, type AtlasUserRole } from '../lib/roles';
import { localizedDestinationName } from '../lib/atlas-utils';
import type { SettingFieldTarget } from '../lib/settings-highlight';

export interface AtlasContextControlsProps {
  locale: string;
  setLocale: (locale: string) => void;
  userRole: AtlasUserRole;
  setUserRole: (role: AtlasUserRole) => void;
  mapProvider: GeoMapProvider;
  setMapProvider: (provider: GeoMapProvider) => void;
  selectedId: string;
  setSelectedId: (id: string) => void;
  highlightField?: SettingFieldTarget | null;
  className?: string;
}

const ROLE_HINT = 'Preview permissions for gated screens.';
const LOCALE_HINT = 'Base locale for developer-owned destination labels.';
const MAP_HINT = 'Default 2D map engine for the Map screen.';
const SELECTED_HINT = 'Active destination across tabs and URL state.';

export function AtlasContextControls({
  locale,
  setLocale,
  userRole,
  setUserRole,
  mapProvider,
  setMapProvider,
  selectedId,
  setSelectedId,
  highlightField,
  className,
}: AtlasContextControlsProps) {
  const rootClass = ['da-context-grid', className].filter(Boolean).join(' ');

  const localeOptions = DEFAULT_APP_LOCALES.map((entry) => ({
    value: entry.code,
    label: entry.nativeLabel ? `${entry.label} (${entry.nativeLabel})` : entry.label,
  }));

  const mapOptions = GEO_MAP_PROVIDERS.map((entry) => ({
    value: entry.id,
    label: entry.label,
  }));

  const destinationOptions = MOCK_DESTINATIONS.map((dest) => ({
    value: dest.id,
    label: localizedDestinationName(dest, locale),
  }));

  const fields: Array<{
    key: SettingFieldTarget;
    label: string;
    hint: string;
    value: string;
    options: Array<{ value: string; label: string }>;
    onChange: (value: string) => void;
  }> = [
    {
      key: 'role',
      label: 'Role',
      hint: ROLE_HINT,
      value: userRole,
      options: ATLAS_USER_ROLES.map((entry) => ({ value: entry.id, label: entry.label })),
      onChange: (value: string) => setUserRole(value as AtlasUserRole),
    },
    {
      key: 'locale',
      label: 'App locale',
      hint: LOCALE_HINT,
      value: locale,
      options: localeOptions,
      onChange: setLocale,
    },
    {
      key: 'map',
      label: 'Map provider',
      hint: MAP_HINT,
      value: mapProvider,
      options: mapOptions,
      onChange: (value: string) => setMapProvider(value as GeoMapProvider),
    },
    {
      key: 'selected',
      label: 'Selected',
      hint: SELECTED_HINT,
      value: selectedId,
      options: destinationOptions,
      onChange: setSelectedId,
    },
  ];

  return (
    <div className={rootClass}>
      {fields.map((field) => (
        <div
          key={field.key}
          data-setting={field.key}
          className={[
            'da-context-grid__cell',
            highlightField === field.key ? 'rd-highlight-target' : undefined,
          ]
            .filter(Boolean)
            .join(' ')}
        >
          <SelectInput
            label={field.label}
            options={field.options}
            value={field.value}
            onChange={field.onChange}
          />
          <p className="da-context-grid__hint">{field.hint}</p>
        </div>
      ))}
    </div>
  );
}

// apps/proof-vue/src/components/AtlasContextControls.vue
<script setup lang="ts">
import { DEFAULT_APP_LOCALES, GEO_MAP_PROVIDERS, MOCK_DESTINATIONS, type GeoMapProvider } from '@destination-atlas';
import BoundSelectInput from './BoundSelectInput.vue';
import { ATLAS_USER_ROLES, type AtlasUserRole } from '../lib/roles';
import { localizedDestinationName } from '../lib/atlas-utils';
import type { SettingFieldTarget } from '../lib/settings-highlight';

const props = defineProps<{
  locale: string;
  userRole: AtlasUserRole;
  mapProvider: GeoMapProvider;
  selectedId: string;
  highlightField?: SettingFieldTarget | null;
  class?: string;
}>();

const emit = defineEmits<{
  'update:locale': [string];
  'update:userRole': [AtlasUserRole];
  'update:mapProvider': [GeoMapProvider];
  'update:selectedId': [string];
}>();

const localeOptions = DEFAULT_APP_LOCALES.map((entry) => ({
  value: entry.code,
  label: entry.nativeLabel ? `${entry.label} (${entry.nativeLabel})` : entry.label,
}));

const mapOptions = GEO_MAP_PROVIDERS.map((entry) => ({ value: entry.id, label: entry.label }));

const destinationOptions = () =>
  MOCK_DESTINATIONS.map((dest) => ({
    value: dest.id,
    label: localizedDestinationName(dest, props.locale),
  }));

const fields = () => [
  {
    key: 'role' as const,
    label: 'Role',
    hint: 'Preview permissions for gated screens.',
    value: props.userRole,
    options: ATLAS_USER_ROLES.map((entry) => ({ value: entry.id, label: entry.label })),
    onChange: (value: string) => emit('update:userRole', value as AtlasUserRole),
  },
  {
    key: 'locale' as const,
    label: 'App locale',
    hint: 'Base locale for developer-owned destination labels.',
    value: props.locale,
    options: localeOptions,
    onChange: (value: string) => emit('update:locale', value),
  },
  {
    key: 'map' as const,
    label: 'Map provider',
    hint: 'Default 2D map engine for the Map screen.',
    value: props.mapProvider,
    options: mapOptions,
    onChange: (value: string) => emit('update:mapProvider', value as GeoMapProvider),
  },
  {
    key: 'selected' as const,
    label: 'Selected',
    hint: 'Active destination across tabs and URL state.',
    value: props.selectedId,
    options: destinationOptions(),
    onChange: (value: string) => emit('update:selectedId', value),
  },
];
</script>

<template>
  <div :class="['da-context-grid', $props.class].filter(Boolean)">
    <div
      v-for="field in fields()"
      :key="field.key"
      :data-setting="field.key"
      :class="['da-context-grid__cell', highlightField === field.key ? 'rd-highlight-target' : undefined].filter(Boolean)"
    >
      <BoundSelectInput
        :field-label="field.label"
        :options="field.options"
        :value="field.value"
        @update:value="field.onChange"
      />
      <p class="da-context-grid__hint">{{ field.hint }}</p>
    </div>
  </div>
</template>
