// apps/proof-svelte/src/components/BoundTextInput.svelte
<script lang="ts">
  let {
    fieldLabel,
    placeholder,
    value = '',
    inputType = 'text',
    onValueChange,
  }: {
    fieldLabel?: string;
    placeholder?: string;
    value?: string;
    inputType?: 'text' | 'password';
    onValueChange?: (value: string) => void;
  } = $props();
</script>

<section class="rd-input-text">
  {#if fieldLabel}<span class="rd-field__label">{fieldLabel}</span>{/if}
  <input
    class="rd-input"
    type={inputType}
    {placeholder}
    {value}
    oninput={(event) => onValueChange?.((event.currentTarget as HTMLInputElement).value)}
  />
</section>

// apps/proof-vue/src/components/BoundTextInput.vue
<script setup lang="ts">
defineProps<{
  fieldLabel?: string;
  placeholder?: string;
  value?: string;
  inputType?: 'text' | 'password';
}>();

const emit = defineEmits<{ 'update:value': [string] }>();
</script>

<template>
  <section class="rd-input-text">
    <span v-if="fieldLabel" class="rd-field__label">{{ fieldLabel }}</span>
    <input
      class="rd-input"
      :type="inputType ?? 'text'"
      :placeholder="placeholder ?? ''"
      :value="value ?? ''"
      @input="emit('update:value', ($event.target as HTMLInputElement).value)"
    />
  </section>
</template>
