// packages/react/src/visual/destination/destination-select-list/DestinationSelectList.tsx
import { forwardRef, type CSSProperties } from 'react';

export interface DestinationSelectItem {
  id: string;
  label: string;
  meta?: string;
}

export interface DestinationSelectListProps {
  title?: string;
  items: DestinationSelectItem[];
  selectedId?: string;
  onSelect?: (id: string) => void;
  className?: string;
  style?: CSSProperties;
}

/** @rosettadash/react/visual/destination/destination-select-list — selectable destination sidebar list */
export const DestinationSelectList = forwardRef<HTMLElement, DestinationSelectListProps>(
  function DestinationSelectList({ title = 'Destinations', items, selectedId, onSelect, className, style }, ref) {
    const rootClass = ['rd-destination-list', className].filter(Boolean).join(' ');

    return (
      <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} aria-label={title}>
        <header className="rd-destination-list__header">
          <h3>{title}</h3>
          <span className="rd-destination-list__count">{items.length}</span>
        </header>
        <ul className="rd-destination-list__items">
          {items.map((item) => {
            const selected = item.id === selectedId;
            return (
              <li
                key={item.id}
                className={['rd-destination-list__item', selected ? 'rd-destination-list__item--selected' : '']
                  .filter(Boolean)
                  .join(' ')}
              >
                <button
                  type="button"
                  className="rd-destination-list__button"
                  aria-current={selected ? 'true' : undefined}
                  onClick={() => onSelect?.(item.id)}
                >
                  <span className="rd-destination-list__label">{item.label}</span>
                  {item.meta ? <span className="rd-destination-list__meta">{item.meta}</span> : null}
                </button>
              </li>
            );
          })}
        </ul>
      </section>
    );
  },
);

// apps/proof-vue/src/components/DestinationSelectList.vue
<script setup lang="ts">
export interface DestinationSelectItem {
  id: string;
  label: string;
  meta?: string;
}

defineProps<{
  listTitle?: string;
  items: DestinationSelectItem[];
  selectedId?: string;
}>();

const emit = defineEmits<{ select: [string] }>();
</script>

<template>
  <section class="rd-destination-list" :aria-label="listTitle ?? 'Destinations'">
    <header class="rd-destination-list__header">
      <h3>{{ listTitle ?? 'Destinations' }}</h3>
      <span class="rd-destination-list__count">{{ items.length }}</span>
    </header>
    <ul class="rd-destination-list__items">
      <li
        v-for="item in items"
        :key="item.id"
        class="rd-destination-list__item"
        :class="{ 'rd-destination-list__item--selected': item.id === selectedId }"
      >
        <button
          type="button"
          class="rd-destination-list__button"
          :aria-current="item.id === selectedId ? 'true' : undefined"
          @click="emit('select', item.id)"
        >
          <span class="rd-destination-list__label">{{ item.label }}</span>
          <span v-if="item.meta" class="rd-destination-list__meta">{{ item.meta }}</span>
        </button>
      </li>
    </ul>
  </section>
</template>
