// apps/proof-angular/src/components/maps-panel-nav.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import type { MapsPanelId } from '@rosettadash/core';

@Component({
  selector: 'da-maps-panel-nav',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <nav class="da-tabbar da-maps-tabbar" aria-label="Map views">
      <button
        type="button"
        class="da-tabbar__tab da-tabbar__tab--left"
        [attr.aria-current]="panel() === 'map' ? 'page' : null"
        (click)="selectPanel.emit('map')"
      >
        Map
      </button>
      <button
        type="button"
        class="da-tabbar__tab da-tabbar__tab--right"
        [attr.aria-current]="panel() === 'globe' ? 'page' : null"
        (click)="selectPanel.emit('globe')"
      >
        Globe
      </button>
    </nav>
  `,
})
export class MapsPanelNavComponent {
  readonly panel = input.required<MapsPanelId>();
  readonly selectPanel = output<MapsPanelId>();
}

// apps/proof-vue/src/components/MapsPanelNav.vue
<script setup lang="ts">
import type { MapsPanelId } from '@rosettadash/core';

defineProps<{ panel: MapsPanelId }>();
const emit = defineEmits<{ selectPanel: [MapsPanelId] }>();

const panels: Array<{ id: MapsPanelId; label: string; align: 'left' | 'right' }> = [
  { id: 'map', label: 'Map', align: 'left' },
  { id: 'globe', label: 'Globe', align: 'right' },
];
</script>

<template>
  <nav class="da-tabbar da-maps-tabbar" aria-label="Map views">
    <button
      v-for="entry in panels"
      :key="entry.id"
      type="button"
      :class="['da-tabbar__tab', `da-tabbar__tab--${entry.align}`]"
      :aria-current="panel === entry.id ? 'page' : undefined"
      @click="emit('selectPanel', entry.id)"
    >
      {{ entry.label }}
    </button>
  </nav>
</template>
