// apps/proof-angular/src/components/role-gate-panel.component.ts
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import { roleAllows, roleLabel, type AtlasUserRole } from '../lib/roles';

@Component({
  selector: 'da-role-gate-panel',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (allowed()) {
      <section class="rd-role-gate">
        @if (gateLabel()) {
          <span class="rd-field__label">{{ gateLabel() }}</span>
        }
        @if (statusText()) {
          <p class="rd-role-gate__status">{{ statusText() }}</p>
        }
        <ng-content />
      </section>
    } @else {
      <p class="rd-role-gate__status">{{ hiddenMessage() }}</p>
    }
  `,
})
export class RoleGatePanelComponent {
  readonly gateLabel = input<string>();
  readonly currentRole = input.required<AtlasUserRole>();
  readonly allowedRoles = input<string[]>(['admin']);
  readonly statusText = input<string>();
  readonly hiddenStatusText = input<string>();

  readonly allowed = computed(() => roleAllows(this.currentRole(), this.allowedRoles()));

  readonly hiddenMessage = computed(() => {
    if (this.hiddenStatusText()) {
      return this.hiddenStatusText();
    }
    return `This section is hidden for ${roleLabel(this.currentRole())} role.`;
  });
}

// apps/proof-vue/src/components/RoleGatePanel.vue
<script setup lang="ts">
import { computed } from 'vue';
import { roleAllows, roleLabel, type AtlasUserRole } from '../lib/roles';

const props = withDefaults(
  defineProps<{
    gateLabel?: string;
    currentRole: AtlasUserRole;
    allowedRoles?: string[];
    statusText?: string;
    hiddenStatusText?: string;
  }>(),
  {
    allowedRoles: () => ['admin'],
  },
);

const allowed = computed(() => roleAllows(props.currentRole, props.allowedRoles));
const hiddenMessage = computed(
  () => props.hiddenStatusText ?? `This section is hidden for ${roleLabel(props.currentRole)} role.`,
);
</script>

<template>
  <section v-if="allowed" class="rd-role-gate">
    <span v-if="gateLabel" class="rd-field__label">{{ gateLabel }}</span>
    <p v-if="statusText" class="rd-role-gate__status">{{ statusText }}</p>
    <slot />
  </section>
  <p v-else class="rd-role-gate__status">{{ hiddenMessage }}</p>
</template>
