// packages/react/src/visual/chart/venn/VennOverlapChart.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface VennSet {
  id: string;
  label: string;
  count: number;
  color?: string;
}

export interface VennOverlap {
  setIds: string[];
  count: number;
  label?: string;
}

export interface VennOverlapChartProps {
  title?: string;
  sets?: VennSet[];
  overlaps?: VennOverlap[];
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

const DEFAULT_COLORS = ['#3b82f6', '#f59e0b', '#10b981'];

const FALLBACK_SETS: VennSet[] = [
  { id: 'a', label: 'Set A', count: 100 },
  { id: 'b', label: 'Set B', count: 80 },
];

const FALLBACK_OVERLAPS: VennOverlap[] = [{ setIds: ['a', 'b'], count: 25 }];

/** @rosettadash/react/visual/chart/venn — SVG Venn / overlap diagram */
export const VennOverlapChart = forwardRef<HTMLElement, VennOverlapChartProps>(function VennOverlapChart(
  { title, sets, overlaps, className, style, children },
  ref,
) {
  const rootClass = ['rd-chart-venn', className].filter(Boolean).join(' ');
  const chartSets = sets?.length ? sets : FALLBACK_SETS;
  const chartOverlaps = overlaps ?? FALLBACK_OVERLAPS;
  const threeWay = chartSets.length >= 3;

  return (
    <section
      ref={ref as React.RefObject<HTMLElement>}
      className={rootClass}
      style={style}
      data-testid="rd-chart-venn"
      role="img"
      aria-label={title ?? 'Venn overlap chart'}
    >
      <header className="rd-chart-venn__header">
        <span>{title ?? 'Overlap diagram'}</span>
      </header>
      <div className="rd-chart-venn__body">
        <svg viewBox="0 0 420 260" className="rd-chart-venn__svg" aria-hidden="true">
          {threeWay ? (
            <>
              <circle cx="150" cy="120" r="72" className="rd-chart-venn__circle" style={{ fill: chartSets[0]?.color ?? DEFAULT_COLORS[0] }} />
              <circle cx="270" cy="120" r="72" className="rd-chart-venn__circle" style={{ fill: chartSets[1]?.color ?? DEFAULT_COLORS[1] }} />
              <circle cx="210" cy="170" r="72" className="rd-chart-venn__circle" style={{ fill: chartSets[2]?.color ?? DEFAULT_COLORS[2] }} />
              <text x="95" y="75" className="rd-chart-venn__set-label">{chartSets[0]?.label}</text>
              <text x="300" y="75" className="rd-chart-venn__set-label">{chartSets[1]?.label}</text>
              <text x="210" y="230" className="rd-chart-venn__set-label" textAnchor="middle">{chartSets[2]?.label}</text>
            </>
          ) : (
            <>
              <circle cx="155" cy="130" r="78" className="rd-chart-venn__circle" style={{ fill: chartSets[0]?.color ?? DEFAULT_COLORS[0] }} />
              <circle cx="265" cy="130" r="78" className="rd-chart-venn__circle" style={{ fill: chartSets[1]?.color ?? DEFAULT_COLORS[1] }} />
              <text x="105" y="130" className="rd-chart-venn__set-label">{chartSets[0]?.label}</text>
              <text x="315" y="130" className="rd-chart-venn__set-label" textAnchor="end">{chartSets[1]?.label}</text>
            </>
          )}
        </svg>
        <ul className="rd-chart-venn__legend">
          {chartSets.map((set, index) => (
            <li key={set.id}>
              <span className="rd-chart-venn__swatch" style={{ background: set.color ?? DEFAULT_COLORS[index % DEFAULT_COLORS.length] }} />
              <span>{set.label}</span>
              <strong>{set.count.toLocaleString()}</strong>
            </li>
          ))}
          {chartOverlaps.map((overlap) => (
            <li key={overlap.setIds.join('-')}>
              <span className="rd-chart-venn__swatch rd-chart-venn__swatch--overlap" />
              <span>{overlap.label ?? overlap.setIds.join(' ∩ ')}</span>
              <strong>{overlap.count.toLocaleString()}</strong>
            </li>
          ))}
        </ul>
      </div>
      {children}
    </section>
  );
});

// apps/proof-vue/src/components/VennOverlapChart.vue
<script setup lang="ts">
export interface VennSet {
  id: string;
  label: string;
  count: number;
  color?: string;
}

export interface VennOverlap {
  setIds: string[];
  count: number;
  label?: string;
}

const DEFAULT_COLORS = ['#3b82f6', '#f59e0b', '#10b981'];

const props = defineProps<{
  title?: string;
  sets?: VennSet[];
  overlaps?: VennOverlap[];
}>();

function threeWay() {
  return (props.sets ?? []).length >= 3;
}

function colorAt(index: number) {
  const set = props.sets?.[index];
  return set?.color ?? DEFAULT_COLORS[index % DEFAULT_COLORS.length];
}
</script>

<template>
  <section class="rd-chart-venn" data-testid="rd-chart-venn" role="img" :aria-label="title ?? 'Overlap diagram'">
    <header class="rd-chart-venn__header">
      <span>{{ title ?? 'Overlap diagram' }}</span>
    </header>
    <div class="rd-chart-venn__body">
      <svg viewBox="0 0 420 260" class="rd-chart-venn__svg" aria-hidden="true">
        <template v-if="threeWay()">
          <circle cx="150" cy="120" r="72" class="rd-chart-venn__circle" :fill="colorAt(0)" />
          <circle cx="270" cy="120" r="72" class="rd-chart-venn__circle" :fill="colorAt(1)" />
          <circle cx="210" cy="170" r="72" class="rd-chart-venn__circle" :fill="colorAt(2)" />
          <text x="95" y="75" class="rd-chart-venn__set-label">{{ sets?.[0]?.label }}</text>
          <text x="300" y="75" class="rd-chart-venn__set-label">{{ sets?.[1]?.label }}</text>
          <text x="210" y="230" class="rd-chart-venn__set-label" text-anchor="middle">{{ sets?.[2]?.label }}</text>
        </template>
        <template v-else>
          <circle cx="155" cy="130" r="78" class="rd-chart-venn__circle" :fill="colorAt(0)" />
          <circle cx="265" cy="130" r="78" class="rd-chart-venn__circle" :fill="colorAt(1)" />
          <text x="105" y="130" class="rd-chart-venn__set-label">{{ sets?.[0]?.label }}</text>
          <text x="315" y="130" class="rd-chart-venn__set-label" text-anchor="end">{{ sets?.[1]?.label }}</text>
        </template>
      </svg>
      <ul class="rd-chart-venn__legend">
        <li v-for="(set, index) in sets ?? []" :key="set.id">
          <span class="rd-chart-venn__swatch" :style="{ background: set.color ?? colorAt(index) }" />
          <span>{{ set.label }}</span>
          <strong>{{ set.count.toLocaleString() }}</strong>
        </li>
        <li v-for="overlap in overlaps ?? []" :key="overlap.setIds.join('-')">
          <span class="rd-chart-venn__swatch rd-chart-venn__swatch--overlap" />
          <span>{{ overlap.label ?? overlap.setIds.join(' ∩ ') }}</span>
          <strong>{{ overlap.count.toLocaleString() }}</strong>
        </li>
      </ul>
    </div>
  </section>
</template>
