// tools/storybook-shared/dom-story-host.tsx
import { createElement, useEffect, useRef } from 'react';
import { attachDomStory, clearDomStoryHost } from './dom-story-mount.js';

export interface DomStoryHostProps {
  mount: () => HTMLElement;
}

/** Mount shared catalog/composition HTMLElement trees inside React Storybook stories. */
export function DomStoryHost({ mount }: DomStoryHostProps) {
  const hostRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const host = hostRef.current;
    if (!host) {
      return;
    }
    attachDomStory(host, mount);
    return () => {
      clearDomStoryHost(host);
    };
  }, [mount]);

  return createElement('div', { ref: hostRef, className: 'rd-dom-story-host' });
}

export function renderDomStory(mount: () => HTMLElement) {
  return () => createElement(DomStoryHost, { mount });
}

// tools/storybook-shared/DomStoryHost.svelte
<script lang="ts">
  import { attachDomStory, clearDomStoryHost } from './dom-story-mount.js';

  let { mount }: { mount: () => HTMLElement } = $props();

  let host = $state<HTMLDivElement | null>(null);

  $effect(() => {
    if (!host) {
      return;
    }
    attachDomStory(host, mount);
    return () => {
      clearDomStoryHost(host);
    };
  });
</script>

<div bind:this={host} class="rd-dom-story-host"></div>
