// tools/storybook-shared/dom-story-host.component.ts
import {
  AfterViewInit,
  Component,
  ElementRef,
  Input,
  OnChanges,
  OnDestroy,
  ViewChild,
} from '@angular/core';
import { attachDomStory, clearDomStoryHost } from './dom-story-mount.js';

@Component({
  selector: 'rd-dom-story-host',
  standalone: true,
  template: '<div #host class="rd-dom-story-host"></div>',
})
export class DomStoryHostComponent implements AfterViewInit, OnChanges, OnDestroy {
  @Input({ required: true }) mount!: () => HTMLElement;
  @ViewChild('host', { static: true }) hostRef!: ElementRef<HTMLDivElement>;

  ngAfterViewInit(): void {
    this.renderMount();
  }

  ngOnChanges(): void {
    if (this.hostRef) {
      this.renderMount();
    }
  }

  ngOnDestroy(): void {
    clearDomStoryHost(this.hostRef.nativeElement);
  }

  private renderMount(): void {
    attachDomStory(this.hostRef.nativeElement, this.mount);
  }
}

// tools/storybook-shared/DomStoryHost.svelte
<script lang="ts">
  import { attachDomStory, clearDomStoryHost } from './dom-story-mount.js';

  let { mount }: { mount: () => HTMLElement } = $props();

  let host = $state<HTMLDivElement | null>(null);

  $effect(() => {
    if (!host) {
      return;
    }
    attachDomStory(host, mount);
    return () => {
      clearDomStoryHost(host);
    };
  });
</script>

<div bind:this={host} class="rd-dom-story-host"></div>
