// apps/proof-vue/src/components/FilterSummary.vue
<script setup lang="ts">
export interface FilterSummaryChip {
  label: string;
  value: string;
}

const props = withDefaults(
  defineProps<{
    summaryTitle?: string;
    count?: number;
    countNoun?: string;
    chips?: FilterSummaryChip[];
    hint?: string;
  }>(),
  {
    summaryTitle: 'Filter results',
    count: 0,
    countNoun: 'result',
    chips: () => [],
  },
);

const countLabel = () => (props.count === 1 ? props.countNoun : `${props.countNoun}s`);
</script>

<template>
  <section class="rd-filter-summary" data-testid="rd-filter-summary" aria-live="polite">
    <div class="rd-filter-summary__header">
      <strong>{{ summaryTitle }}</strong>
      <span class="rd-filter-summary__count">{{ count }} {{ countLabel() }}</span>
    </div>
    <dl class="rd-filter-summary__chips">
      <div v-for="chip in chips" :key="chip.label">
        <dt>{{ chip.label }}</dt>
        <dd>{{ chip.value }}</dd>
      </div>
    </dl>
    <p v-if="hint" class="rd-filter-summary__hint">{{ hint }}</p>
  </section>
</template>

// packages/react/src/visual/filter/filter-summary/FilterSummary.tsx
import { forwardRef, type CSSProperties } from 'react';

export interface FilterSummaryChip {
  label: string;
  value: string;
}

export interface FilterSummaryProps {
  title?: string;
  count: number;
  countNoun?: string;
  chips: FilterSummaryChip[];
  hint?: string;
  className?: string;
  style?: CSSProperties;
}

/** @rosettadash/react/visual/filter/filter-summary — visual.filter.filter-summary */
export const FilterSummary = forwardRef<HTMLElement, FilterSummaryProps>(function FilterSummary(
  { title = 'Filter results', count, countNoun = 'result', chips, hint, className, style },
  ref,
) {
  const rootClass = ['rd-filter-summary', className].filter(Boolean).join(' ');
  const plural = count === 1 ? countNoun : `${countNoun}s`;

  return (
    <section
      ref={ref as React.RefObject<HTMLElement>}
      className={rootClass}
      style={style}
      data-testid="rd-filter-summary"
      aria-live="polite"
    >
      <div className="rd-filter-summary__header">
        <strong>{title}</strong>
        <span className="rd-filter-summary__count">
          {count} {plural}
        </span>
      </div>
      <dl className="rd-filter-summary__chips">
        {chips.map((chip) => (
          <div key={chip.label}>
            <dt>{chip.label}</dt>
            <dd>{chip.value}</dd>
          </div>
        ))}
      </dl>
      {hint ? <p className="rd-filter-summary__hint">{hint}</p> : null}
    </section>
  );
});
