// packages/react/src/domain/role-gate/RoleGate.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface RoleGateProps {
  label?: string;
  allowedRoles?: string[];
  statusText?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/domain/role-gate — domain.role-gate */
export const RoleGate = forwardRef<HTMLElement, RoleGateProps>(function RoleGate(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-role-gate', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-role-gate">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <p className="rd-role-gate__status">{props.statusText ?? 'Visible'}</p>
      {props.allowedRoles?.length ? <code>{JSON.stringify(props.allowedRoles)}</code> : null}
      {children}
    </section>
  );
});

// packages/angular/src/domain/role-gate/role-gate.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface RoleGateProps {
  label?: string;
  allowedRoles?: string[];
  statusText?: string;
  className?: string;
}

/** @rosettadash/angular/domain/role-gate — domain.role-gate */
@Component({
  selector: 'rd-role-gate',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-role-gate'" [ngClass]="rootClass()">
      @if (label()) { <span class="rd-field__label">{{ label() }}</span> }
      <p class="rd-role-gate__status">{{ statusText() ?? 'Visible' }}</p>
      <ng-content />
    </section>
  `,
})
export class RoleGate {
  readonly className = input<string | undefined>(undefined);
  readonly label = input<string | undefined>(undefined);
  readonly allowedRoles = input<string[] | undefined>(undefined);
  readonly statusText = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-role-gate', this.className()].filter(Boolean).join(' '),
  );
}
