// packages/react/src/visual/plugin/metric-chip/MetricChip.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface MetricChipProps {
  chipLabel?: string;
  chipValue?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/plugin/metric-chip — visual.plugin.metric-chip */
export const MetricChip = forwardRef<HTMLElement, MetricChipProps>(function MetricChip(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-plugin-metric-chip', className].filter(Boolean).join(' ');

  return (
    <span ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-plugin-metric-chip">
      <span className="rd-metric-chip__label">{props.chipLabel ?? 'Metric'}</span>
      <span className="rd-metric-chip__value">{props.chipValue ?? '—'}</span>
    </span>
  );
});

// packages/angular/src/visual/plugin/metric-chip/metric-chip.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface MetricChipProps {
  chipLabel?: string;
  chipValue?: string;
  className?: string;
}

/** @rosettadash/angular/visual/plugin/metric-chip — visual.plugin.metric-chip */
@Component({
  selector: 'rd-plugin-metric-chip',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span [attr.data-testid]="'rd-plugin-metric-chip'" [ngClass]="rootClass()">
      <span class="rd-plugin-metric-chip__label">{{ chipLabel() ?? 'Metric' }}</span>
      <span class="rd-plugin-metric-chip__value">{{ chipValue() ?? '—' }}</span>
    </span>
  `,
})
export class MetricChip {
  readonly className = input<string | undefined>(undefined);
  readonly chipLabel = input<string | undefined>(undefined);
  readonly chipValue = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-plugin-metric-chip', this.className()].filter(Boolean).join(' '),
  );
}
