// packages/react/src/visual/display/geo-map/GeoMap.tsx
import { createElement, forwardRef, type CSSProperties } from 'react';
import {
  DB_GEO_MAP_TAG,
  registerRdGeoMap,
  type GeoMapMarker,
  type GeoMapProvider,
} from '@rosettadash/web-components/visual/display/geo-map';
import { useCustomElementHost } from '../../../lib/custom-element-host.js';

export type { GeoMapMarker, GeoMapProvider };

export interface GeoMapProps {
  provider?: GeoMapProvider;
  tileUrl?: string;
  apiKey?: string;
  center?: string;
  zoom?: number;
  markers?: GeoMapMarker[];
  selectedId?: string;
  className?: string;
  style?: CSSProperties;
  onMarkerSelect?: (detail: { id: string; lat: number; lng: number }) => void;
}

/** React wrapper around `<rd-geo-map>`. */
export const GeoMap = forwardRef<HTMLElement, GeoMapProps>(function GeoMap(
  {
    provider,
    tileUrl,
    apiKey,
    center,
    zoom,
    markers,
    selectedId,
    className,
    style,
    onMarkerSelect,
  },
  ref,
) {
  const hostRef = useCustomElementHost(
    {
      register: registerRdGeoMap,
      attrs: {
        tileUrl: 'tile-url',
        apiKey: 'api-key',
        selectedId: 'selected-id',
      },
      properties: ['markers'],
      events: {
        'marker-select': 'onMarkerSelect',
      },
    },
    { provider, tileUrl, apiKey, center, zoom, selectedId },
    {
      onMarkerSelect: onMarkerSelect as ((detail: unknown) => void) | undefined,
    },
    ref,
    { markers },
  );

  return createElement(DB_GEO_MAP_TAG, {
    ref: hostRef,
    className,
    style,
  });
});

// packages/svelte/src/visual/display/geo-map/GeoMap.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import {
		DB_GEO_MAP_TAG,
		registerRdGeoMap,
	} from '@rosettadash/web-components/visual/display/geo-map';
	import {
		attachHostEvents,
		setHostAttribute,
		setHostProperty,
	} from '../../../lib/custom-element-host';
	import type { GeoMapProps } from './types';

	let {
		provider,
		tileUrl,
		apiKey,
		center,
		zoom,
		markers,
		selectedId,
		className,
		onMarkerSelect,
	}: GeoMapProps = $props();

	let host: HTMLElement;
	let detachEvents = () => {};

	onMount(() => {
		registerRdGeoMap();
		detachEvents = attachHostEvents(host, {
			'marker-select': (detail) =>
				onMarkerSelect?.(detail as { id: string; lat: number; lng: number }),
		});
		return () => detachEvents();
	});

	$effect(() => {
		if (!host) {
			return;
		}
		setHostAttribute(host, 'provider', provider);
		setHostAttribute(host, 'tile-url', tileUrl);
		setHostAttribute(host, 'api-key', apiKey);
		setHostAttribute(host, 'center', center);
		setHostAttribute(host, 'zoom', zoom);
		setHostProperty(host, 'markers', markers);
		setHostAttribute(host, 'selected-id', selectedId);
	});
</script>

<svelte:element this={DB_GEO_MAP_TAG} bind:this={host} class={className} />
