// packages/react/src/visual/news/results-table/NewsResultsTable.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface NewsResultsTableProps {
  title?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/news/results-table — visual.news.results-table */
export const NewsResultsTable = forwardRef<HTMLElement, NewsResultsTableProps>(function NewsResultsTable(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-news-results-table', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-news-results-table">
      <header className="rd-table__header"><span>{props.title ?? 'News results'}</span></header>
      <table className="rd-table"><thead><tr><th>Headline</th><th>Source</th><th>Region</th><th>Published</th></tr></thead><tbody /></table>
      {children}
    </section>
  );
});

// packages/angular/src/visual/news/results-table/news-results-table.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface NewsResultsTableProps {
  title?: string;
  className?: string;
}

/** @rosettadash/angular/visual/news/results-table — visual.news.results-table */
@Component({
  selector: 'rd-news-results-table',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-news-results-table'" [ngClass]="rootClass()">
      <header class="rd-table__header"><span>{{ title() ?? 'News results' }}</span></header>
      <table class="rd-table"><thead><tr><th>Headline</th><th>Source</th><th>Region</th><th>Published</th></tr></thead><tbody></tbody></table>
      <ng-content />
    </section>
  `,
})
export class NewsResultsTable {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-news-results-table', this.className()].filter(Boolean).join(' '),
  );
}
