// apps/proof-svelte/src/screens/GlobeScreen.svelte
<script module lang="ts">
  export const GLOBE_SOURCE = `<GlobeScreen part="explorer" locale={locale} selectedId={selectedId}>
  <GeoExplorerLayout items={…} selectedId={selectedId} />
  <ReactMount component={GlobeThree} textureUrl markers selectedId />
</GlobeScreen>`;
</script>

<script lang="ts">
  import {
    DEFAULT_WORLD_EQUIRECT_ATTRIBUTION,
    DEFAULT_WORLD_EQUIRECT_URL,
    GLOBE_TEXTURE_SOURCE_OPTIONS,
    MOCK_DESTINATIONS,
  } from '@destination-atlas';
  import GeoExplorerLayout, { type GeoExplorerListPlacement } from '../components/GeoExplorerLayout.svelte';
  import ReactMount from '../components/ReactMount.svelte';
  import { GlobeThree } from '../globe/GlobeThree';
  import { formatRegionLabel, localizedDestinationName } from '../lib/atlas-utils';

  let {
    locale,
    selectedId,
    embedded = false,
    part,
    listPlacement = 'right',
    onSelectedIdChange,
    onFocusDestinationOnMap,
  }: {
    locale: string;
    selectedId: string;
    embedded?: boolean;
    part?: 'explorer' | 'footer';
    listPlacement?: GeoExplorerListPlacement;
    onSelectedIdChange?: (id: string) => void;
    onFocusDestinationOnMap?: (id: string) => void;
  } = $props();

  const markers = $derived(
    MOCK_DESTINATIONS.map((dest) => ({
      id: dest.id,
      lat: dest.lat,
      lng: dest.lng,
      label: localizedDestinationName(dest, locale),
    })),
  );

  const listItems = $derived(
    MOCK_DESTINATIONS.map((dest) => ({
      id: dest.id,
      label: localizedDestinationName(dest, locale),
      meta: formatRegionLabel(dest.region),
    })),
  );

  function selectFromList(id: string) {
    onSelectedIdChange?.(id);
  }

  function selectFromGlobe(id: string) {
    if (id === selectedId) {
      onFocusDestinationOnMap?.(id);
      return;
    }
    onSelectedIdChange?.(id);
  }

  const globeMountProps = $derived({
    textureUrl: DEFAULT_WORLD_EQUIRECT_URL,
    markers,
    selectedId,
    onMarkerSelect: selectFromGlobe,
  });
</script>

{#if !embedded || part === 'explorer'}
  <GeoExplorerLayout {listPlacement} items={listItems} {selectedId} onSelect={selectFromList}>
    <div class="da-globe-stage">
      {#key selectedId}
        <ReactMount component={GlobeThree} componentProps={globeMountProps} />
      {/key}
    </div>
  </GeoExplorerLayout>
{/if}

{#if embedded && part === 'footer'}
  <div class="da-maps-footer">
    <p class="da-note">{DEFAULT_WORLD_EQUIRECT_ATTRIBUTION}</p>
    <details class="da-globe-sources">
      <summary>Future globe texture sources</summary>
      <ul>
        {#each GLOBE_TEXTURE_SOURCE_OPTIONS as source (source.id)}
          <li>
            <strong>{source.label}</strong> — {source.license}. {source.notes}
            {#if source.apiKeyRequired}<span> API key required.</span>{/if}
          </li>
        {/each}
      </ul>
    </details>
  </div>
{/if}

// apps/proof-react/src/screens/GlobeScreen.tsx
import { GeoExplorerLayout, type GeoExplorerListPlacement } from '@rosettadash/react/layout/geo-explorer';
import { ThreeGeoGlobe } from '@rosettadash/react/visual/display/3d-geo-globe';
import {
  DEFAULT_WORLD_EQUIRECT_ATTRIBUTION,
  DEFAULT_WORLD_EQUIRECT_URL,
  GLOBE_TEXTURE_SOURCE_OPTIONS,
  MOCK_DESTINATIONS,
} from '@destination-atlas';
import type { AtlasContext } from '../state/useDestinationAtlasState';
import { formatRegionLabel, localizedDestinationName } from '../lib/atlas-utils';

export const GLOBE_SOURCE = `<GlobeScreen part="explorer" locale={locale} selectedId={selectedId}>
  <GeoExplorerLayout listPlacement={listPlacement} items={destinationItems} selectedId={selectedId}>
    <ThreeGeoGlobe textureUrl={DEFAULT_WORLD_EQUIRECT_URL} markers={destinationMarkers} selectedId={selectedId} />
  </GeoExplorerLayout>
</GlobeScreen>`;

type GlobeScreenPart = 'explorer' | 'footer';

type Props = Pick<AtlasContext, 'locale' | 'selectedId' | 'setSelectedId' | 'focusDestinationOnMap'> & {
  embedded?: boolean;
  part?: GlobeScreenPart;
  listPlacement?: GeoExplorerListPlacement;
};

export function GlobeScreen({
  locale,
  selectedId,
  setSelectedId,
  focusDestinationOnMap,
  embedded = false,
  part,
  listPlacement = 'right',
}: Props) {
  const markers = MOCK_DESTINATIONS.map((dest) => ({
    id: dest.id,
    lat: dest.lat,
    lng: dest.lng,
    label: localizedDestinationName(dest, locale),
  }));

  const listItems = MOCK_DESTINATIONS.map((dest) => ({
    id: dest.id,
    label: localizedDestinationName(dest, locale),
    meta: formatRegionLabel(dest.region),
  }));

  const selectFromList = (id: string) => {
    setSelectedId(id);
  };

  const selectFromGlobe = (id: string) => {
    if (id === selectedId) {
      focusDestinationOnMap(id);
      return;
    }
    setSelectedId(id);
  };

  const renderExplorer = () => (
    <GeoExplorerLayout
      listPlacement={listPlacement}
      items={listItems}
      selectedId={selectedId}
      onSelect={selectFromList}
    >
      <div className="da-globe-stage">
        <ThreeGeoGlobe
          title="Destination globe (Three.js)"
          textureUrl={DEFAULT_WORLD_EQUIRECT_URL}
          markers={markers}
          selectedId={selectedId}
          onMarkerSelect={selectFromGlobe}
        />
      </div>
    </GeoExplorerLayout>
  );

  const renderFooter = () => (
    <>
      <p className="da-note">{DEFAULT_WORLD_EQUIRECT_ATTRIBUTION}</p>
      <details className="da-globe-sources">
        <summary>Future globe texture sources</summary>
        <ul>
          {GLOBE_TEXTURE_SOURCE_OPTIONS.map((source) => (
            <li key={source.id}>
              <strong>{source.label}</strong> — {source.license}. {source.notes}
              {source.apiKeyRequired ? ' API key required.' : ''}
            </li>
          ))}
        </ul>
      </details>
    </>
  );

  if (embedded && part === 'explorer') {
    return renderExplorer();
  }

  if (embedded && part === 'footer') {
    return <div className="da-maps-footer">{renderFooter()}</div>;
  }

  if (embedded) {
    return (
      <>
        {renderExplorer()}
        {renderFooter()}
      </>
    );
  }

  return (
    <section className="da-panel">
      <h2>Globe</h2>
      <p>
        Three.js globe with dataset destination markers — pick a destination in the list to fly the globe to it;
        click the same marker again to open the Map panel.
      </p>
      {renderExplorer()}
      {renderFooter()}
    </section>
  );
}
