// apps/proof-angular/src/screens/globe-screen.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input } from '@angular/core';
import { ThreeGeoGlobe } from '@rosettadash/angular/visual/display/3d-geo-globe';
import {
  DEFAULT_WORLD_EQUIRECT_ATTRIBUTION,
  DEFAULT_WORLD_EQUIRECT_URL,
  GLOBE_TEXTURE_SOURCE_OPTIONS,
  MOCK_DESTINATIONS,
} from '@destination-atlas';
import { formatRegionLabel, localizedDestinationName } from '../lib/atlas-utils';
import { AtlasStateService } from '../services/atlas-state.service';
import {
  GeoExplorerLayoutComponent,
  type GeoExplorerListPlacement,
} from '../components/geo-explorer-layout.component';

export type GlobeScreenPart = 'explorer' | 'footer';

@Component({
  selector: 'da-globe-screen',
  standalone: true,
  imports: [ThreeGeoGlobe, GeoExplorerLayoutComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (showExplorer()) {
      <da-geo-explorer-layout
        [listPlacement]="listPlacement()"
        [items]="listItems()"
        [selectedId]="atlas.selectedId()"
        (select)="selectFromList($event)"
      >
        <div class="da-globe-stage">
          <rd-display-3d-geo-globe
            title="Destination globe (Three.js)"
            [textureUrl]="textureUrl"
            [markers]="markers()"
            [selectedId]="atlas.selectedId()"
            (markerSelect)="selectFromGlobe($event)"
          />
        </div>
      </da-geo-explorer-layout>
    }

    @if (showFooter()) {
      <div class="da-maps-footer">
        <p class="da-note">{{ attribution }}</p>
        <details class="da-globe-sources">
          <summary>Future globe texture sources</summary>
          <ul>
            @for (source of textureSources; track source.id) {
              <li>
                <strong>{{ source.label }}</strong> — {{ source.license }}. {{ source.notes }}
                @if (source.apiKeyRequired) {
                  API key required.
                }
              </li>
            }
          </ul>
        </details>
      </div>
    }
  `,
})
export class GlobeScreenComponent {
  readonly screenPart = input<GlobeScreenPart>();
  readonly embedded = input(false);
  readonly listPlacement = input<GeoExplorerListPlacement>('right');

  readonly atlas = inject(AtlasStateService);

  readonly textureUrl = DEFAULT_WORLD_EQUIRECT_URL;
  readonly attribution = DEFAULT_WORLD_EQUIRECT_ATTRIBUTION;
  readonly textureSources = GLOBE_TEXTURE_SOURCE_OPTIONS;

  readonly markers = computed(() =>
    MOCK_DESTINATIONS.map((dest) => ({
      id: dest.id,
      lat: dest.lat,
      lng: dest.lng,
      label: localizedDestinationName(dest, this.atlas.locale()),
    })),
  );

  readonly listItems = computed(() =>
    MOCK_DESTINATIONS.map((dest) => ({
      id: dest.id,
      label: localizedDestinationName(dest, this.atlas.locale()),
      meta: formatRegionLabel(dest.region),
    })),
  );

  showExplorer(): boolean {
    const part = this.screenPart();
    if (this.embedded()) {
      return part === 'explorer' || part === undefined;
    }
    return true;
  }

  showFooter(): boolean {
    const part = this.screenPart();
    if (this.embedded()) {
      return part === 'footer';
    }
    return true;
  }

  selectFromList(id: string): void {
    this.atlas.setSelectedId(id);
  }

  selectFromGlobe(id: string): void {
    if (id === this.atlas.selectedId()) {
      this.atlas.focusDestinationOnMap(id);
      return;
    }
    this.atlas.setSelectedId(id);
  }
}

// apps/proof-react/src/screens/GlobeScreen.tsx
import { GeoExplorerLayout, type GeoExplorerListPlacement } from '@rosettadash/react/layout/geo-explorer';
import { ThreeGeoGlobe } from '@rosettadash/react/visual/display/3d-geo-globe';
import {
  DEFAULT_WORLD_EQUIRECT_ATTRIBUTION,
  DEFAULT_WORLD_EQUIRECT_URL,
  GLOBE_TEXTURE_SOURCE_OPTIONS,
  MOCK_DESTINATIONS,
} from '@destination-atlas';
import type { AtlasContext } from '../state/useDestinationAtlasState';
import { formatRegionLabel, localizedDestinationName } from '../lib/atlas-utils';

export const GLOBE_SOURCE = `<GlobeScreen part="explorer" locale={locale} selectedId={selectedId}>
  <GeoExplorerLayout listPlacement={listPlacement} items={destinationItems} selectedId={selectedId}>
    <ThreeGeoGlobe textureUrl={DEFAULT_WORLD_EQUIRECT_URL} markers={destinationMarkers} selectedId={selectedId} />
  </GeoExplorerLayout>
</GlobeScreen>`;

type GlobeScreenPart = 'explorer' | 'footer';

type Props = Pick<AtlasContext, 'locale' | 'selectedId' | 'setSelectedId' | 'focusDestinationOnMap'> & {
  embedded?: boolean;
  part?: GlobeScreenPart;
  listPlacement?: GeoExplorerListPlacement;
};

export function GlobeScreen({
  locale,
  selectedId,
  setSelectedId,
  focusDestinationOnMap,
  embedded = false,
  part,
  listPlacement = 'right',
}: Props) {
  const markers = MOCK_DESTINATIONS.map((dest) => ({
    id: dest.id,
    lat: dest.lat,
    lng: dest.lng,
    label: localizedDestinationName(dest, locale),
  }));

  const listItems = MOCK_DESTINATIONS.map((dest) => ({
    id: dest.id,
    label: localizedDestinationName(dest, locale),
    meta: formatRegionLabel(dest.region),
  }));

  const selectFromList = (id: string) => {
    setSelectedId(id);
  };

  const selectFromGlobe = (id: string) => {
    if (id === selectedId) {
      focusDestinationOnMap(id);
      return;
    }
    setSelectedId(id);
  };

  const renderExplorer = () => (
    <GeoExplorerLayout
      listPlacement={listPlacement}
      items={listItems}
      selectedId={selectedId}
      onSelect={selectFromList}
    >
      <div className="da-globe-stage">
        <ThreeGeoGlobe
          title="Destination globe (Three.js)"
          textureUrl={DEFAULT_WORLD_EQUIRECT_URL}
          markers={markers}
          selectedId={selectedId}
          onMarkerSelect={selectFromGlobe}
        />
      </div>
    </GeoExplorerLayout>
  );

  const renderFooter = () => (
    <>
      <p className="da-note">{DEFAULT_WORLD_EQUIRECT_ATTRIBUTION}</p>
      <details className="da-globe-sources">
        <summary>Future globe texture sources</summary>
        <ul>
          {GLOBE_TEXTURE_SOURCE_OPTIONS.map((source) => (
            <li key={source.id}>
              <strong>{source.label}</strong> — {source.license}. {source.notes}
              {source.apiKeyRequired ? ' API key required.' : ''}
            </li>
          ))}
        </ul>
      </details>
    </>
  );

  if (embedded && part === 'explorer') {
    return renderExplorer();
  }

  if (embedded && part === 'footer') {
    return <div className="da-maps-footer">{renderFooter()}</div>;
  }

  if (embedded) {
    return (
      <>
        {renderExplorer()}
        {renderFooter()}
      </>
    );
  }

  return (
    <section className="da-panel">
      <h2>Globe</h2>
      <p>
        Three.js globe with dataset destination markers — pick a destination in the list to fly the globe to it;
        click the same marker again to open the Map panel.
      </p>
      {renderExplorer()}
      {renderFooter()}
    </section>
  );
}
