// apps/proof-angular/src/screens/media-screen.component.ts
import { ChangeDetectionStrategy, Component, computed, effect, inject } from '@angular/core';
import { YoutubeEmbed } from '@rosettadash/angular/visual/media/youtube-embed';
import {
  EQUIRECT_VIDEO_DESTINATIONS,
  FLAT_VIDEO_DESTINATIONS,
  destinationHasFlatVideo,
  getDestinationById,
  isEquirectDestination,
} from '@destination-atlas';
import { localizedDestinationName } from '../lib/atlas-utils';
import { AtlasStateService } from '../services/atlas-state.service';
import { DaBoundSelectInputComponent } from '../components/proof-form-fields.component';
import { VideoMetadataPanelComponent } from '../components/video-metadata-panel.component';

@Component({
  selector: 'da-media-screen',
  standalone: true,
  imports: [YoutubeEmbed, DaBoundSelectInputComponent, VideoMetadataPanelComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="da-panel">
      <h2>Media</h2>
      <p>
        Watch flat destination videos here. 360° equirectangular locations open in
        <strong>Authoring</strong> with the shipped source loaded in the sphere viewport.
      </p>
      <div class="rd-media-layout">
        <div class="rd-media-primary">
          <da-bound-select-input
            [fieldLabel]="'Flat video (YouTube)'"
            [options]="flatOptions()"
            [value]="flatSelected()?.id ?? ''"
            (valueChange)="onFlatChange($event)"
          />
          @if (flatSelected()?.youtubeId; as videoId) {
            <rd-youtube-embed
              class="rd-youtube-embed-host"
              [videoId]="videoId"
              [title]="youtubeTitle()"
              [controls]="true"
            />
          } @else {
            <p class="da-note">Select a flat destination video to play the YouTube embed.</p>
          }

          <da-bound-select-input
            [fieldLabel]="'360° video (Authoring)'"
            [options]="equirectOptions()"
            [value]="equirectSelected()?.id ?? ''"
            (valueChange)="onEquirectChange($event)"
          />
          <p class="da-note">
            Choosing a 360° destination switches to the Authoring tab and loads its equirect source
            for sphere preview and ffmpeg.wasm extract.
          </p>
        </div>
        <div class="rd-media-tools">
          <da-video-metadata-panel [items]="metadataItems()" />
        </div>
      </div>
    </section>
  `,
})
export class MediaScreenComponent {
  readonly atlas = inject(AtlasStateService);

  readonly flatOptions = computed(() =>
    FLAT_VIDEO_DESTINATIONS.map((dest) => ({
      value: dest.id,
      label: localizedDestinationName(dest, this.atlas.locale()),
    })),
  );

  readonly equirectOptions = computed(() =>
    EQUIRECT_VIDEO_DESTINATIONS.map((dest) => ({
      value: dest.id,
      label: `${localizedDestinationName(dest, this.atlas.locale())} · 360°`,
    })),
  );

  readonly selected = computed(() => getDestinationById(this.atlas.selectedId()));

  readonly flatSelected = computed(() => {
    const selected = this.selected();
    return selected && destinationHasFlatVideo(selected) ? selected : undefined;
  });

  readonly equirectSelected = computed(() => {
    const selected = this.selected();
    return selected && isEquirectDestination(selected) ? selected : undefined;
  });

  readonly metadataItems = computed(() => {
    const flat = this.flatSelected();
    if (!flat) {
      return [];
    }
    return [
      { label: 'Destination', value: localizedDestinationName(flat, this.atlas.locale()) },
      { label: 'Source', value: 'YouTube embed' },
      { label: 'Projection', value: 'Flat / standard' },
      { label: 'Video id', value: flat.youtubeId ?? '—' },
      { label: 'Region', value: flat.region },
    ];
  });

  readonly youtubeTitle = computed(() => {
    const flat = this.flatSelected();
    return flat ? `${localizedDestinationName(flat, this.atlas.locale())} — destination video` : '';
  });

  constructor() {
    effect(() => {
      const equirect = this.equirectSelected();
      if (equirect) {
        this.atlas.openAuthoringForDestination(equirect.id);
      }
    });
  }

  onFlatChange(destinationId: string): void {
    this.atlas.setSelectedId(destinationId);
  }

  onEquirectChange(destinationId: string): void {
    this.atlas.openAuthoringForDestination(destinationId);
  }
}

// apps/proof-react/src/screens/MediaScreen.tsx
import { useEffect } from 'react';
import { YoutubeEmbed } from '@rosettadash/react/visual/media/youtube-embed';
import { VideoMetadataPanel } from '@rosettadash/react/visual/media/video-metadata';
import { SelectInput } from '@rosettadash/react/visual/input/select';
import {
  EQUIRECT_VIDEO_DESTINATIONS,
  FLAT_VIDEO_DESTINATIONS,
  destinationHasFlatVideo,
  getDestinationById,
  isEquirectDestination,
} from '@destination-atlas';
import type { AtlasContext } from '../state/useDestinationAtlasState';
import { localizedDestinationName } from '../lib/atlas-utils';

export const MEDIA_SOURCE = `<MediaScreen selectedId={selectedId}>
  <SelectInput label="Flat video (YouTube)" … />
  <SelectInput label="360° video (Authoring)" … />
  <YoutubeEmbed videoId={selected.youtubeId} controls />
  <VideoMetadataPanel items={videoMetadata} />
</MediaScreen>`;

type Props = Pick<AtlasContext, 'locale' | 'selectedId' | 'setSelectedId'> & {
  openAuthoringForDestination: (destinationId: string) => void;
};

export function MediaScreen({
  locale,
  selectedId,
  setSelectedId,
  openAuthoringForDestination,
}: Props) {
  const selected = getDestinationById(selectedId);
  const flatSelected = destinationHasFlatVideo(selected) ? selected : undefined;
  const equirectSelected = isEquirectDestination(selected) ? selected : undefined;

  useEffect(() => {
    if (equirectSelected) {
      openAuthoringForDestination(equirectSelected.id);
    }
  }, [equirectSelected, openAuthoringForDestination]);

  const metadataItems = flatSelected
    ? [
        { label: 'Destination', value: localizedDestinationName(flatSelected, locale) },
        { label: 'Source', value: 'YouTube embed' },
        { label: 'Projection', value: 'Flat / standard' },
        { label: 'Video id', value: flatSelected.youtubeId ?? '—' },
        { label: 'Region', value: flatSelected.region },
      ]
    : [];

  const handleFlatChange = (destinationId: string) => {
    setSelectedId(destinationId);
  };

  const handleEquirectChange = (destinationId: string) => {
    openAuthoringForDestination(destinationId);
  };

  return (
    <section className="da-panel">
      <h2>Media</h2>
      <p>
        Watch flat destination videos here. 360° equirectangular locations open in{' '}
        <strong>Authoring</strong> with the shipped source loaded in the sphere viewport.
      </p>
      <div className="rd-media-layout">
        <div className="rd-media-primary">
          <SelectInput
            label="Flat video (YouTube)"
            options={FLAT_VIDEO_DESTINATIONS.map((dest) => ({
              value: dest.id,
              label: localizedDestinationName(dest, locale),
            }))}
            value={flatSelected?.id ?? ''}
            onChange={handleFlatChange}
          />
          {flatSelected?.youtubeId ? (
            <YoutubeEmbed
              className="rd-youtube-embed-host"
              videoId={flatSelected.youtubeId}
              title={`${localizedDestinationName(flatSelected, locale)} — destination video`}
              controls
            />
          ) : (
            <p className="da-note">Select a flat destination video to play the YouTube embed.</p>
          )}

          <SelectInput
            label="360° video (Authoring)"
            options={EQUIRECT_VIDEO_DESTINATIONS.map((dest) => ({
              value: dest.id,
              label: `${localizedDestinationName(dest, locale)} · 360°`,
            }))}
            value={equirectSelected?.id ?? ''}
            onChange={handleEquirectChange}
          />
          <p className="da-note">
            Choosing a 360° destination switches to the Authoring tab and loads its equirect source
            for sphere preview and ffmpeg.wasm extract.
          </p>
        </div>
        <div className="rd-media-tools">
          <VideoMetadataPanel items={metadataItems} />
        </div>
      </div>
    </section>
  );
}
