// apps/proof-angular/src/screens/settings-screen.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  effect,
  ElementRef,
  inject,
  signal,
  viewChild,
} from '@angular/core';
import { roleLabel } from '../lib/roles';
import { isSettingFieldTarget, type SettingsHighlightTarget } from '../lib/settings-highlight';
import { AtlasStateService } from '../services/atlas-state.service';
import { ThemeService } from '../services/theme.service';
import { ConsumerSecretsService } from '../services/consumer-secrets.service';
import { AtlasContextControlsComponent } from '../components/atlas-context-controls.component';
import { ThemeToggleComponent } from '../components/theme-toggle.component';
import { CollapsibleComponent } from '../components/collapsible.component';
import { ScoutSettingsSectionComponent } from '../components/scout-settings-section.component';
import { ByokFieldsSectionComponent } from '../components/byok-fields-section.component';
import { DaBoundTextareaInputComponent } from '../components/proof-form-fields.component';

const FEEDBACK_MESSAGE = 'Hope you like the app, please leave comments on github.';

@Component({
  selector: 'da-settings-screen',
  standalone: true,
  imports: [
    AtlasContextControlsComponent,
    ThemeToggleComponent,
    CollapsibleComponent,
    ScoutSettingsSectionComponent,
    ByokFieldsSectionComponent,
    DaBoundTextareaInputComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section class="da-panel da-settings-panel">
      <div class="da-settings-head">
        <h2>Settings</h2>
        <da-theme-toggle
          #themeToggle
          [theme]="theme.theme()"
          [class.rd-highlight-target]="atlas.highlightTarget() === 'theme'"
          (themeChange)="theme.setTheme($event)"
        />
      </div>

      <div #preferencesRef class="da-settings-preferences">
        <da-atlas-context-controls
          [locale]="atlas.locale()"
          [userRole]="atlas.userRole()"
          [mapProvider]="atlas.mapProvider()"
          [selectedId]="atlas.selectedId()"
          [highlightField]="settingFieldHighlight()"
          (localeChange)="atlas.setLocale($event)"
          (userRoleChange)="atlas.setUserRole($event)"
          (mapProviderChange)="atlas.setMapProvider($event)"
          (selectedIdChange)="atlas.setSelectedId($event)"
        />
      </div>

      <div
        #integrationsRef
        [class.rd-highlight-target]="atlas.highlightTarget() === 'integrations'"
      >
        <da-collapsible
          [panelTitle]="'Integration keys (BYOK)'"
          [panelSummary]="'Google Maps, MapTiler, News API'"
          class="da-byok-collapsible"
          [open]="integrationsOpen()"
          (openChange)="integrationsOpen.set($event)"
        >
          <da-byok-fields-section
            [userRole]="atlas.userRole()"
            [fields]="secrets.integrationFields"
            gateLabel="Integration keys (BYOK)"
            gateStatusText="Admin can manage API keys for Map, Intel, and Stack"
            [gateHiddenStatusText]="
              'Integration keys are read-only for ' +
              roleLabel(atlas.userRole()) +
              '. Switch to Admin to configure BYOK.'
            "
          />
        </da-collapsible>
      </div>

      <div #aiRef [class.rd-highlight-target]="atlas.highlightTarget() === 'ai'">
        <da-collapsible
          [panelTitle]="'Scout / AI providers (BYOK)'"
          [panelSummary]="'Deal scout — OpenAI, Anthropic, Gemini, Azure, Ollama'"
          class="da-byok-collapsible"
          [open]="aiOpen()"
          (openChange)="aiOpen.set($event)"
        >
          <da-scout-settings-section [locale]="atlas.locale()" [selectedId]="atlas.selectedId()" />
          <da-byok-fields-section
            [userRole]="atlas.userRole()"
            [fields]="secrets.aiFields"
            gateLabel="AI providers (BYOK)"
            gateStatusText="Admin can manage AI keys for Scout and future premium features"
            [gateHiddenStatusText]="
              'AI keys are read-only for ' +
              roleLabel(atlas.userRole()) +
              '. Switch to Admin to configure BYOK.'
            "
          />
        </da-collapsible>
      </div>

      <div
        #feedbackRef
        class="da-settings-feedback"
        [class.rd-highlight-target]="atlas.highlightTarget() === 'feedback'"
      >
        <da-bound-textarea-input
          [fieldLabel]="'Feedback'"
          placeholder="This is a demonstration, and feedback is not functional here."
          [rows]="4"
          [value]="feedbackDraft()"
          (valueChange)="feedbackDraft.set($event)"
        />
        <div class="da-settings-feedback__actions">
          <button type="button" class="rd-button" (click)="submitFeedback()">Submit feedback</button>
        </div>
        @if (feedbackSent()) {
          <p class="da-settings-feedback__msg">{{ feedbackMessage }}</p>
        }
      </div>
    </section>
  `,
})
export class SettingsScreenComponent {
  readonly roleLabel = roleLabel;

  readonly atlas = inject(AtlasStateService);
  readonly theme = inject(ThemeService);
  readonly secrets = inject(ConsumerSecretsService);

  readonly feedbackMessage = FEEDBACK_MESSAGE;
  readonly feedbackDraft = signal('');
  readonly feedbackSent = signal(false);
  readonly integrationsOpen = signal(false);
  readonly aiOpen = signal(false);

  private readonly preferencesRef = viewChild<ElementRef<HTMLElement>>('preferencesRef');
  private readonly integrationsRef = viewChild<ElementRef<HTMLElement>>('integrationsRef');
  private readonly aiRef = viewChild<ElementRef<HTMLElement>>('aiRef');
  private readonly feedbackRef = viewChild<ElementRef<HTMLElement>>('feedbackRef');
  private readonly themeToggleRef = viewChild<ElementRef<HTMLElement>>('themeToggle');

  constructor() {
    effect(() => {
      const target = this.atlas.highlightTarget();
      if (!target) {
        return;
      }

      if (target === 'integrations') {
        this.integrationsOpen.set(true);
      }
      if (target === 'ai') {
        this.aiOpen.set(true);
      }

      queueMicrotask(() => {
        const scrollTarget = this.resolveScrollTarget(target);
        scrollTarget?.scrollIntoView({ behavior: 'smooth', block: 'center' });
        window.setTimeout(() => this.atlas.setHighlightTarget(null), 2400);
      });
    });
  }

  settingFieldHighlight() {
    const target = this.atlas.highlightTarget();
    return isSettingFieldTarget(target) ? target : null;
  }

  submitFeedback(): void {
    this.feedbackSent.set(true);
    this.feedbackDraft.set('');
  }

  private resolveScrollTarget(target: SettingsHighlightTarget): HTMLElement | null {
    if (!target) {
      return null;
    }
    if (target === 'theme') {
      return this.themeToggleRef()?.nativeElement ?? null;
    }
    if (target === 'integrations') {
      return this.integrationsRef()?.nativeElement ?? null;
    }
    if (target === 'ai') {
      return this.aiRef()?.nativeElement ?? null;
    }
    if (target === 'feedback') {
      return this.feedbackRef()?.nativeElement ?? null;
    }
    if (isSettingFieldTarget(target)) {
      return (
        this.preferencesRef()?.nativeElement.querySelector(`[data-setting="${target}"]`) ?? null
      );
    }
    return this.preferencesRef()?.nativeElement ?? null;
  }
}

// apps/proof-react/src/screens/SettingsScreen.tsx
import { useEffect, useRef, useState } from 'react';
import { Collapsible } from '@rosettadash/react/layout/collapsible';
import { RoleGate } from '@rosettadash/react/domain/role-gate';
import { TextInput } from '@rosettadash/react/visual/input/text';
import { TextareaInput } from '@rosettadash/react/visual/input/textarea';
import type { AtlasContext } from '../state/useDestinationAtlasState';
import { useConsumerSecrets } from '../state/consumer-secrets-context';
import { AtlasContextControls } from '../components/AtlasContextControls';
import { ScoutSettingsSection } from '../components/ScoutSettingsSection';
import { ThemeToggle, type ThemePreference } from '../lib/theme';
import { roleLabel } from '../lib/roles';
import { isSettingFieldTarget } from '../lib/settings-highlight';

export const SETTINGS_SOURCE = `<SettingsScreen>
  <header><h2>Settings</h2><ThemeToggle /></header>
  <AtlasContextControls highlightField={…} />
  <Collapsible title="Integration keys (BYOK)">…</Collapsible>
  <Collapsible title="Scout / AI providers (BYOK)">…</Collapsible>
  <TextareaInput label="Feedback" />
</SettingsScreen>`;

const FEEDBACK_MESSAGE = 'Hope you like the app, please leave comments on github.';

type Props = Pick<
  AtlasContext,
  | 'locale'
  | 'userRole'
  | 'setLocale'
  | 'setUserRole'
  | 'mapProvider'
  | 'setMapProvider'
  | 'selectedId'
  | 'setSelectedId'
  | 'highlightTarget'
  | 'setHighlightTarget'
> & {
  theme: ThemePreference;
  setTheme: (theme: ThemePreference) => void;
};

export function SettingsScreen({
  locale,
  userRole,
  setLocale,
  setUserRole,
  mapProvider,
  setMapProvider,
  selectedId,
  setSelectedId,
  highlightTarget,
  setHighlightTarget,
  theme,
  setTheme,
}: Props) {
  const preferencesRef = useRef<HTMLDivElement>(null);
  const themeRef = useRef<HTMLLabelElement>(null);
  const integrationsRef = useRef<HTMLDivElement>(null);
  const aiRef = useRef<HTMLDivElement>(null);
  const feedbackRef = useRef<HTMLDivElement>(null);
  const secrets = useConsumerSecrets();
  const [integrationsOpen, setIntegrationsOpen] = useState(highlightTarget === 'integrations');
  const [aiOpen, setAiOpen] = useState(highlightTarget === 'ai');
  const [feedbackDraft, setFeedbackDraft] = useState('');
  const [feedbackSent, setFeedbackSent] = useState(false);

  const settingFieldHighlight = isSettingFieldTarget(highlightTarget) ? highlightTarget : null;

  useEffect(() => {
    if (!highlightTarget) {
      return undefined;
    }

    const scrollTarget =
      highlightTarget === 'theme'
        ? themeRef.current
        : highlightTarget === 'integrations'
          ? integrationsRef.current
          : highlightTarget === 'ai'
            ? aiRef.current
            : highlightTarget === 'feedback'
              ? feedbackRef.current
              : isSettingFieldTarget(highlightTarget)
                ? preferencesRef.current?.querySelector(`[data-setting="${highlightTarget}"]`)
                : preferencesRef.current;

    scrollTarget?.scrollIntoView({ behavior: 'smooth', block: 'center' });

    if (highlightTarget === 'integrations') {
      setIntegrationsOpen(true);
    }
    if (highlightTarget === 'ai') {
      setAiOpen(true);
    }

    const timer = window.setTimeout(() => setHighlightTarget(null), 2400);
    return () => window.clearTimeout(timer);
  }, [highlightTarget, setHighlightTarget]);

  const submitFeedback = () => {
    setFeedbackSent(true);
    setFeedbackDraft('');
  };

  return (
    <section className="da-panel da-settings-panel">
      <div className="da-settings-head">
        <h2>Settings</h2>
        <ThemeToggle
          ref={themeRef}
          theme={theme}
          onChange={setTheme}
          className={highlightTarget === 'theme' ? 'rd-highlight-target' : undefined}
        />
      </div>

      <div ref={preferencesRef} className="da-settings-preferences">
        <AtlasContextControls
          locale={locale}
          setLocale={setLocale}
          userRole={userRole}
          setUserRole={setUserRole}
          mapProvider={mapProvider}
          setMapProvider={setMapProvider}
          selectedId={selectedId}
          setSelectedId={setSelectedId}
          highlightField={settingFieldHighlight}
        />
      </div>

      <div
        ref={integrationsRef}
        className={highlightTarget === 'integrations' ? 'rd-highlight-target' : undefined}
      >
        <Collapsible
          title="Integration keys (BYOK)"
          summary="Google Maps, MapTiler, News API"
          open={integrationsOpen}
          onOpenChange={setIntegrationsOpen}
          className="da-byok-collapsible"
        >
          <RoleGate
            label="Integration keys (BYOK)"
            currentRole={userRole}
            allowedRoles={['admin']}
            statusText="Admin can manage API keys for Map, Intel, and Stack"
            hiddenStatusText={`Integration keys are read-only for ${roleLabel(userRole)}. Switch to Admin to configure BYOK.`}
          >
            {!secrets.loaded ? <p className="da-note">Loading encrypted key vault…</p> : null}
            <div className="da-byok-fields">
              {secrets.integrationFields.map((field) => (
                <div key={field.id} className="da-byok-field">
                  <TextInput
                    label={field.label}
                    placeholder={field.placeholder}
                    inputType="password"
                    value={secrets.getDraftValue(field.envKey)}
                    onChange={(value) => secrets.setDraftValue(field.envKey, value)}
                  />
                  <p className="da-byok-field__desc">{field.description}</p>
                  <p className="da-byok-field__meta">
                    Env key: <code>{field.envKey}</code>
                    {secrets.hasConfiguredKey(field.envKey) ? (
                      <span className="da-byok-field__status da-byok-field__status--ok">configured</span>
                    ) : (
                      <span className="da-byok-field__status">not set</span>
                    )}
                  </p>
                </div>
              ))}
            </div>
            <label className="da-byok-remember">
              <input
                type="checkbox"
                checked={secrets.rememberKeys}
                onChange={(event) => secrets.setRememberKeys(event.target.checked)}
              />
              Remember keys in this browser (localStorage + encryption)
            </label>
            <div className="da-byok-actions">
              <button type="button" className="rd-button" onClick={() => void secrets.save()} disabled={!secrets.loaded}>
                Save keys
              </button>
              <button type="button" className="rd-button rd-button--ghost" onClick={() => void secrets.clearAll()}>
                Clear keys
              </button>
            </div>
            {secrets.saveMessage ? <p className="da-byok-save-msg">{secrets.saveMessage}</p> : null}
          </RoleGate>
        </Collapsible>
      </div>

      <div ref={aiRef} className={highlightTarget === 'ai' ? 'rd-highlight-target' : undefined}>
        <Collapsible
          title="Scout / AI providers (BYOK)"
          summary="Deal scout — OpenAI, Anthropic, Gemini, Azure, Ollama"
          open={aiOpen}
          onOpenChange={setAiOpen}
          className="da-byok-collapsible"
        >
          <ScoutSettingsSection locale={locale} selectedId={selectedId} />
          <RoleGate
            label="AI providers (BYOK)"
            currentRole={userRole}
            allowedRoles={['admin']}
            statusText="Admin can manage AI keys for Scout and future premium features"
            hiddenStatusText={`AI keys are read-only for ${roleLabel(userRole)}. Switch to Admin to configure BYOK.`}
          >
            {!secrets.loaded ? <p className="da-note">Loading encrypted key vault…</p> : null}
            <div className="da-byok-fields">
              {secrets.aiFields.map((field) => (
                <div key={field.id} className="da-byok-field">
                  <TextInput
                    label={field.label}
                    placeholder={field.placeholder}
                    inputType={field.sensitive ? 'password' : 'text'}
                    value={secrets.getDraftValue(field.envKey)}
                    onChange={(value) => secrets.setDraftValue(field.envKey, value)}
                  />
                  <p className="da-byok-field__desc">{field.description}</p>
                  <p className="da-byok-field__meta">
                    Env key: <code>{field.envKey}</code>
                    {field.optional ? <span className="da-byok-field__optional">optional</span> : null}
                    {secrets.hasConfiguredKey(field.envKey) ? (
                      <span className="da-byok-field__status da-byok-field__status--ok">configured</span>
                    ) : field.sensitive ? (
                      <span className="da-byok-field__status">not set</span>
                    ) : null}
                  </p>
                </div>
              ))}
            </div>
            <label className="da-byok-remember">
              <input
                type="checkbox"
                checked={secrets.rememberKeys}
                onChange={(event) => secrets.setRememberKeys(event.target.checked)}
              />
              Remember keys in this browser (localStorage + encryption)
            </label>
            <div className="da-byok-actions">
              <button type="button" className="rd-button" onClick={() => void secrets.save()} disabled={!secrets.loaded}>
                Save keys
              </button>
              <button type="button" className="rd-button rd-button--ghost" onClick={() => void secrets.clearAll()}>
                Clear keys
              </button>
            </div>
            {secrets.saveMessage ? <p className="da-byok-save-msg">{secrets.saveMessage}</p> : null}
          </RoleGate>
        </Collapsible>
      </div>

      <div
        ref={feedbackRef}
        className={[
          'da-settings-feedback',
          highlightTarget === 'feedback' ? 'rd-highlight-target' : undefined,
        ]
          .filter(Boolean)
          .join(' ')}
      >
        <TextareaInput
          label="Feedback"
          placeholder="This is a demonstration, and feedback is not functional here."
          rows={4}
          value={feedbackDraft}
          onChange={setFeedbackDraft}
        />
        <div className="da-settings-feedback__actions">
          <button type="button" className="rd-button" onClick={submitFeedback}>
            Submit feedback
          </button>
        </div>
        {feedbackSent ? <p className="da-settings-feedback__msg">{FEEDBACK_MESSAGE}</p> : null}
      </div>
    </section>
  );
}
