// packages/react/src/infra/wasm/asset/WasmAsset.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface WasmAssetProps {
  assetPath?: string;
  gluePath?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/infra/wasm/asset — infra.wasm.asset */
export const WasmAsset = forwardRef<HTMLElement, WasmAssetProps>(function WasmAsset(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-wasm-asset', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-wasm-asset">
      <span className="rd-wasm__badge">WASM</span>
      <code>{props.assetPath ?? 'wasm/modules/example.wasm'}</code>
      {props.gluePath ? <span className="rd-wasm__glue">+ {props.gluePath}</span> : null}
      {children}
    </section>
  );
});

// packages/angular/src/infra/wasm/asset/wasm-asset.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface WasmAssetProps {
  assetPath?: string;
  gluePath?: string;
  className?: string;
}

/** @rosettadash/angular/infra/wasm/asset — infra.wasm.asset */
@Component({
  selector: 'rd-wasm-asset',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-wasm-asset'" [ngClass]="rootClass()">
      <span class="rd-wasm__badge">WASM</span>
      <code>{{ assetPath() ?? 'wasm/modules/example.wasm' }}</code>
      @if (gluePath()) { <span class="rd-wasm__glue">+ {{ gluePath() }}</span> }
      <ng-content />
    </section>
  `,
})
export class WasmAsset {
  readonly className = input<string | undefined>(undefined);
  readonly assetPath = input<string | undefined>(undefined);
  readonly gluePath = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-wasm-asset', this.className()].filter(Boolean).join(' '),
  );
}
