// packages/react/src/visual/display/3d-gltf-model/ThreeGltfModel.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface ThreeGltfModelProps {
  title?: string;
  mode?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/display/3d-gltf-model — visual.display.3d-gltf-model */
export const ThreeGltfModel = forwardRef<HTMLElement, ThreeGltfModelProps>(function ThreeGltfModel(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-display-3d-gltf-model', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-display-3d-gltf-model" data-three-mode={props.mode} data-three-title={props.title} aria-label={props.title ?? '3D host'}>{children}</section>
  );
});

// packages/angular/src/visual/display/3d-gltf-model/three-gltf-model.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface ThreeGltfModelProps {
  title?: string;
  mode?: string;
  className?: string;
}

/** @rosettadash/angular/visual/display/3d-gltf-model — visual.display.3d-gltf-model */
@Component({
  selector: 'rd-display-3d-gltf-model',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-display-3d-gltf-model'" [ngClass]="rootClass()" [attr.data-three-mode]="mode()" [attr.data-three-title]="title()" [attr.aria-label]="title() ?? '3D host'"><ng-content /></section>
  `,
})
export class ThreeGltfModel {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly mode = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-display-3d-gltf-model', this.className()].filter(Boolean).join(' '),
  );
}
