// packages/react/src/layout/flex/FlexLayout.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface FlexLayoutProps {
  title?: string;
  direction?: 'row' | 'column';
  gap?: number | string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/layout/flex — layout.flex */
export const FlexLayout = forwardRef<HTMLElement, FlexLayoutProps>(function FlexLayout(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-flex', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-flex">
      {props.title ? <span className="rd-flex__title">{props.title}</span> : null}
      <div className="rd-flex__flex" style={{ flexDirection: props.direction ?? 'row', gap: props.gap ?? 12 }}>{children}</div>
    </section>
  );
});

// packages/angular/src/layout/flex/flex-layout.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface FlexLayoutProps {
  title?: string;
  direction?: 'row' | 'column';
  gap?: number | string;
  className?: string;
}

/** @rosettadash/angular/layout/flex — layout.flex */
@Component({
  selector: 'rd-flex',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-flex'" [ngClass]="rootClass()">
      @if (title()) { <span class="rd-flex__title">{{ title() }}</span> }
      <div class="rd-flex__flex" [style.flex-direction]="direction() ?? 'row'" [style.gap.px]="flexGap()"><ng-content /></div>
    </section>
  `,
})
export class FlexLayout {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);
  readonly direction = input<'row' | 'column' | undefined>(undefined);
  readonly gap = input<number | string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-flex', this.className()].filter(Boolean).join(' '),
  );
  flexGap(): number {
    const gap = this.gap();
    return typeof gap === 'number' ? gap : 12;
  }
}
