// packages/svelte/src/visual/plugin/metric-chip/MetricChip.svelte
<script lang="ts">
	import type { MetricChipProps } from './types';

	type Props = MetricChipProps;

	let {
		className,
		chipLabel,
		chipValue,
	}: Props = $props();
	const rootClass = $derived(['rd-plugin-metric-chip', className].filter(Boolean).join(' '));
</script>

<span class={rootClass} data-testid="rd-plugin-metric-chip">
	<span class="rd-plugin-metric-chip__label">{chipLabel ?? 'Metric'}</span>
	<span class="rd-plugin-metric-chip__value">{chipValue ?? '—'}</span>
</span>

// packages/react/src/visual/plugin/metric-chip/MetricChip.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface MetricChipProps {
  chipLabel?: string;
  chipValue?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/plugin/metric-chip — visual.plugin.metric-chip */
export const MetricChip = forwardRef<HTMLElement, MetricChipProps>(function MetricChip(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-plugin-metric-chip', className].filter(Boolean).join(' ');

  return (
    <span ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-plugin-metric-chip">
      <span className="rd-metric-chip__label">{props.chipLabel ?? 'Metric'}</span>
      <span className="rd-metric-chip__value">{props.chipValue ?? '—'}</span>
    </span>
  );
});
