// packages/svelte/src/infra/server/express/ExpressServerInfra.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { ExpressServerInfraProps } from './types';

	type Props = ExpressServerInfraProps & { children?: Snippet };

	let {
		className,
		label,
		globalPrefix,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-server-express', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-server-express">
	<span class="rd-infra__badge">INFRA</span>
	{#if label}<span class="rd-field__label">{label}</span>{/if}
	{#if globalPrefix}<code>globalPrefix: {globalPrefix}</code>{/if}
	{@render children?.()}
</section>

// packages/react/src/infra/server/express/ExpressServerInfra.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface ExpressServerInfraProps {
  label?: string;
  globalPrefix?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/infra/server/express — infra.server.express */
export const ExpressServerInfra = forwardRef<HTMLElement, ExpressServerInfraProps>(function ExpressServerInfra(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-server-express', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-server-express">
      <span className="rd-infra__badge">INFRA</span>
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      {props.globalPrefix ? <code>globalPrefix: {props.globalPrefix}</code> : null}
      {children}
    </section>
  );
});
