// packages/react/src/domain/time-preset/TimePreset.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface TimePresetPreset {
  id: string;
  label: string;
}

export interface TimePresetProps {
  label?: string;
  presets?: TimePresetPreset[];
  activePresetId?: string;
  onPresetChange?: (presetId: string) => void;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/domain/time-preset — domain.time-preset */
export const TimePreset = forwardRef<HTMLElement, TimePresetProps>(function TimePreset(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-time-preset', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-time-preset">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <div className="rd-time-preset__buttons" role="group">
        {(props.presets ?? []).map((p) => (
          <button
            key={p.id}
            type="button"
            className={['rd-time-preset__button', props.activePresetId === p.id ? 'rd-time-preset__button--active' : ''].filter(Boolean).join(' ')}
            onClick={() => props.onPresetChange?.(p.id)}
          >
            {p.label}
          </button>
        ))}
      </div>
      {children}
    </section>
  );
});

// packages/svelte/src/domain/time-preset/TimePreset.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { TimePresetProps } from './types';

	type Props = TimePresetProps & { children?: Snippet };

	let {
		className,
		label,
		presets,
		activePresetId,
		children,
	}: Props = $props();
	function presetButtonClass(id: string): string {
		return ['rd-time-preset__button', activePresetId === id ? 'rd-time-preset__button--active' : ''].filter(Boolean).join(' ');
	}
	const rootClass = $derived(['rd-time-preset', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-time-preset">
	{#if label}<span class="rd-field__label">{label}</span>{/if}
	<div class="rd-time-preset__buttons" role="group">
		{#each presets ?? [] as p (p.id)}<button type="button" class={presetButtonClass(p.id)}>{p.label}</button>{/each}
	</div>
	{@render children?.()}
</section>
