// packages/react/src/domain/role-gate/RoleGate.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface RoleGateProps {
  label?: string;
  allowedRoles?: string[];
  statusText?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/domain/role-gate — domain.role-gate */
export const RoleGate = forwardRef<HTMLElement, RoleGateProps>(function RoleGate(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-role-gate', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-role-gate">
      {props.label ? <span className="rd-field__label">{props.label}</span> : null}
      <p className="rd-role-gate__status">{props.statusText ?? 'Visible'}</p>
      {props.allowedRoles?.length ? <code>{JSON.stringify(props.allowedRoles)}</code> : null}
      {children}
    </section>
  );
});

// packages/svelte/src/domain/role-gate/RoleGate.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import type { RoleGateProps } from './types';

	type Props = RoleGateProps & { children?: Snippet };

	let {
		className,
		label,
		allowedRoles,
		statusText,
		children,
	}: Props = $props();
	const rootClass = $derived(['rd-role-gate', className].filter(Boolean).join(' '));
</script>

<section class={rootClass} data-testid="rd-role-gate">
	{#if label}<span class="rd-field__label">{label}</span>{/if}
	<p class="rd-role-gate__status">{statusText ?? 'Visible'}</p>
	{@render children?.()}
</section>
