// apps/proof-react/src/App.tsx
import { useState } from 'react';
import { NavLink } from 'react-router-dom';
import { buildAtlasLocation } from '@rosettadash/core';
import { DESTINATION_ATLAS_SCREENS, MOCK_DESTINATIONS } from '@destination-atlas';
import { screenAllowedForRole } from './lib/roles';
import { useClientRouterMode } from './lib/client-router';
import { useDestinationAtlasState } from './state/useDestinationAtlasState';
import { AboutScreen, ABOUT_SOURCE } from './screens/AboutScreen';
import { OverviewScreen, OVERVIEW_SOURCE } from './screens/OverviewScreen';
import { DestinationsScreen, DESTINATIONS_SOURCE } from './screens/DestinationsScreen';
import { MapsScreen, MAPS_SOURCE } from './screens/MapsScreen';
import { MediaScreen, MEDIA_SOURCE } from './screens/MediaScreen';
import { AuthoringScreen, AUTHORING_SOURCE } from './screens/AuthoringScreen';
import { IntelScreen, INTEL_SOURCE } from './screens/IntelScreen';
import { PlanScreen, PLAN_SOURCE } from './screens/PlanScreen';
import { ViewsScreen, VIEWS_SOURCE } from './screens/ViewsScreen';
import { StackScreen, STACK_SOURCE } from './screens/StackScreen';
import { SettingsScreen, SETTINGS_SOURCE } from './screens/SettingsScreen';
import { useThemePreference } from './lib/theme';
import type { SettingFieldTarget } from './lib/settings-highlight';
import { ErrorBoundary } from './components/ErrorBoundary';
import {
  ComponentSourcePanel,
  ScreenWorkbenchMobileToggle,
  ScreenWorkbenchPreview,
} from './components/ScreenWorkbench';
import { RouterModeSelect } from './components/RouterModeSelect';
import { AtlasContextSummary } from './components/AtlasContextSummary';

const SCREEN_SOURCES: Record<string, string> = {
  about: ABOUT_SOURCE,
  overview: OVERVIEW_SOURCE,
  destinations: DESTINATIONS_SOURCE,
  maps: MAPS_SOURCE,
  media: MEDIA_SOURCE,
  authoring: AUTHORING_SOURCE,
  intel: INTEL_SOURCE,
  plan: PLAN_SOURCE,
  views: VIEWS_SOURCE,
  stack: STACK_SOURCE,
  settings: SETTINGS_SOURCE,
};

export function App() {
  const initialDestId = MOCK_DESTINATIONS[0]?.id ?? '';
  const atlas = useDestinationAtlasState(initialDestId);
  const { theme, setTheme } = useThemePreference();
  const { routerMode, setRouterMode } = useClientRouterMode();
  const [mobileView, setMobileView] = useState<'preview' | 'source'>('preview');
  const activeScreen = DESTINATION_ATLAS_SCREENS.find((screen) => screen.id === atlas.screen);
  const visibleScreens = DESTINATION_ATLAS_SCREENS.filter((screen) =>
    screenAllowedForRole(screen.id, atlas.userRole),
  );

  const atlasQuery = {
    dest: atlas.selectedId,
    locale: atlas.locale,
    provider: atlas.mapProvider,
    role: atlas.userRole,
  };

  const urlDefaults = {
    dest: initialDestId,
    locale: 'en',
    provider: 'leaflet' as const,
    role: 'viewer' as const,
  };

  const screenTo = (screenId: (typeof visibleScreens)[number]['id']) => {
    const mapsPanel = screenId === 'maps' ? atlas.mapsPanel : 'map';
    const { pathname, search } = buildAtlasLocation(screenId, atlasQuery, urlDefaults, mapsPanel);
    return { pathname, search };
  };

  const openSetting = (field: SettingFieldTarget | 'theme' | 'ai') => {
    atlas.setHighlightTarget(field);
    atlas.setScreen('settings');
  };

  const settingsIndex = visibleScreens.findIndex((screen) => screen.id === 'settings');
  const navScreensBeforeScout = settingsIndex >= 0 ? visibleScreens.slice(0, settingsIndex) : visibleScreens;
  const navScreensFromSettings = settingsIndex >= 0 ? visibleScreens.slice(settingsIndex) : [];

  return (
    <div className="da-shell">
      <header className="da-header">
        <h1>Destination Atlas</h1>
        <p>Current and historic information about world locations — React proof (DAS-137 Scout + Maps)</p>
      </header>

      <div className="da-body-row">
        <div className="da-preview-column">
          <div className="da-context-strip">
            <RouterModeSelect mode={routerMode} onChange={setRouterMode} />
            <AtlasContextSummary
              locale={atlas.locale}
              userRole={atlas.userRole}
              mapProvider={atlas.mapProvider}
              selectedId={atlas.selectedId}
              theme={theme}
              onOpenSetting={openSetting}
            />
          </div>

          <nav className="da-nav da-tabbar" aria-label="Screens">
            {navScreensBeforeScout.map((screen) => (
              <NavLink
                key={screen.id}
                className="da-tabbar__tab"
                to={screenTo(screen.id)}
                aria-current={atlas.screen === screen.id ? 'page' : undefined}
              >
                {screen.label}
              </NavLink>
            ))}
            <button
              type="button"
              className="da-tabbar__tab"
              aria-current={atlas.settingsScoutFocus ? 'page' : undefined}
              onClick={atlas.openScoutSettings}
            >
              Scout
            </button>
            {navScreensFromSettings.map((screen) => (
              <NavLink
                key={screen.id}
                className="da-tabbar__tab"
                to={screenTo(screen.id)}
                aria-current={
                  atlas.screen === screen.id && !atlas.settingsScoutFocus ? 'page' : undefined
                }
              >
                {screen.label}
              </NavLink>
            ))}
          </nav>

          <div className="da-workbench-host">
            <ErrorBoundary label={activeScreen?.label ?? atlas.screen}>
              <ScreenWorkbenchMobileToggle mobileView={mobileView} onChange={setMobileView} />
              <ScreenWorkbenchPreview mobileView={mobileView}>
              {atlas.screen === 'about' ? <AboutScreen /> : null}
              {atlas.screen === 'overview' ? (
                <OverviewScreen locale={atlas.locale} userRole={atlas.userRole} />
              ) : null}
              {atlas.screen === 'destinations' ? (
                <DestinationsScreen
                  locale={atlas.locale}
                  userRole={atlas.userRole}
                  selectedId={atlas.selectedId}
                  setSelectedId={atlas.setSelectedId}
                  destSearch={atlas.destSearch}
                  setDestSearch={atlas.setDestSearch}
                  destRegion={atlas.destRegion}
                  setDestRegion={atlas.setDestRegion}
                  timePreset={atlas.timePreset}
                  setTimePreset={atlas.setTimePreset}
                  visitPeriodStart={atlas.visitPeriodStart}
                  visitPeriodEnd={atlas.visitPeriodEnd}
                  setVisitPeriod={atlas.setVisitPeriod}
                  focusDestinationOnMap={atlas.focusDestinationOnMap}
                />
              ) : null}
              {atlas.screen === 'maps' ? (
                <MapsScreen
                  locale={atlas.locale}
                  selectedId={atlas.selectedId}
                  setSelectedId={atlas.setSelectedId}
                  mapProvider={atlas.mapProvider}
                  setMapProvider={atlas.setMapProvider}
                  mapLocationQuery={atlas.mapLocationQuery}
                  setMapLocationQuery={atlas.setMapLocationQuery}
                  mapViewOverride={atlas.mapViewOverride}
                  focusDestinationOnMap={atlas.focusDestinationOnMap}
                  goToMapView={atlas.goToMapView}
                  setScreen={atlas.setScreen}
                  setHighlightTarget={atlas.setHighlightTarget}
                  mapsPanel={atlas.mapsPanel}
                  setMapsPanel={atlas.setMapsPanel}
                />
              ) : null}
              {atlas.screen === 'media' ? (
                <MediaScreen
                  locale={atlas.locale}
                  selectedId={atlas.selectedId}
                  setSelectedId={atlas.setSelectedId}
                  openAuthoringForDestination={atlas.openAuthoringForDestination}
                />
              ) : null}
              {atlas.screen === 'authoring' ? (
                <AuthoringScreen locale={atlas.locale} selectedId={atlas.selectedId} />
              ) : null}
              {atlas.screen === 'intel' ? (
                <IntelScreen
                  userRole={atlas.userRole}
                  newsQuery={atlas.newsQuery}
                  setNewsQuery={atlas.setNewsQuery}
                  newsRegion={atlas.newsRegion}
                  setNewsRegion={atlas.setNewsRegion}
                  selectedArticleId={atlas.selectedArticleId}
                  setSelectedArticleId={atlas.setSelectedArticleId}
                  setScreen={atlas.setScreen}
                  setHighlightTarget={atlas.setHighlightTarget}
                />
              ) : null}
              {atlas.screen === 'plan' ? <PlanScreen userRole={atlas.userRole} locale={atlas.locale} /> : null}
              {atlas.screen === 'views' ? (
                <ViewsScreen locale={atlas.locale} selectedId={atlas.selectedId} setSelectedId={atlas.setSelectedId} />
              ) : null}
              {atlas.screen === 'stack' ? <StackScreen userRole={atlas.userRole} /> : null}
              {atlas.screen === 'settings' ? (
                <SettingsScreen
                  locale={atlas.locale}
                  userRole={atlas.userRole}
                  setLocale={atlas.setLocale}
                  setUserRole={atlas.setUserRole}
                  mapProvider={atlas.mapProvider}
                  setMapProvider={atlas.setMapProvider}
                  selectedId={atlas.selectedId}
                  setSelectedId={atlas.setSelectedId}
                  highlightTarget={atlas.highlightTarget}
                  setHighlightTarget={atlas.setHighlightTarget}
                  theme={theme}
                  setTheme={setTheme}
                />
              ) : null}
            </ScreenWorkbenchPreview>
            </ErrorBoundary>
          </div>
        </div>
        <ComponentSourcePanel
          source={SCREEN_SOURCES[atlas.screen] ?? ''}
          hidden={mobileView === 'preview'}
        />
      </div>
    </div>
  );
}

// apps/proof-angular/src/app.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DESTINATION_ATLAS_SCREENS } from '@destination-atlas';
import { screenAllowedForRole } from './lib/roles';
import { SCREEN_SOURCES } from './lib/screen-sources';
import type { SettingFieldTarget } from './lib/settings-highlight';
import { AtlasStateService } from './services/atlas-state.service';
import { ThemeService } from './services/theme.service';
import { AtlasContextSummaryComponent } from './components/atlas-context-summary.component';
import {
  ComponentSourcePanelComponent,
  ScreenWorkbenchMobileToggleComponent,
  ScreenWorkbenchPreviewComponent,
} from './components/screen-workbench.component';
import { AboutScreenComponent } from './screens/about-screen.component';
import { OverviewScreenComponent } from './screens/overview-screen.component';
import { SettingsScreenComponent } from './screens/settings-screen.component';
import { MapsScreenComponent } from './screens/maps-screen.component';
import { DestinationsScreenComponent } from './screens/destinations-screen.component';
import { IntelScreenComponent } from './screens/intel-screen.component';
import { MediaScreenComponent } from './screens/media-screen.component';
import { AuthoringScreenComponent } from './screens/authoring-screen.component';
import { PlanScreenComponent } from './screens/plan-screen.component';
import { ViewsScreenComponent } from './screens/views-screen.component';
import { StackScreenComponent } from './screens/stack-screen.component';
import { GapScreenComponent } from './screens/gap-screen.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [
    RouterLink,
    AtlasContextSummaryComponent,
    ScreenWorkbenchMobileToggleComponent,
    ScreenWorkbenchPreviewComponent,
    ComponentSourcePanelComponent,
    AboutScreenComponent,
    OverviewScreenComponent,
    SettingsScreenComponent,
    MapsScreenComponent,
    DestinationsScreenComponent,
    IntelScreenComponent,
    MediaScreenComponent,
    AuthoringScreenComponent,
    PlanScreenComponent,
    ViewsScreenComponent,
    StackScreenComponent,
    GapScreenComponent,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="da-shell">
      <header class="da-header">
        <h1>Destination Atlas</h1>
        <p>Current and historic information about world locations — Angular proof (DAS-139)</p>
      </header>

      <div class="da-body-row">
        <div class="da-preview-column">
          <div class="da-context-strip">
            <da-atlas-context-summary
              [locale]="atlas.locale()"
              [userRole]="atlas.userRole()"
              [mapProvider]="atlas.mapProvider()"
              [selectedId]="atlas.selectedId()"
              [theme]="theme.theme()"
              (openSetting)="openSetting($event)"
            />
          </div>

          <nav class="da-nav da-tabbar" aria-label="Screens">
            @for (screen of navScreensBeforeScout(); track screen.id) {
              <a
                class="da-tabbar__tab"
                [routerLink]="atlas.screenRouterLink(screen.id).path"
                [queryParams]="atlas.screenRouterLink(screen.id).queryParams"
                [attr.aria-current]="atlas.screen() === screen.id ? 'page' : null"
              >
                {{ screen.label }}
              </a>
            }
            <button
              type="button"
              class="da-tabbar__tab"
              [attr.aria-current]="atlas.settingsScoutFocus() ? 'page' : null"
              (click)="atlas.openScoutSettings()"
            >
              Scout
            </button>
            @for (screen of navScreensFromSettings(); track screen.id) {
              <a
                class="da-tabbar__tab"
                [routerLink]="atlas.screenRouterLink(screen.id).path"
                [queryParams]="atlas.screenRouterLink(screen.id).queryParams"
                [attr.aria-current]="
                  atlas.screen() === screen.id && !atlas.settingsScoutFocus() ? 'page' : null
                "
              >
                {{ screen.label }}
              </a>
            }
          </nav>

          <div class="da-workbench-host">
            <da-screen-workbench-mobile-toggle
              [mobileView]="mobileView()"
              (viewChange)="mobileView.set($event)"
            />
            <da-screen-workbench-preview [mobileView]="mobileView()">
              @switch (atlas.screen()) {
                @case ('about') {
                  <da-about-screen />
                }
                @case ('overview') {
                  <da-overview-screen [locale]="atlas.locale()" [userRole]="atlas.userRole()" />
                }
                @case ('settings') {
                  <da-settings-screen />
                }
                @case ('maps') {
                  <da-maps-screen />
                }
                @case ('destinations') {
                  <da-destinations-screen />
                }
                @case ('media') {
                  <da-media-screen />
                }
                @case ('authoring') {
                  <da-authoring-screen />
                }
                @case ('intel') {
                  <da-intel-screen />
                }
                @case ('plan') {
                  <da-plan-screen />
                }
                @case ('views') {
                  <da-views-screen />
                }
                @case ('stack') {
                  <da-stack-screen />
                }
                @default {
                  <da-gap-screen [screenId]="atlas.screen()" [label]="activeScreenLabel()" />
                }
              }
            </da-screen-workbench-preview>
          </div>
        </div>

        <da-component-source-panel
          [source]="activeSource()"
          [hidden]="mobileView() === 'preview'"
        />
      </div>
    </div>
  `,
})
export class AppComponent {
  readonly atlas = inject(AtlasStateService);
  readonly theme = inject(ThemeService);

  readonly mobileView = signal<'preview' | 'source'>('preview');

  readonly visibleScreens = computed(() =>
    DESTINATION_ATLAS_SCREENS.filter((screen) => screenAllowedForRole(screen.id, this.atlas.userRole())),
  );

  readonly navScreensBeforeScout = computed(() => {
    const screens = this.visibleScreens();
    const settingsIndex = screens.findIndex((screen) => screen.id === 'settings');
    return settingsIndex >= 0 ? screens.slice(0, settingsIndex) : screens;
  });

  readonly navScreensFromSettings = computed(() => {
    const screens = this.visibleScreens();
    const settingsIndex = screens.findIndex((screen) => screen.id === 'settings');
    return settingsIndex >= 0 ? screens.slice(settingsIndex) : [];
  });

  readonly activeScreenLabel = computed(() => {
    const active = DESTINATION_ATLAS_SCREENS.find((screen) => screen.id === this.atlas.screen());
    return active?.label ?? this.atlas.screen();
  });

  readonly activeSource = computed(() => SCREEN_SOURCES[this.atlas.screen()] ?? '');

  openSetting(field: SettingFieldTarget | 'theme' | 'ai'): void {
    this.atlas.setHighlightTarget(field === 'theme' ? 'theme' : field === 'ai' ? 'ai' : field);
    this.atlas.setScreen('settings');
  }
}
