// packages/react/src/domain/i18n/app-language-select/AppLanguageSelect.tsx
import { createElement, forwardRef, type CSSProperties } from 'react';
import {
  DB_APP_LANGUAGE_SELECT_TAG,
  registerRdAppLanguageSelect,
  type AppLocaleOption,
} from '@rosettadash/web-components/domain/i18n/app-language-select';
import { useCustomElementHost } from '../../../lib/custom-element-host.js';

export type { AppLocaleOption };

export interface AppLanguageSelectProps {
  locales?: AppLocaleOption[];
  value?: string;
  defaultLocale?: string;
  label?: string;
  placeholder?: string;
  className?: string;
  style?: CSSProperties;
  onLocaleChange?: (detail: { locale: string }) => void;
}

/** React wrapper around `<rd-app-language-select>`. */
export const AppLanguageSelect = forwardRef<HTMLElement, AppLanguageSelectProps>(
  function AppLanguageSelect(
    {
      locales,
      value,
      defaultLocale,
      label,
      placeholder,
      className,
      style,
      onLocaleChange,
    },
    ref,
  ) {
    const hostRef = useCustomElementHost(
      {
        register: registerRdAppLanguageSelect,
        attrs: {
          defaultLocale: 'default-locale',
        },
        properties: ['locales'],
        events: {
          'locale-change': 'onLocaleChange',
        },
      },
      { value, defaultLocale, label, placeholder },
      {
        onLocaleChange: onLocaleChange as ((detail: unknown) => void) | undefined,
      },
      ref,
      { locales },
    );

    return createElement(DB_APP_LANGUAGE_SELECT_TAG, {
      ref: hostRef,
      className,
      style,
    });
  },
);

// packages/svelte/src/domain/i18n/app-language-select/AppLanguageSelect.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import {
		DB_APP_LANGUAGE_SELECT_TAG,
		registerRdAppLanguageSelect,
	} from '@rosettadash/web-components/domain/i18n/app-language-select';
	import {
		attachHostEvents,
		setHostAttribute,
		setHostProperty,
	} from '../../../lib/custom-element-host';
	import type { AppLanguageSelectProps } from './types';

	let {
		locales,
		value,
		defaultLocale,
		label,
		placeholder,
		className,
		onLocaleChange,
	}: AppLanguageSelectProps = $props();

	let host: HTMLElement;
	let detachEvents = () => {};

	onMount(() => {
		registerRdAppLanguageSelect();
		detachEvents = attachHostEvents(host, {
			'locale-change': (detail) =>
				onLocaleChange?.(detail as { locale: string }),
		});
		return () => detachEvents();
	});

	$effect(() => {
		if (!host) {
			return;
		}
		setHostProperty(host, 'locales', locales);
		setHostAttribute(host, 'value', value);
		setHostAttribute(host, 'default-locale', defaultLocale);
		setHostAttribute(host, 'label', label);
		setHostAttribute(host, 'placeholder', placeholder);
	});
</script>

<svelte:element this={DB_APP_LANGUAGE_SELECT_TAG} bind:this={host} class={className} />
