// packages/angular/src/visual/chart/pie/pie-chart.ts
import { NgClass } from '@angular/common';
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

export interface PieChartProps {
  title?: string;
  className?: string;
}

/** @rosettadash/angular/visual/chart/pie — visual.chart.pie */
@Component({
  selector: 'rd-chart-pie',
  standalone: true,
  imports: [NgClass],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <section [attr.data-testid]="'rd-chart-pie'" [ngClass]="rootClass()">
      <header class="rd-chart-pie__header"><span>{{ title() ?? 'Pie chart' }}</span></header>
      <div class="rd-chart-pie__pie" aria-hidden="true"></div>
      <ng-content />
    </section>
  `,
})
export class PieChart {
  readonly className = input<string | undefined>(undefined);
  readonly title = input<string | undefined>(undefined);

  readonly rootClass = computed(() =>
    ['rd-chart-pie', this.className()].filter(Boolean).join(' '),
  );
}

// packages/react/src/visual/chart/pie/PieChart.tsx
import { forwardRef, type CSSProperties, type ReactNode } from 'react';

export interface PieChartProps {
  title?: string;
  className?: string;
  style?: CSSProperties;
  children?: ReactNode;
}

/** @rosettadash/react/visual/chart/pie — visual.chart.pie */
export const PieChart = forwardRef<HTMLElement, PieChartProps>(function PieChart(
  props,
  ref,
) {
  const { className, style, children } = props;
  const rootClass = ['rd-chart-pie', className].filter(Boolean).join(' ');

  return (
    <section ref={ref as React.RefObject<HTMLElement>} className={rootClass} style={style} data-testid="rd-chart-pie">
      <header className="rd-chart-pie__header"><span>{props.title ?? 'Pie chart'}</span></header>
      <div className="rd-chart-pie__pie" aria-hidden="true" />
      {children}
    </section>
  );
});
